//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class MMAddressAnnotation, NSArray, NSMutableDictionary, QMapView;

@interface AnnotationLogicController : MMObject
{
    NSMutableDictionary *_annotationDic;
    QMapView *_mapView;
    MMAddressAnnotation *_addressAnnotation;
}

- (void).cxx_destruct;
- (id)addAddressAnnotation:(CDStruct_c3b9c2ee)arg1 Location:(id)arg2 POIName:(id)arg3;
- (id)addFriendAnnotation:(id)arg1;
- (id)addMyselfAnnotationWithHeading:(double)arg1;
@property(readonly, nonatomic) NSArray *allAnnotations;
@property(readonly, nonatomic) NSArray *allUsernames;
- (void)dealloc;
- (id)getAddressAnnotation;
- (id)getClusterUsernamesAroundPoint:(struct CGPoint)arg1;
- (CDStruct_90e2a262)getConvexRegion:(BOOL)arg1;
- (id)getFriendAnnotationWithUsername:(id)arg1;
- (id)getMyselfAnnotation;
- (id)getUserLocation;
- (id)initWithMapView:(id)arg1;
- (void)onlyShowMe;
- (void)removeAddressAnnotation;
- (void)removeAllFriendAnnoations;
- (void)removeAllFriendAnnotationCalloutAnimation;
- (void)removeAllHeadAnnotationCalloutAnimation;
- (void)removeFriendAnnotationWithUsername:(id)arg1;
- (void)removeMyselfAnnotation;
- (void)setAllHeadAnnotationShowCallout:(BOOL)arg1 Animated:(BOOL)arg2;

@end

