//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppRecordMessageNodeView.h"

@class UIView;

@interface AppNoteMessageNodeView : AppRecordMessageNodeView
{
    UIView *m_maskView;
}

+ (BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)cutImage:(id)arg1 toFitSize:(struct CGSize)arg2;
- (id)getBackgroundImage;
- (id)getBackgroundImageHL;
- (id)getFirstImgData:(id)arg1;
- (void)layoutSubviewsInternal;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)updateBkgImage:(BOOL)arg1;
- (void)updateThumbImage;

@end

