//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "EmoticonDescMgrExt.h"
#import "IAppDataExt.h"
#import "IContactMgrExt.h"
#import "IEnterpriseContactMgrExt.h"
#import "IHeadImageExt.h"
#import "IKFContactExt.h"
#import "IQQContactMgrExt.h"
#import "IStrangerContactMgrExt.h"
#import "MMIconActionSheetDelegate.h"
#import "UIViewForceTouchShakeProtocol.h"
#import "WCActionSheetDelegate.h"
#import "WCForceTouchPreviewProtocol.h"
#import "WCForceTouchTriggerLongPressProtocol.h"

@class AppMessageBlockButton, CBaseContact, CMessageWrap, CTRichTextView, MMCPLabel, MMIconActionSheet, NSArray, NSString, UIActivityIndicatorView, UIButton, UIImageView, UIView;

@interface BaseMessageNodeView : MMUIView <IHeadImageExt, IContactMgrExt, IQQContactMgrExt, IStrangerContactMgrExt, WCActionSheetDelegate, IAppDataExt, MMIconActionSheetDelegate, EmoticonDescMgrExt, IKFContactExt, IEnterpriseContactMgrExt, UIViewForceTouchShakeProtocol, WCForceTouchPreviewProtocol, WCForceTouchTriggerLongPressProtocol>
{
    CMessageWrap *m_oMessageWrap;
    CBaseContact *m_oContact;
    CBaseContact *m_oChatContact;
    id <messageNodeViewDelegate> m_delegate;
    unsigned long m_uiTouchBeginTime;
    BOOL m_bIsLongPressHandled;
    unsigned long m_eNodeType;
    UIView *m_oContentView;
    UIView *m_oHeadImageView;
    UIButton *m_oCommentButton;
    MMCPLabel *m_oChatRoomNameLabel;
    UIImageView *m_oBkgImageView;
    BOOL m_bHasLayout;
    float m_lastScreenWidth;
    float m_fContentViewLeftMargin;
    float m_fContentViewRightMargin;
    int m_orientation;
    NSArray *m_arrMenuItems;
    UIButton *m_oSendFailButton;
    UIImageView *m_oSendOKView;
    UIActivityIndicatorView *m_oActivityIndicator;
    UIButton *m_oAppBottomButton;
    AppMessageBlockButton *m_oAppMessageBlockButton;
    BOOL m_donorIconHidden;
    BOOL m_bSendOKShowAnimate;
    float m_fHeightInSizeForFrame;
    BOOL m_bMenuVC;
    MMIconActionSheet *m_iconActionSheet;
    NSString *m_cpKeyForChatRoomMessage;
    BOOL m_isChatRoomMessageUnsafe;
    BOOL m_touchEnded;
    CTRichTextView *m_crashWarningLabel;
    NSString *m_cpKeyForChatRoomDisplayName;
    BOOL m_isChatRoomDisplayNameUnsafe;
    BOOL m_isConverting3dTouchToLongPress;
}

+ (BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)LongPressEvents;
- (void)MenuControllerWillHide:(id)arg1;
- (void)OnAppInfoChanged:(id)arg1;
- (void)OnAppWatermarkChanged:(id)arg1;
- (void)OnLongPressGesture:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)actionSheet:(id)arg1 didDismissWithItem:(id)arg2;
- (void)addFavorite;
- (void)calculateLeftRightMargin;
- (void)calculateSize;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPeek;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)canShowFavMenu;
- (BOOL)canShowMoreMenu;
- (BOOL)canShowRevokeMenu;
- (BOOL)canShowSendTo3rdApp;
- (BOOL)canShowSendToDevices;
- (void)clearActivityView;
- (void)clearAppBottomButton;
- (void)clearSendFailButton;
- (void)clearSendOKView;
- (void)dealloc;
@property(readonly, nonatomic) __weak UIView *forceTouchShakeView;
- (void)forward;
- (id)getCurrentNodeAccessibilityDescription:(id)arg1;
- (id)getMoreMainInfomationAccessibilityDescription;
- (struct CGPoint)getSendOKViewOrgin;
- (BOOL)hasForwardInList:(id)arg1;
- (void)hideUIStatus;
- (void)initAcitivityView;
- (void)initAppBottomButton;
- (void)initAppMessageBlockButton;
- (void)initChatRoomNameLabel;
- (void)initCommentButton;
- (void)initCrashWarningLabel;
- (void)initHeadImageView;
- (void)initSendFailButton;
- (void)initSendOKView;
- (id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;
- (BOOL)isLocationMessage;
- (BOOL)isPortait;
- (BOOL)isShowChatRoomDisplayName;
- (BOOL)isTouchInView:(id)arg1;
- (void)launch:(id)arg1;
- (void)layoutForCrashWarning;
- (void)layoutSubviews;
- (void)layoutSubviewsInternal;
@property(nonatomic) __weak id <messageNodeViewDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) unsigned long m_eNodeType; // @synthesize m_eNodeType;
- (id)m_msgWrap;
@property(readonly, nonatomic) UIView *m_oContentView; // @synthesize m_oContentView;
@property(nonatomic) int m_orientation; // @synthesize m_orientation;
- (void)onAppear;
- (void)onBrandConnector:(id)arg1;
- (void)onClearResource;
- (void)onComment;
- (void)onDebug:(id)arg1;
- (void)onDelete:(id)arg1;
- (void)onDisappear;
- (void)onEndTouch;
- (void)onForward:(id)arg1;
- (void)onGetEmoticonDesc:(id)arg1 forMd5:(id)arg2;
- (void)onHeadImageChange:(id)arg1;
- (void)onHeadImageClicked:(id)arg1;
- (void)onKFContactHeadImgUpdate:(id)arg1;
- (void)onLongTouch;
- (void)onMenuItemWillHide;
- (void)onModifyContact:(id)arg1;
- (void)onModifyEnterpriseContact:(id)arg1;
- (void)onModifyKFContact:(id)arg1;
- (void)onModifyQQContact:(id)arg1;
- (void)onOrientationChanged;
- (void)onRestore:(id)arg1;
- (void)onStrangerContactUpdated:(id)arg1;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)pressedEvents;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)reCalculateSizeIfNeed;
- (void)reLayoutSubviews;
- (void)resend:(id)arg1;
- (void)revokeMsg:(id)arg1;
- (void)setDonorIconHidden:(BOOL)arg1;
- (void)setOrientation:(int)arg1;
- (void)setupWatchSourceBadgeIfNeed;
- (void)shareMsgToOpenSDK:(id)arg1;
- (BOOL)shouldShowForwardBrandItem;
- (void)showConnectorSheet:(id)arg1;
- (void)showOperationMenu:(id)arg1;
- (void)showOperationMenu:(id)arg1 NeedDelete:(BOOL)arg2;
- (void)showOperationMenuWithoutDelete:(id)arg1 CanBeForward:(BOOL)arg2;
- (void)showUIStatus;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)triggerLongPressFor3DTouchAtLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)updateAppBottomButton;
- (void)updateBkgImage:(BOOL)arg1;
- (void)updateChatContact:(id)arg1;
- (void)updateChatRoomDisplayNameCrashProtectedState;
- (void)updateChatRoomMessageCrashProtectedState;
- (void)updateMessageContent:(id)arg1;
- (void)updateNodeStatus:(id)arg1;
- (void)updateStatus:(id)arg1;
- (void)updateThumbImage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

