//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMImagePickerManagerDelegate.h"
#import "MMPickerViewDelegate.h"
#import "MMRegionPickerViewControllerDelegate.h"
#import "MessageObserverDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "settingModifySignDelegate.h"

@class CUsrInfo, MMHeadImageView, MMLoadingView, MMPickerView, MMTableView, NSString;

@interface BottleProfileEditViewController : MMUIViewController <MessageObserverDelegate, MMPickerViewDelegate, settingModifySignDelegate, UITableViewDelegate, UITableViewDataSource, WCActionSheetDelegate, MMRegionPickerViewControllerDelegate, MMImagePickerManagerDelegate>
{
    MMTableView *m_tableView;
    CUsrInfo *m_oUsrInfo;
    MMHeadImageView *m_headImage;
    MMPickerView *m_pickerView;
    unsigned long m_curPickerMode;
    MMLoadingView *m_loadingView;
    unsigned long m_uiUploadHeadEventID;
    BOOL m_bIsFirstIn;
    id <EditBottleProfileDelegate> m_delegate;
    struct map<unsigned int, unsigned int, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, unsigned int>>> m_map;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)MMImagePickerManager:(id)arg1 didFinishPickingImageWithInfo:(id)arg2;
- (void)MMImagePickerManagerDidCancel:(id)arg1;
- (void)MMPickerViewDidChooseRowTitle:(id)arg1 atSessionTitle:(id)arg2;
- (void)MMRegionPickerDidChoosRegion:(id)arg1;
- (void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
- (void)OnPop;
- (void)OnReturn;
- (void)OnSave;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dealloc;
- (int)getLinesForSignature:(id)arg1;
- (id)getSettingHeadImage;
- (id)getViewController;
- (void)goToSandyBeach;
- (void)handleImage:(id)arg1;
- (id)init;
- (void)initData;
- (void)initLoadingView;
- (void)initView;
@property(nonatomic) BOOL m_bIsFirstIn; // @synthesize m_bIsFirstIn;
@property(nonatomic) __weak id <EditBottleProfileDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) CUsrInfo *m_oUsrInfo; // @synthesize m_oUsrInfo;
- (void)makeCellInfoInternal:(id)arg1 col:(id)arg2 value:(id)arg3 mustFill:(BOOL)arg4;
- (id)makeMustFillLabel;
- (void)makeSetAddressCell:(id)arg1;
- (void)makeSetDetailProfileCell:(id)arg1 row:(int)arg2;
- (void)makeSetHeadImageCell:(id)arg1;
- (void)makeSetSexCell:(id)arg1;
- (void)makeSetSignatureCell:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)saveNewSign:(id)arg1;
- (void)showChangeImg;
- (void)showImagePicker:(int)arg1;
- (void)showModifyAddressView;
- (void)showModifySexView:(id)arg1;
- (void)showModifySignView;
- (void)startLoading;
- (void)stopLoading;
- (void)stopLoadingAndShowError:(id)arg1;
- (void)stopLoadingAndShowOK:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (void)updateHead:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

