//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class MMTextView, NSString;

@interface BottleTextView : UIView <UITextViewDelegate>
{
    MMTextView *_textView;
    UIView *shiftView;
}

- (void).cxx_destruct;
- (void)beginEdit;
- (void)clearText;
- (void)dealloc;
- (void)endEdit;
- (id)init;
- (void)initViewWithEditEnabled:(BOOL)arg1;
- (void)initWriteView;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)moveToPoint:(struct CGPoint)arg1;
- (void)readReadWithHeight:(unsigned long)arg1;
- (void)readyWriteWithHeight:(unsigned long)arg1;
@property(retain, nonatomic) UIView *shiftView; // @synthesize shiftView;
- (void)setText:(id)arg1;
- (void)showEditTextViewWithKeyBoardHeight:(unsigned long)arg1;
- (void)showNormalTextView;
- (id)text;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (BOOL)textViewShouldEndEditing:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

