//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "CNetworkStatusExt.h"
#import "IAudioToMessageExt.h"
#import "IEmoticonDownloadExt.h"
#import "INetworkStatusReportWithGPSExt.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "MessageObserverDelegate.h"
#import "PBMessageObserverDelegate.h"

@class CNetworkStatusReportArchive, COOBData, MMTimer, NSDate, NSString, ReportInfo;

@interface CNetworkStatusMgr : MMService <MMService, MessageObserverDelegate, IAudioToMessageExt, CNetworkStatusExt, IEmoticonDownloadExt, MMKernelExt, PBMessageObserverDelegate, INetworkStatusReportWithGPSExt>
{
    BOOL m_bConnecting;
    BOOL m_bConnected;
    BOOL m_bReadToGettingData;
    long long m_n64MsgIdForVoiceMsgToDownload;
    BOOL m_bDownloadingEmoticon;
    BOOL m_bReadOnceAgain;
    BOOL m_bDidCheckNewWiFiInterface;
    unsigned long m_uiConnnectType;
    unsigned long m_uiShortChannelFailCount;
    unsigned long m_uiLastReportTime;
    struct timeval m_tvLastGettingDataTime;
    CNetworkStatusReportArchive *m_reportArchive;
    vector_bc4292e6 m_vecMesssageIdToListen;
    int m_eNetworkStatusType;
    COOBData *m_dtOOB;
    NSDate *m_dtLastReport;
    ReportInfo *m_oReportInfo;
    MMTimer *m_oReportTimer;
    NSString *m_nsLastWifiBssid;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)AddOplogInternal;
- (void)CheckBG2FG;
- (void)CheckReportNetworkInfo:(unsigned long)arg1;
- (id)GetOOBData;
- (id)GetOOBUrl;
- (void)InternalReportNetworkInfo:(id)arg1;
- (void)InternalReportWithGPS:(id)arg1 inScene:(unsigned int)arg2;
- (void)LoadReportInfo;
- (id)MakeSafeReportString:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
- (void)OnAddMessageByReceiver:(id)arg1;
- (void)OnEmoticonDownload:(unsigned long)arg1;
- (void)OnErrorByReceiver:(id)arg1 ErrNo:(int)arg2;
- (void)OnNetworkStatusReportWithGPS:(id)arg1 inScene:(unsigned long)arg2;
- (void)ReachabilityChange:(unsigned long)arg1;
- (void)SaveReportInfo;
- (void)callDisconnectStatusChangedExt;
- (void)checkCallStatusChangedExt;
- (void)dealloc;
- (void)doReportIpxx:(id)arg1;
- (void)doReportNetworkStatus;
- (struct timeval)getCurTimeVal;
- (id)getGpsReportString:(id)arg1;
- (unsigned long)getNetworkStatusType;
- (id)getReportStringWithScene:(unsigned int)arg1;
- (void)handleNetworkStatusChange:(unsigned long)arg1;
- (void)handleReport:(int)arg1;
- (void)handleReportDisconnected:(int)arg1;
- (void)handleReportGettingData:(int)arg1;
- (void)handleReportLongUnConnectCount;
- (void)handleSyncBegin;
- (void)handleSyncEnd;
- (void)handleVoiceDowdload:(id)arg1 error:(BOOL)arg2;
- (id)init;
- (void)initMessageIdToListen;
- (BOOL)isDuringSync;
- (BOOL)isNeedReport;
- (void)loadNetworkStatusReportArchive;
- (void)onAuthOK;
- (void)onServiceEnterBackground;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)onServiceTerminate;
- (void)realCalDisconnected;
- (void)regExt;
- (void)setReadToGettingData;
- (void)translateStatus;
- (void)translateStatusLongConnect;
- (void)translateStatusLongUnConnect;
- (void)unListenMessageId;
- (void)unregExt;
- (void)zeroEmocticonDownloadingStatus;
- (void)zeroVoiceMsgToDownload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

