//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ContactsDataLogicDelegate.h"
#import "MMSearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class ContactsDataLogic, MMSearchBar, MMTableView, NSDictionary, NSMutableDictionary, NSString;

@interface ContactSelectView : UIView <UISearchDisplayDelegate, UITableViewDelegate, UITableViewDataSource, MMSearchBarDelegate, WCActionSheetDelegate, ContactsDataLogicDelegate>
{
    id <ContactSelectViewDelegate> m_delegate;
    MMTableView *m_tableView;
    NSDictionary *m_dicExistContact;
    BOOL m_bShowHistoryGroup;
    BOOL m_bShowRadarCreateRoom;
    BOOL m_bMultiSelect;
    NSMutableDictionary *m_dicMultiSelect;
    ContactsDataLogic *m_contactsDataLogic;
    unsigned long m_uiGroupScene;
    UIView *_tableFooterView;
    NSString *nsCurrentSearchText;
    MMSearchBar *m_mmSearchBar;
}

- (void).cxx_destruct;
- (void)addSelect:(id)arg1;
- (void)cancelSearch;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (void)dealloc;
- (void)didSearchViewTableSelect:(id)arg1;
- (void)doSearch:(id)arg1 Pre:(BOOL)arg2;
- (id)getCellImage:(id)arg1;
- (id)getCellTextView:(id)arg1;
- (id)getMatchTipForUsername:(id)arg1;
- (unsigned int)getTotalSelectCount;
- (void)handleSelectHistoryGroup;
- (void)handleSelectRadarCreateRoom;
- (float)heightForSearchViewTable:(id)arg1;
- (void)initData:(unsigned long)arg1;
- (void)initSearchBar;
- (void)initTableView;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;
- (BOOL)isExisted:(id)arg1;
- (BOOL)isSelected:(id)arg1;
@property(nonatomic) BOOL m_bMultiSelect; // @synthesize m_bMultiSelect;
@property(nonatomic) BOOL m_bShowHistoryGroup; // @synthesize m_bShowHistoryGroup;
@property(nonatomic) BOOL m_bShowRadarCreateRoom; // @synthesize m_bShowRadarCreateRoom;
@property(nonatomic) __weak id <ContactSelectViewDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSDictionary *m_dicExistContact; // @synthesize m_dicExistContact;
@property(retain, nonatomic) NSMutableDictionary *m_dicMultiSelect; // @synthesize m_dicMultiSelect;
@property(nonatomic) unsigned long m_uiGroupScene; // @synthesize m_uiGroupScene;
- (void)makeCell:(id)arg1 contact:(id)arg2;
- (void)makeCell:(id)arg1 contact:(id)arg2 showMatchTip:(BOOL)arg3;
- (void)makeCell:(id)arg1 tableCell:(id)arg2 section:(unsigned int)arg3 row:(unsigned int)arg4;
- (void)makeGroupCell:(id)arg1 head:(id)arg2 title:(id)arg3;
- (void)makeHistoryGroupCell:(id)arg1;
- (void)makeMultiTalkSessionCell:(id)arg1;
- (void)makeRadarCreateRoomCell:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onContactAsynSearchResultChanged:(BOOL)arg1;
- (void)onContactsDataChange;
- (BOOL)onFilterContactCandidate:(id)arg1;
- (void)reloadTableView;
- (void)removeSelect:(id)arg1;
- (void)resetTableViewOffset:(id)arg1;
- (void)searchTextFieldDidBeginEditing;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)setExtraCellLineHidden:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)updateMultiSelect:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

