//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableArray, NSString;

@interface CountryFormatConfig : MMObject
{
    NSString *nsCountryCode;
    NSString *nsISOCode;
    NSMutableArray *arrayFormats;
    unsigned long uiMinLength;
    unsigned long uiMaxLength;
    BOOL bHasLeading;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *arrayFormats; // @synthesize arrayFormats;
@property(nonatomic) BOOL bHasLeading; // @synthesize bHasLeading;
- (id)init;
@property(retain, nonatomic) NSString *nsCountryCode; // @synthesize nsCountryCode;
@property(retain, nonatomic) NSString *nsISOCode; // @synthesize nsISOCode;
@property(nonatomic) unsigned long uiMaxLength; // @synthesize uiMaxLength;
@property(nonatomic) unsigned long uiMinLength; // @synthesize uiMinLength;

@end

