//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VoicePrintLogicControllerFactory.h"

#import "IRecordPermissionCheckExt.h"
#import "IVoicePrintMgrExt.h"
#import "VoicePrintViewControllerDelegate.h"

@class MMTimer, NSString;

@interface CreateVoicePrintLogicController : VoicePrintLogicControllerFactory <IRecordPermissionCheckExt, VoicePrintViewControllerDelegate, IVoicePrintMgrExt>
{
    BOOL _isCreateFirst;
    int _failureTimes;
    float averagePeakMeter;
    MMTimer *mEnvironmentCheckTimeOutTimer;
}

+ (id)factoryMethod;
- (void).cxx_destruct;
- (void)OnBackButtonDone;
- (void)OnClickEnvironmentCheckReTryBtn;
- (void)OnEndRecord:(BOOL)arg1;
- (void)OnEnviromentCheckModeLevelMeter:(unsigned long)arg1 Peak:(float)arg2;
- (void)OnEnviromentCheckResult:(BOOL)arg1;
- (void)OnGetMatchingResult:(int)arg1 andVoiceId:(unsigned long)arg2;
- (void)OnLevelMeter:(unsigned long)arg1 Peak:(float)arg2;
- (void)OnRecordDenied;
- (void)OnRecordPermissioned;
- (void)OnStartRecord;
- (void)OnTalkButtonCanceled;
- (void)OnTalkButtonPressed;
- (void)OnTryVerifyBtnDone;
- (void)OnUploadError:(int)arg1 andVoiceId:(unsigned long)arg2;
- (void)OnViewDidLoad;
- (void)StartEnviromentCheck;
- (void)TimerEnvironmentCheckTimeOut;
- (void)beginAllAnimation;
- (void)callVoicePrintMgrStart;
- (void)dealloc;
- (void)getResourceSuccess;
- (id)initWithScene:(unsigned long)arg1;
@property(retain, nonatomic) MMTimer *mEnvironmentCheckTimeOutTimer; // @synthesize mEnvironmentCheckTimeOutTimer;
- (void)processTimeOut;
- (void)registerExtension;
- (void)startNonBlockLoading;
- (void)stopNonBlockLoading;
- (void)unregisterExtension;
- (void)voicePrintBtnPressed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

