//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PrtlBase.h"

@class NSString;

@interface CSyncBasePrtl : PrtlBase
{
    NSString *m_nsDocPath;
}

- (void).cxx_destruct;
- (id)HandleMemContact:(struct tagMMRoomInfo *)arg1;
- (id)HandleMemContactDetail:(id)arg1 isSimplify:(BOOL)arg2;
- (void)HandleModContact:(struct tagMMModContact *)arg1 Cmd:(unsigned long)arg2;
- (void)HandleModUsrImg:(struct tagMMModUserImg *)arg1;
- (void)ParseCmd:(unsigned long)arg1 Buff:(char *)arg2 Len:(unsigned long)arg3;
@property(retain, nonatomic) NSString *m_nsDocPath; // @synthesize m_nsDocPath;

@end

