//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSData, NSString;

@interface CUploadVoiceWrap : NSObject <WCDBCoding>
{
    NSString *m_nsFromUsrName;
    NSString *m_nsToUsrName;
    long long m_n64SvrID;
    unsigned long m_uiLocalID;
    unsigned long m_uiOffset;
    unsigned long m_uiLen;
    unsigned long m_uiCreateTime;
    unsigned long m_uiVoiceLen;
    unsigned long m_uiVoiceTime;
    unsigned long m_uiVoiceFormat;
    unsigned long m_uiEndFlag;
    NSData *m_dtVoice;
    unsigned long m_uiRetryCount;
    unsigned long m_uiInsertQueueTime;
    unsigned long m_uiCancelFlag;
    unsigned long m_uiVoiceForwardFlag;
    unsigned long m_uiCgi;
    NSString *m_nsMsgThumbUrl;
    NSString *m_nsMsgSource;
    unsigned long m_uiStatus;
    NSString *m_nsExtend;
    NSString *ConStrRes2;
    NSString *ConStrRes3;
    long long m___rowID;
}

+ (id)dummyObject;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *ConStrRes3; // @synthesize ConStrRes3;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
- (const WCDBCondition_8be2a476 *)db_ConStrRes2;
- (const WCDBCondition_8be2a476 *)db_ConStrRes3;
- (const WCDBCondition_24a5b6f7 *)db_m_n64SvrID;
- (const WCDBCondition_8be2a476 *)db_m_nsExtend;
- (const WCDBCondition_8be2a476 *)db_m_nsToUsrName;
- (const WCDBCondition_e9b1f587 *)db_m_uiCancelFlag;
- (const WCDBCondition_e9b1f587 *)db_m_uiCreateTime;
- (const WCDBCondition_e9b1f587 *)db_m_uiEndFlag;
- (const WCDBCondition_e9b1f587 *)db_m_uiInsertQueueTime;
- (const WCDBCondition_e9b1f587 *)db_m_uiLen;
- (const WCDBCondition_e9b1f587 *)db_m_uiLocalID;
- (const WCDBCondition_e9b1f587 *)db_m_uiOffset;
- (const WCDBCondition_e9b1f587 *)db_m_uiRetryCount;
- (const WCDBCondition_e9b1f587 *)db_m_uiStatus;
- (const WCDBCondition_e9b1f587 *)db_m_uiVoiceFormat;
- (const WCDBCondition_e9b1f587 *)db_m_uiVoiceTime;
@property(readonly, copy) NSString *description;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
- (id)init;
@property(retain, nonatomic) NSData *m_dtVoice; // @synthesize m_dtVoice;
@property(nonatomic) long long m_n64SvrID; // @synthesize m_n64SvrID;
@property(retain, nonatomic) NSString *m_nsExtend; // @synthesize m_nsExtend;
@property(retain, nonatomic) NSString *m_nsFromUsrName; // @synthesize m_nsFromUsrName;
@property(retain, nonatomic) NSString *m_nsMsgSource; // @synthesize m_nsMsgSource;
@property(retain, nonatomic) NSString *m_nsToUsrName; // @synthesize m_nsToUsrName;
@property(nonatomic) unsigned long m_uiCancelFlag; // @synthesize m_uiCancelFlag;
@property(nonatomic) unsigned long m_uiCgi; // @synthesize m_uiCgi;
@property(nonatomic) unsigned long m_uiCreateTime; // @synthesize m_uiCreateTime;
@property(nonatomic) unsigned long m_uiEndFlag; // @synthesize m_uiEndFlag;
@property(nonatomic) unsigned long m_uiInsertQueueTime; // @synthesize m_uiInsertQueueTime;
@property(nonatomic) unsigned long m_uiLen; // @synthesize m_uiLen;
@property(nonatomic) unsigned long m_uiLocalID; // @synthesize m_uiLocalID;
@property(nonatomic) unsigned long m_uiOffset; // @synthesize m_uiOffset;
@property(nonatomic) unsigned long m_uiRetryCount; // @synthesize m_uiRetryCount;
@property(nonatomic) unsigned long m_uiStatus; // @synthesize m_uiStatus;
@property(nonatomic) unsigned long m_uiVoiceFormat; // @synthesize m_uiVoiceFormat;
@property(nonatomic) unsigned long m_uiVoiceForwardFlag; // @synthesize m_uiVoiceForwardFlag;
@property(nonatomic) unsigned long m_uiVoiceLen; // @synthesize m_uiVoiceLen;
@property(nonatomic) unsigned long m_uiVoiceTime; // @synthesize m_uiVoiceTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

