//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class DeviceRankSetting, NSString;

@interface DeviceRankSettingMgr : MMService <MMService, PBMessageObserverDelegate>
{
    DeviceRankSetting *_rankSetting;
    BOOL bSettingChanged;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (BOOL)NeedLikeNotify;
- (BOOL)NeedRankNotify;
- (BOOL)NeedRecordDataNotify;
- (BOOL)NeedTakePartIn;
- (void)SetLikeNotify:(BOOL)arg1;
- (void)SetRankNotify:(BOOL)arg1;
- (void)SetRecordDataNotify:(BOOL)arg1;
- (void)SetTakePartIn:(BOOL)arg1;
- (void)UpdateSettingFromSVR;
- (void)UpdateSettingTOSVR;
- (id)getRankSettingFilePath;
- (id)init;
- (void)loadRankSetting;
- (void)saveRankSetting;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

