//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "EmoticonCustomManageAddLogicDelegate.h"
#import "IEmoticonDownloadExt.h"
#import "MMUIViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class EmoticonCustomManageAddLogic, MMEmoticonView, MMToastViewController, NSString, UIActivityIndicatorView, UIView;

@interface EmoticonMessageNodeView : BaseMessageNodeView <IEmoticonDownloadExt, EmoticonCustomManageAddLogicDelegate, MMUIViewControllerDelegate, UIAlertViewDelegate>
{
    UIView *m_rewardTips;
    MMToastViewController *m_toastView;
    unsigned int m_msgDownloadStatus;
    UIActivityIndicatorView *m_oImageLoadingView;
    UIView *m_downloadFailView;
    MMEmoticonView *m_oImageView;
    EmoticonCustomManageAddLogic *_addEmoticonLogic;
}

+ (BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)OnEmoticonDownload:(unsigned long)arg1 withMsgWrap:(id)arg2;
- (void)SaveEmoticon:(id)arg1;
@property(retain, nonatomic) EmoticonCustomManageAddLogic *addEmoticonLogic; // @synthesize addEmoticonLogic=_addEmoticonLogic;
- (float)adjustNoImageSizeWithLengh:(float)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (BOOL)canPurchaseByPid:(id)arg1;
- (void)dealloc;
- (id)getViewController;
- (void)initRewardTipsView;
- (void)layoutSubviewsInternal;
@property(retain, nonatomic) MMEmoticonView *m_oImageView; // @synthesize m_oImageView;
- (void)onAppear;
- (void)onClearResource;
- (void)onClick;
- (void)onClickStopShowTipsButton:(id)arg1;
- (void)onDisappear;
- (void)onForward:(id)arg1;
- (void)onGoToRewardInDetailPage:(id)arg1;
- (void)onLongTouch;
- (void)onMenuItemWillHide;
- (void)onMoreOperate:(id)arg1;
- (void)onShowDetailPage:(id)arg1;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)setCanShowRewardTips:(BOOL)arg1;
- (void)showDetailPageWithNeedScrollToBottom:(BOOL)arg1;
- (void)showDownloadFailView;
- (void)showFinishedTipsWithWording:(id)arg1;
- (void)showLoadingView;
- (void)showOperations;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)startDownloadImage;
- (void)updateNodeStatus:(id)arg1;
- (void)updateStatus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

