//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "CNetworkStatusExt.h"
#import "EmoticonAddFromServerLogicObjectDelegate.h"
#import "EmoticonBackupDeleteNotifyExt.h"
#import "EmoticonBackupLogicObjectDelegate.h"
#import "EmoticonDeleteFromServerLogicObjectDelegate.h"
#import "EmoticonRecoverLogicObjectDelegate.h"
#import "EmoticonRestartBackupWhenDeleteTaskDelegate.h"
#import "IMsgExt.h"
#import "MMKernelExt.h"
#import "MMService.h"

@class EmoticonBackupLogicObject, EmoticonRecoverLogicObject, NSMutableArray, NSString;

@interface EmoticonBackUpMgr : MMService <EmoticonBackupLogicObjectDelegate, EmoticonRecoverLogicObjectDelegate, MMKernelExt, CNetworkStatusExt, IMsgExt, EmoticonDeleteFromServerLogicObjectDelegate, EmoticonAddFromServerLogicObjectDelegate, EmoticonRestartBackupWhenDeleteTaskDelegate, EmoticonBackupDeleteNotifyExt, MMService>
{
    BOOL m_hasOnceStartRecover;
    EmoticonBackupLogicObject *m_backupLogicObject;
    EmoticonRecoverLogicObject *m_recoverLogicObject;
    NSMutableArray *m_notifyTaskList;
    unsigned long m_userActionStatus;
    unsigned long m_lastManageViewUploadTime;
}

+ (unsigned long)ActionStatusAllowRecover;
+ (unsigned long)ActionStatusNoAction;
+ (unsigned long)ActionStatusRecoverForbiden;
- (void).cxx_destruct;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)ReachabilityChange:(unsigned long)arg1;
- (void)backupLocalEmoticonToServer;
- (void)backupLocalEmoticonToServerAndIgnoreOnceLimit:(BOOL)arg1;
- (void)backupLocalEmoticonToServerFromManageView;
- (BOOL)canResumeAddSyncLogic;
- (BOOL)canResumeDeleteSyncLogic;
- (BOOL)canStartCgiNow;
- (void)checkIfServerOverLimitAndBackup;
- (void)dealloc;
- (id)filterMsgType;
- (void)goonRecover;
- (id)init;
- (void)internalGoonRecover;
- (BOOL)isRecoverEmoticonBeenPause;
- (BOOL)isRecoveringEmoticon;
- (BOOL)isRecoveringEmoticonComplete;
- (BOOL)isRecoveringEmoticonFromServer;
- (BOOL)isRecoveringEmoticonPause;
- (BOOL)isUserAllowOnRecover;
- (BOOL)isUserNoActionOnRecover;
- (BOOL)isUserPauseOnRecover;
@property(retain, nonatomic) EmoticonBackupLogicObject *m_backupLogicObject; // @synthesize m_backupLogicObject;
@property(nonatomic) BOOL m_hasOnceStartRecover; // @synthesize m_hasOnceStartRecover;
@property(nonatomic) unsigned long m_lastManageViewUploadTime; // @synthesize m_lastManageViewUploadTime;
@property(retain, nonatomic) NSMutableArray *m_notifyTaskList; // @synthesize m_notifyTaskList;
@property(retain, nonatomic) EmoticonRecoverLogicObject *m_recoverLogicObject; // @synthesize m_recoverLogicObject;
@property(nonatomic) unsigned long m_userActionStatus; // @synthesize m_userActionStatus;
- (void)onAddSyncLogicBeginWithFullMd5List:(id)arg1;
- (void)onAuthOK;
- (void)onDeleteSyncLogicComplete;
- (void)onEmoticonBackupDeleteNotify;
- (void)onEmoticonBackupLogicFailed;
- (void)onEmoticonBackupLogicOk;
- (void)onEmoticonRecoverLogicAutoPauseOnWWan;
- (void)onEmoticonRecoverLogicDownloadOneEmoticonOK;
- (void)onEmoticonRecoverLogicFailed;
- (void)onEmoticonRecoverLogicOk;
- (void)onEmoticonRestartBackupWhenDeleteTaskExecute;
- (void)pauseRecover;
- (void)recoverEmoticonFromServer;
- (void)runNotifyTask;
- (BOOL)shouldSpeedUpRecoverDonwload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

