//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IContactMgrExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSString;

@interface EnterpriseBrandContactMgr : MMService <MMService, IContactMgrExt, PBMessageObserverDelegate>
{
}

- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)callEnterpriseBrandContactModifiedExtension:(id)arg1;
- (void)dealloc;
- (void)forceUpdateEnterpriseBrandContact:(id)arg1;
- (id)getDisabledSubBrandContactList:(id)arg1;
- (id)getEnabledSubBrandContactList:(id)arg1;
- (id)getEnterpriseChatContact:(id)arg1;
- (id)getEnterpriseWebContacts:(id)arg1;
- (id)getMainAndChatBrandListForConnectMsgType:(int)arg1;
- (id)getSubBrandContactList:(id)arg1;
- (id)getSubBrandContacts:(id)arg1 ForConnectMsgType:(int)arg2;
- (void)handleSwitchBrandContact:(id)arg1;
- (BOOL)hasMainBrandForConnectMsgType:(int)arg1;
- (id)init;
- (void)onDeleteContact:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)onModifyContactDraft:(id)arg1;
- (id)sortMainAndChatBrandContacts:(id)arg1;
- (void)switchBrandContact:(id)arg1 enable:(BOOL)arg2;
- (void)updateEnterpriseBrandContactOfMainBrand:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

