//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IEnterpriseGroupMgrExt.h"
#import "IEnterpriseSessionMgrExt.h"
#import "MMWebViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CContact, CEnterpriseContact, MMScrollView, MMTableView, MMUIAlertView, NSString, UIAlertController;

@interface EnterpriseSessionSelectViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, MMWebViewDelegate, IEnterpriseGroupMgrExt, IEnterpriseSessionMgrExt>
{
    CContact *_brandContact;
    CEnterpriseContact *_selectedContact;
    MMTableView *_tableView;
    MMScrollView *_emptyView;
    MMUIAlertView *_selectAlert;
    UIAlertController *_selectAlertController;
    id <EnterpriseSessionSelectViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)cancelSelect:(id)arg1;
- (void)createChatroom:(id)arg1;
- (void)createSingleChat:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <EnterpriseSessionSelectViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)initTableView;
- (void)initView;
- (id)initWithChatSubBrandContact:(id)arg1;
- (void)makeCell:(id)arg1 contact:(id)arg2;
- (void)makeNewSessionCell:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onCreateEnterpriseGroup:(id)arg1 errorCode:(int)arg2 extDic:(id)arg3;
- (void)onEnterpriseSessionChanged;
- (void)onWebViewWillClose:(id)arg1;
- (void)openCreateChat;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)selectContact:(id)arg1;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

