//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMultiMenuTableViewCell.h"

@class UIView;

@interface FavMultiMenuTableViewCell : MMMultiMenuTableViewCell
{
    UIView *coverView;
    BOOL m_selected;
}

- (void).cxx_destruct;
- (void)deleteAction:(id)arg1;
- (void)forwardAction:(id)arg1;
- (void)moreAction:(id)arg1;
- (void)setCoverView:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;

@end

