//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSString;

@interface FavSearchItem : NSObject <WCDBCoding>
{
    unsigned long localId;
    NSString *xml;
    NSString *searchStr;
    unsigned long status;
    long type;
    long subTypes;
    NSString *StrRes1;
    long long m___rowID;
}

+ (id)dummyObject;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
- (const WCDBCondition_8be2a476 *)db_StrRes1;
- (const WCDBCondition_e9b1f587 *)db_localId;
- (const WCDBCondition_8be2a476 *)db_searchStr;
- (const WCDBCondition_e9b1f587 *)db_status;
- (const WCDBCondition_750820ee *)db_subTypes;
- (const WCDBCondition_750820ee *)db_type;
- (const WCDBCondition_8be2a476 *)db_xml;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
- (id)init;
@property(nonatomic) unsigned long localId; // @synthesize localId;
@property(retain, nonatomic) NSString *searchStr; // @synthesize searchStr;
@property(nonatomic) unsigned long status; // @synthesize status;
@property(nonatomic) long subTypes; // @synthesize subTypes;
@property(nonatomic) long type; // @synthesize type;
@property(retain, nonatomic) NSString *xml; // @synthesize xml;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

