//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIButton.h"

@class NSMutableSet, UIColor;

@interface FixTitleColorButton : MMUIButton
{
    NSMutableSet *m_titleColorStateSet;
    NSMutableSet *m_backgroundImageStateSet;
    float m_fixHeight;
    float m_fixLeftRightMargin;
    UIColor *m_fixBackgroundColor;
    BOOL _m_dynamicSize;
    UIColor *_m_highlighBorderColor;
    UIColor *_m_disabledBorderColor;
    UIColor *_m_normalBorderColor;
}

- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) NSMutableSet *m_backgroundImageStateSet; // @synthesize m_backgroundImageStateSet;
@property(retain, nonatomic) UIColor *m_disabledBorderColor; // @synthesize m_disabledBorderColor=_m_disabledBorderColor;
@property(nonatomic) BOOL m_dynamicSize; // @synthesize m_dynamicSize=_m_dynamicSize;
@property(retain, nonatomic) UIColor *m_highlighBorderColor; // @synthesize m_highlighBorderColor=_m_highlighBorderColor;
@property(retain, nonatomic) UIColor *m_normalBorderColor; // @synthesize m_normalBorderColor=_m_normalBorderColor;
@property(retain, nonatomic) NSMutableSet *m_titleColorStateSet; // @synthesize m_titleColorStateSet;
- (void)setBackgroundColor:(id)arg1;
- (void)setBackgroundImage:(id)arg1 forState:(unsigned int)arg2;
- (void)setEnabled:(BOOL)arg1;
- (void)setFixHeight:(float)arg1;
- (void)setFixLeftRightMargin:(float)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)setTitleColor:(id)arg1 forState:(unsigned int)arg2;

@end

