//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FTSTopHitDelegate.h"
#import "IContactLabelMgrExt.h"
#import "IContactMgrExt.h"
#import "IFriendListMgrExt.h"
#import "IMMNewSessionMgrExt.h"

@class FTSTopHitMgr, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface FTSContactMgr : NSObject <IContactMgrExt, IFriendListMgrExt, IContactLabelMgrExt, IMMNewSessionMgrExt, FTSTopHitDelegate>
{
    BOOL _hasInited;
    NSMutableArray *_arrAddressBookFriend;
    NSMutableDictionary *_dicNickNameToFriends;
    NSMutableDictionary *_dicAddressBook;
    NSMutableArray *_arrContact;
    NSMutableDictionary *_dicContact;
    NSMutableDictionary *_dicNewestCreateTimeForSession;
    NSMutableArray *_arrSessionContact;
    NSMutableArray *_arrFilterContact;
    NSMutableArray *_arrFilterAddressBookFriend;
    NSMutableArray *_arrNormalContact;
    NSMutableArray *_arrGroupContact;
    NSMutableArray *_arrBrandContact;
    NSString *_lastQueryText;
    NSString *_newestQueryText;
    NSMutableArray *_arrLastQueryKeywords;
    NSMutableDictionary *_dicSearchMatchTip;
    NSMutableArray *_arrGroupContactForDetailPage;
    NSMutableArray *_arrSourceGroupContact;
    NSString *_lastQueryTextForDetailPage;
    NSString *_newestQueryTextForDetailPage;
    NSMutableArray *_arrLastQueryKeywordsForDetailPage;
    NSMutableDictionary *_dicSearchMatchTipForDetailPage;
    NSMutableDictionary *_dicChinesePinYin;
    NSMutableDictionary *_dicMatchWeChatID;
    NSMutableDictionary *_dicTagNames;
    NSMutableDictionary *_dicCacheFilterContact;
    NSMutableDictionary *_dicCacheFilterAddressBookFriend;
    NSMutableArray *_arrSourceSingleContact;
    NSMutableArray *_arrSingleContactForDetailPage;
    NSMutableArray *_arrAddressBookFriendForDetailPage;
    NSMutableArray *_arrSourceBrandContact;
    NSMutableArray *_arrBrandContactForDetailPage;
    BOOL _hasLoadedAddressContact;
    BOOL _hasLoadedSessionContact;
    BOOL _needMonitorReport;
    BOOL _needSaveRUContact;
    NSMutableDictionary *_dicRUContact;
    int _mgrScene;
    FTSTopHitMgr *_ftsTopHitMgr;
}

- (void).cxx_destruct;
- (void)DeepCopyArrSessionContact:(id)arg1;
- (void)OnChangeNotifyStatus:(id)arg1 withStatus:(BOOL)arg2;
- (void)accessContact:(id)arg1 withParams:(id)arg2;
- (void)addBrandContacts:(id)arg1;
- (void)addPluginContact:(id)arg1 pluginType:(int)arg2;
@property(retain, nonatomic) NSArray *arrLastQueryKeywords; // @synthesize arrLastQueryKeywords=_arrLastQueryKeywords;
@property(retain, nonatomic) NSMutableArray *arrLastQueryKeywordsForDetailPage; // @synthesize arrLastQueryKeywordsForDetailPage=_arrLastQueryKeywordsForDetailPage;
- (void)asyncDetailSearch:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)asyncLoadAllSessionContact;
- (void)asyncSearchText:(id)arg1;
- (void)asyncSearchTextForDetailPage:(id)arg1;
- (void)asyncSearchTextForDetailPageOfBrandContact:(id)arg1;
- (void)asyncSearchTextForDetailPageOfSingleContact:(id)arg1;
- (void)cacheSearchResult;
- (void)cancelSearch;
- (void)cancelSearchForDetailPage;
- (void)cancelSearchForDetailPageOfBrandContact;
- (void)cancelSearchForDetailPageOfSingleContact;
- (void)compactRUContact:(id)arg1;
- (void)dealloc;
- (void)doInitWorker;
- (void)doSearch:(id)arg1;
- (void)doSearchForDetailPage:(id)arg1;
- (void)doSearchForDetailPageOfBrandContact:(id)arg1;
- (void)doSearchForDetailPageOfSingleContact:(id)arg1;
@property(retain, nonatomic) FTSTopHitMgr *ftsTopHitMgr; // @synthesize ftsTopHitMgr=_ftsTopHitMgr;
- (id)getAddressBookDictionary;
- (id)getAddressBookFriendForDetailPage:(id)arg1;
- (id)getAddressBookFriends;
- (id)getAddressBookFriendsByNickName:(id)arg1;
- (unsigned long)getAddressBookFriendsCount;
- (id)getArrSessionContact;
- (id)getBrandContacts;
- (unsigned long)getBrandContactsCount;
- (id)getBrandContactsForDetailPage:(id)arg1;
- (id)getCacheFilterAddressFriend:(id)arg1;
- (id)getCacheFilterContact:(id)arg1;
- (id)getChinesePinyin;
- (id)getContactDictionary;
- (unsigned long)getCreateTimeForUser:(id)arg1;
- (id)getDetailMatchTipForUserName:(id)arg1;
- (id)getDetailPageMatchTipForUserName:(id)arg1;
- (id)getDetailPageMatchTipOfBrandContactForUserName:(id)arg1;
- (id)getDetailPageMatchTipOfSingleContactForUserName:(id)arg1;
- (id)getGroupContacts;
- (unsigned long)getGroupContactsCount;
- (id)getGroupContactsForDetailPage:(id)arg1;
- (id)getLastQueryText;
- (id)getMatchTipForUserName:(id)arg1;
- (id)getNickNameToFriendsDictionary;
- (id)getNormalContacts;
- (unsigned long)getNormalContactsCount;
- (id)getNormalContactsForDetailPage:(id)arg1;
- (id)getRUBrandContact;
- (id)getRUBrandContactKey;
- (id)getSingleContactsForDetailPage:(id)arg1;
- (id)getSourceAddressBook;
- (id)getSourceBrandContactForDetailPage;
- (id)getSourceFilterAddressFriend:(id)arg1;
- (id)getSourceFilterContact:(id)arg1;
- (id)getSourceGroupContactForDetailPage;
- (id)getSourceSingleContactContactForDetailPage;
- (unsigned long)getTotalCount;
- (BOOL)hasAddressBookeFriends;
- (BOOL)hasAllContactLoaded;
- (BOOL)hasBrandContacts;
- (BOOL)hasCacheFilterAddressFriend:(id)arg1;
- (BOOL)hasCacheFilterContact:(id)arg1;
- (BOOL)hasGroupContacts;
- (BOOL)hasInitSessionContact;
- (BOOL)hasMatchWechatID:(id)arg1;
- (BOOL)hasNormalContacts;
- (BOOL)hasSearchDoneForDetailPage:(id)arg1;
- (BOOL)hasSearchDoneForDetailPageOfBrandContact:(id)arg1;
- (BOOL)hasSearchDoneForDetailPageOfSingleContact:(id)arg1;
- (BOOL)hasSearchResult;
- (id)init;
- (void)invalidateDetailCache;
@property(retain, nonatomic) NSString *lastQueryText; // @synthesize lastQueryText=_lastQueryText;
@property(retain, nonatomic) NSString *lastQueryTextForDetailPage; // @synthesize lastQueryTextForDetailPage=_lastQueryTextForDetailPage;
- (void)loadAllSessionContact;
- (void)loadRUContact;
- (id)loadSessionUserName;
- (void)logInfo;
@property(nonatomic) int mgrScene; // @synthesize mgrScene=_mgrScene;
- (void)monitorReport;
@property(nonatomic) BOOL needMonitorReport; // @synthesize needMonitorReport=_needMonitorReport;
@property(retain, nonatomic) NSString *newestQueryText; // @synthesize newestQueryText=_newestQueryText;
@property(retain, nonatomic) NSString *newestQueryTextForDetailPage; // @synthesize newestQueryTextForDetailPage=_newestQueryTextForDetailPage;
- (void)onAllTagNameUpdate;
- (void)onAppTerminate;
- (void)onClearData;
- (void)onContactListUpdate:(unsigned long)arg1;
- (void)onContactTagNameUpdate:(id)arg1;
- (void)onDeleteContact:(id)arg1;
- (void)onDeleteSessionOfUser:(id)arg1;
- (void)onEnterBackground;
- (void)onFriendListUpdated:(id)arg1 ErrorCode:(unsigned long)arg2 Message:(id)arg3;
- (void)onModifyContact:(id)arg1;
- (void)onReloadData;
- (void)removeRUBrandContact:(id)arg1;
- (void)removeRUBrandContact:(id)arg1 type:(int)arg2;
- (void)searchCompletely:(id)arg1;
- (void)searchTextAndNotNotify:(id)arg1;
- (void)searchTextCompletely:(id)arg1;
- (void)selectAddressFriend:(id)arg1;
- (void)selectContact:(id)arg1;
- (void)sortAddressBookFriends:(id)arg1 matchTips:(id)arg2;
- (void)sortContacts:(id)arg1 matchTips:(id)arg2;
- (void)sortFriendList;
- (id)syncSearchTextForSingleContact:(id)arg1 limitCount:(unsigned long)arg2;
- (void)tryInitSessionContactTime;
- (void)tryLoadAddressBook;
- (void)tryLoadAddressBookFriends;
- (void)tryLoadContacts;
- (void)trySaveRUContact;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

