//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSString;

@interface FTSFavSearchItem : NSObject <WCDBCoding>
{
    unsigned long localId;
    unsigned long updateTime;
    NSString *searchTitle;
    NSString *searchDesc;
    NSString *searchSource;
    NSString *searchTag;
    unsigned long FavItemReservedInt;
    NSString *FavItemReservedText;
    long long m___rowID;
}

+ (id)dummyObject;
+ (id)getWCDBTableHelperDictionary;
- (void).cxx_destruct;
@property(nonatomic) unsigned long FavItemReservedInt; // @synthesize FavItemReservedInt;
@property(retain, nonatomic) NSString *FavItemReservedText; // @synthesize FavItemReservedText;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
- (int)compareSearchItemAscending:(id)arg1;
- (void)copyFromItem:(id)arg1;
- (const WCDBCondition_e9b1f587 *)db_FavItemReservedInt;
- (const WCDBCondition_8be2a476 *)db_FavItemReservedText;
- (const WCDBCondition_e9b1f587 *)db_localId;
- (const WCDBCondition_8be2a476 *)db_searchDesc;
- (const WCDBCondition_8be2a476 *)db_searchSource;
- (const WCDBCondition_8be2a476 *)db_searchTag;
- (const WCDBCondition_8be2a476 *)db_searchTitle;
- (const WCDBCondition_e9b1f587 *)db_updateTime;
@property(readonly, copy) NSString *description;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
- (id)init;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic) unsigned long localId; // @synthesize localId;
@property(retain, nonatomic) NSString *searchDesc; // @synthesize searchDesc;
@property(retain, nonatomic) NSString *searchSource; // @synthesize searchSource;
@property(retain, nonatomic) NSString *searchTag; // @synthesize searchTag;
@property(retain, nonatomic) NSString *searchTitle; // @synthesize searchTitle;
@property(nonatomic) unsigned long updateTime; // @synthesize updateTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

