//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MMUILabel, UIImageView, UIView;

@interface FTSWebSearchCell : UITableViewCell
{
    MMUILabel *_keyLabel;
    UIImageView *_searchIcon;
    UIView *_labelContentView;
    MMUILabel *_labelLeft;
    MMUILabel *_subTitleLabel;
    MMUILabel *_labelTop;
    MMUILabel *_labelPlainPrefix;
}

+ (float)getCellHeight;
+ (unsigned long)getWebSearchCellStyle;
- (void).cxx_destruct;
- (void)initView;
- (void)initViewOfContentStyle;
- (void)initViewOfKeywordStyle;
- (void)initViewOfPlainStyle;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)layoutSubviewsOfContentStyle;
- (void)layoutSubviewsOfKeywordStyle;
- (void)layoutSubviewsOfPlainStyle;
- (void)updateWord:(id)arg1;

@end

