//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface GameCenterShareInfo : MMObject <PBCoding>
{
    BOOL shouldShareToFriend;
    BOOL shouldShareToTimeline;
    NSString *messageTitle;
    NSString *messageDetail;
    NSString *iconURL;
    NSString *webURL;
    NSString *timelineTitle;
}

+ (void)initialize;
- (void).cxx_destruct;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *iconURL; // @synthesize iconURL;
@property(retain, nonatomic) NSString *messageDetail; // @synthesize messageDetail;
@property(retain, nonatomic) NSString *messageTitle; // @synthesize messageTitle;
- (void)parseFromResp:(id)arg1;
@property(nonatomic) BOOL shouldShareToFriend; // @synthesize shouldShareToFriend;
@property(nonatomic) BOOL shouldShareToTimeline; // @synthesize shouldShareToTimeline;
@property(retain, nonatomic) NSString *timelineTitle; // @synthesize timelineTitle;
@property(retain, nonatomic) NSString *webURL; // @synthesize webURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

