//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class GameCenterAppStoreControl, GameCenterFeedBackEntrance, GameCenterInstalledMore, GameCenterLibraryEntrance, GameRecommendData, NSArray, NSString, NewHotData, RecentPlayInfoData, TopRecommendBannerData;

@interface GameCenterHomeData : MMObject <PBCoding>
{
    BOOL isShowSearchEntry;
    NSString *searchPlaceholder;
    NSString *classifyUrl;
    NSString *giftURL;
    NSString *giftEntranceTitle;
    RecentPlayInfoData *recentPlayInfo;
    TopRecommendBannerData *topRecommendBanner;
    GameRecommendData *todayRecommend;
    NewHotData *hot;
    GameCenterLibraryEntrance *libraryEntrance;
    GameCenterFeedBackEntrance *feedBackEntrance;
    GameCenterAppStoreControl *appStoreControl;
    NSString *productID;
    NSString *msgIconUrl;
    NSString *msgTitle;
    NSString *msgJumpUrl;
    NSArray *installedList;
    GameCenterInstalledMore *installedMore;
    NSString *installedTitle;
    NSString *giftIconUrl;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) GameCenterAppStoreControl *appStoreControl; // @synthesize appStoreControl;
@property(retain, nonatomic) NSString *classifyUrl; // @synthesize classifyUrl;
- (void)dealloc;
@property(retain, nonatomic) GameCenterFeedBackEntrance *feedBackEntrance; // @synthesize feedBackEntrance;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *giftEntranceTitle; // @synthesize giftEntranceTitle;
@property(retain, nonatomic) NSString *giftIconUrl; // @synthesize giftIconUrl;
@property(retain, nonatomic) NSString *giftURL; // @synthesize giftURL;
@property(retain, nonatomic) NewHotData *hot; // @synthesize hot;
@property(retain, nonatomic) NSArray *installedList; // @synthesize installedList;
@property(retain, nonatomic) GameCenterInstalledMore *installedMore; // @synthesize installedMore;
@property(retain, nonatomic) NSString *installedTitle; // @synthesize installedTitle;
@property(nonatomic) BOOL isShowSearchEntry; // @synthesize isShowSearchEntry;
@property(retain, nonatomic) GameCenterLibraryEntrance *libraryEntrance; // @synthesize libraryEntrance;
@property(retain, nonatomic) NSString *msgIconUrl; // @synthesize msgIconUrl;
@property(retain, nonatomic) NSString *msgJumpUrl; // @synthesize msgJumpUrl;
@property(retain, nonatomic) NSString *msgTitle; // @synthesize msgTitle;
@property(retain, nonatomic) NSString *productID; // @synthesize productID;
@property(retain, nonatomic) RecentPlayInfoData *recentPlayInfo; // @synthesize recentPlayInfo;
@property(retain, nonatomic) NSString *searchPlaceholder; // @synthesize searchPlaceholder;
@property(retain, nonatomic) GameRecommendData *todayRecommend; // @synthesize todayRecommend;
@property(retain, nonatomic) TopRecommendBannerData *topRecommendBanner; // @synthesize topRecommendBanner;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

