//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PrtlBase.h"

@class NSString;

@interface GetPushSystemImagePrtl : PrtlBase
{
    NSString *m_url;
    unsigned long m_offset;
    unsigned long m_mode;
}

- (void).cxx_destruct;
- (BOOL)HandleResp:(void *)arg1;
- (void)InitReq:(void *)arg1;
- (id)init;
@property(nonatomic) unsigned long m_mode; // @synthesize m_mode;
@property(nonatomic) unsigned long m_offset; // @synthesize m_offset;
@property(retain, nonatomic) NSString *m_url; // @synthesize m_url;

@end

