//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "GoogleContactAPIFetchImplDelegate.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"
#import "listGoogleContactsFromWXServerDelegate.h"

@class GoogleContactAPIFetchImpl, GoogleContactLocalCacheImpl, GoogleSetting, ListGoogleContactsFromWXServerImpl, NSMutableArray, NSString;

@interface GoogleContactMgr : MMService <MMService, listGoogleContactsFromWXServerDelegate, GoogleContactAPIFetchImplDelegate, PBMessageObserverDelegate>
{
    GoogleContactLocalCacheImpl *m_contactCacheImpl;
    ListGoogleContactsFromWXServerImpl *_listContactImpl;
    GoogleContactAPIFetchImpl *_apiFetchImpl;
    NSString *m_contactKeyForGoogle;
    NSMutableArray *_contactsFromGoogle;
    GoogleSetting *m_setting;
    BOOL _isStopListContact;
    unsigned long m_listGoogleClickSource;
    unsigned long m_bindGoogleCgiEventID;
    unsigned long m_inviteGoogleCgiEventID;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (BOOL)beginGoogleOauth;
- (BOOL)bindGoogleContact:(id)arg1 force:(BOOL)arg2;
- (void)clearCurrentContactCache;
- (void)dealloc;
- (id)getAuthorizationCode;
- (id)getBindedGoogleContactName;
- (id)getCacheGoogleContacts;
- (id)getFillGoogleContactName;
- (id)getGoogleNickNameForGmail:(id)arg1;
- (id)getGoogleSetting;
- (id)getMd5GoogleContactName;
- (void)handleRespForBindGoogleContact:(id)arg1;
- (void)handleRespForInviteGoogleContact:(id)arg1;
- (id)init;
- (BOOL)inviteGoogleContact:(id)arg1;
- (BOOL)isBindAGoogleAccount;
- (BOOL)listGoogleContact:(unsigned long)arg1;
- (void)listGoogleContactsFromWXServer;
@property(retain, nonatomic) GoogleContactAPIFetchImpl *m_apiFetchImpl; // @synthesize m_apiFetchImpl=_apiFetchImpl;
@property(retain, nonatomic) GoogleContactLocalCacheImpl *m_contactCacheImpl; // @synthesize m_contactCacheImpl;
@property(retain, nonatomic) NSMutableArray *m_contactsFromGoogle; // @synthesize m_contactsFromGoogle=_contactsFromGoogle;
@property(retain, nonatomic) ListGoogleContactsFromWXServerImpl *m_listContactImpl; // @synthesize m_listContactImpl=_listContactImpl;
@property(retain, nonatomic) GoogleSetting *m_setting; // @synthesize m_setting;
- (BOOL)needGoogleOauth;
- (void)onGetGoogleContact:(id)arg1 isDecodeOK:(BOOL)arg2;
- (void)onListGoogleContactsFromWXServer:(id)arg1 ret:(unsigned long)arg2;
- (void)onNetWorkError;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (BOOL)refreshGoogleOauth;
- (void)setOauth:(id)arg1;
- (void)stopListGoogleContact;
- (BOOL)unbindGoogleContact:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

