//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMessageWrap, NSString;

@protocol IDownloadImageExt <NSObject>

@optional
- (void)OnDownloadImageExpired:(CMessageWrap *)arg1;
- (void)OnDownloadImageFail:(CMessageWrap *)arg1;
- (void)OnDownloadImageOk:(CMessageWrap *)arg1;
- (void)OnDownloadImagePart:(CMessageWrap *)arg1 PartLen:(unsigned long)arg2 TotalLen:(unsigned long)arg3;
- (void)OnDownloadImagePartNew:(CMessageWrap *)arg1 PartLen:(unsigned long)arg2 TotalLen:(unsigned long)arg3 TryShow:(BOOL)arg4;
- (void)OnDownloadImageStopByChatName:(NSString *)arg1 FromDelMsg:(BOOL)arg2;
@end

