//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CaptureVideoInfo, ImageInfo, MMAsset, NSData, UIImage, UIViewController;

@protocol ImageControllerDelegate <NSObject>
- (BOOL)CanSendMultiImage;
- (BOOL)CanSendOriginalImage;
- (BOOL)CanSendVideoMsg;
- (UIViewController *)getViewController;

@optional
- (void)CameraControllerDidTakeVideo:(CaptureVideoInfo *)arg1;
- (void)processImageControllerDidCancel:(unsigned int)arg1;
- (void)processImageDidCancel;
- (void)processImageDidFinish;
- (void)processInsertedAsset:(MMAsset *)arg1;
- (void)processInsertedImage:(UIImage *)arg1 ImageInfo:(ImageInfo *)arg2;
- (void)processInsertedImage:(UIImage *)arg1 withData:(NSData *)arg2 ImageInfo:(ImageInfo *)arg3;
@end

