//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MessageObserverDelegate.h"

@class MMTimer;

@interface InitLogicController : MMObject <MessageObserverDelegate>
{
    id <initLogicControllerDelegate> m_delegate;
    vector_bc4292e6 m_vecMesssageIdToListen;
    BOOL m_bIsIniting;
    BOOL m_bFromReg;
    MMTimer *m_percenTimer;
    unsigned long m_curPercent;
    unsigned long m_uiEventID;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
- (void)StopInit;
- (void)dealloc;
- (unsigned long)getCurNetworkStatus;
- (id)init;
- (BOOL)initInternal;
- (void)initMessageIdToListen;
- (BOOL)isCanShowWhatsNew;
- (BOOL)isNeedInit;
@property(nonatomic) BOOL m_bFromReg; // @synthesize m_bFromReg;
@property(readonly, nonatomic) BOOL m_bIsIniting; // @synthesize m_bIsIniting;
@property(nonatomic) __weak id <initLogicControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void)onPercentTimer;
- (void)percentIniting;
- (BOOL)startInit;
- (void)startPercentTimer;
- (void)stopIniting:(unsigned long)arg1;
- (void)stopPercentTimer;

@end

