//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSMutableArray;

@interface ListGoogleContactsFromWXServerImpl : MMObject <PBMessageObserverDelegate>
{
    NSMutableArray *_handlingList;
    NSMutableArray *_finishedList;
    id <listGoogleContactsFromWXServerDelegate> _delegate;
    BOOL _isStop;
    unsigned long m_clickSource;
    unsigned long m_listGoogleContactCgiEventID;
    unsigned int m_LastHandleListCount;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)broadcastFail:(unsigned long)arg1;
- (void)broadcastSuccessed;
- (void)dealloc;
@property(nonatomic) __weak id <listGoogleContactsFromWXServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleListGoogleContactsResp:(id)arg1 Event:(unsigned long)arg2;
- (id)init;
- (void)sendListGoogleContactRequest:(unsigned long)arg1;
- (void)startListGoogleContactsFromWXServer:(id)arg1 clickSource:(unsigned long)arg2;
- (void)stopListGoogleContactsFromWXServer;

@end

