//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "C2ObjcClientCallBackExt.h"

@class NSDate, NSString;

@interface LocalAreaNetworkClient : MMObject <C2ObjcClientCallBackExt>
{
    unsigned long totalReciveLength;
    unsigned long totalSendLength;
    NSDate *start_date;
    unsigned short server_port;
    id <LocalAreaNetworkClientDelegate> m_delegate;
    NSString *server_ip;
}

- (void).cxx_destruct;
- (void)Client_Disconnect;
- (unsigned long)Client_SendData:(id)arg1 andLength:(unsigned int)arg2;
- (float)GetClientRecvSpeed;
- (void)dealloc;
- (id)init;
- (void)initTransferStartTime;
@property(nonatomic) __weak id <LocalAreaNetworkClientDelegate> m_delegate; // @synthesize m_delegate;
- (void)onDisconnect:(id)arg1 port:(unsigned short)arg2;
- (void)onRecv:(id)arg1 port:(unsigned short)arg2 data:(id)arg3 length:(unsigned int)arg4;
@property(retain, nonatomic) NSString *server_ip; // @synthesize server_ip;
@property(nonatomic) unsigned short server_port; // @synthesize server_port;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

