//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ILocationMgrExt.h"
#import "QAnnotation.h"

@class NSString;

@interface MMAddressAnnotation : MMObject <QAnnotation, ILocationMgrExt>
{
    unsigned long _geoTag;
    NSString *_title;
    NSString *_subtitle;
    id <MMAddressAnnotationDelegate> m_delegate;
    CDStruct_2c43369c _coordinate;
}

- (void).cxx_destruct;
@property(nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate=_coordinate;
- (void)createNewRequest;
- (void)dealloc;
- (id)initWithCoordinate:(CDStruct_c3b9c2ee)arg1 Location:(id)arg2 POIName:(id)arg3;
@property(nonatomic) __weak id <MMAddressAnnotationDelegate> m_delegate; // @synthesize m_delegate;
- (void)onDidFindAddress:(id)arg1 forTag:(unsigned long)arg2;
- (void)safeDeleteGeocoder;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

