//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISessionStorageDelegate.h"

@class MMBaseSessionStorage, MMEnterpriseMainUsrData, NSMutableDictionary, NSString;

@interface MMEnterpriseSubSessionCacher : NSObject <ISessionStorageDelegate>
{
    MMEnterpriseMainUsrData *_mainUsrData;
    NSString *_mainUsrName;
    NSString *_sessionType;
    MMBaseSessionStorage *_sessionStorage;
    NSMutableDictionary *_dictUsrname2CellData;
    BOOL _showRedDot;
}

- (void).cxx_destruct;
- (void)addOrUpdateSessionInfo:(id)arg1;
- (void)addOrUpdateSessionList:(id)arg1;
- (void)clearMainUsrRedDot;
- (void)clearMainUsrUnreadCount;
- (void)clearNewArrivalCountWithSubSessionUsrName:(id)arg1;
- (void)clearSessionCache;
- (int)compareSession:(id)arg1 rightSession:(id)arg2;
- (void)dealloc;
- (void)deleteAllSessions;
- (void)deleteMainUsrData;
- (void)deleteNewArrivalCountWithSubSessionUsrName:(id)arg1;
- (void)deleteOldVersionSessionCache;
- (void)deleteSessionAtIndex:(int)arg1;
- (void)deleteSessionWithUsrName:(id)arg1;
- (id)getMainUsrDataPath;
- (BOOL)getMainUsrShowRedDot;
- (unsigned long)getMainUsrUnreadCount;
- (unsigned long)getNewArrivalCountWithSubSessionUsrName:(id)arg1;
- (id)getPathForOldSessionCache;
- (BOOL)hasNewArrivalCountWithSubSessionUsrName:(id)arg1;
- (id)importSessions;
- (id)initWithMainUsrName:(id)arg1;
- (void)loadMainUsrData;
@property(readonly, nonatomic) NSString *mainUsrName; // @synthesize mainUsrName=_mainUsrName;
- (void)performCleanUpNoMsgSessions:(id)arg1;
- (void)saveMainUsrData;
- (id)sessionCellDataAtIndex:(int)arg1;
- (unsigned long)sessionCount;
- (id)sessionInfoAtIndex:(int)arg1;
- (id)sessionInfoList;
- (id)sessionInfoWithUsrName:(id)arg1;
- (void)setMainUsrShowRedDot;
- (void)setNewArrivalCount:(unsigned long)arg1 withSubSessionUsrName:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

