//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableArray, NSString;

@interface MMLoadSessionMgr : MMService <MMService>
{
    NSMutableArray *_arrSessionInfo;
    NSMutableArray *_arrLocalizeSessionInfo;
    unsigned long long _startLoadDataTime;
    unsigned long _loadDataCostTime;
    unsigned int _totalSessionCount;
    NSMutableArray *_arrSessionItems;
    NSMutableArray *_arrDefaultSessionItems;
    BOOL m_loadingData;
    BOOL m_loadDataEnd;
    BOOL m_reloadData;
}

+ (unsigned long long)getEmotionTotalSize;
- (void).cxx_destruct;
- (void)getBrandSessionHolderDetail:(id)arg1;
- (id)getDefaultMigratedSessionItem;
- (void)getDetailInfoForSessionItem:(id)arg1;
- (unsigned int)getSessionCount;
- (unsigned int)getSessionItemsCount;
- (id)getSessionName:(id)arg1;
- (id)getSesssionItemWithIndex:(unsigned int)arg1;
- (unsigned long long)getTotalSessionSize;
- (id)init;
- (BOOL)isDataLoadEnd;
- (BOOL)isLocalizedContactThatCanMigrate:(id)arg1 WithSessionInfo:(id)arg2;
- (void)loadSessionBeforeLoadData;
- (void)onLoadData;
- (void)onLoadLocalizedSessionDataItem;
- (unsigned long)parseMesLocalIdFromPath:(id)arg1;
- (void)startLoadData;
- (void)stopLoadData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

