//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "MMResourceDownloadDelegate.h"

@class MMResourceDownloadTaskContext, MMResourceDownloader, NSString;

@interface MMResourceDownloadTask : NSOperation <MMResourceDownloadDelegate>
{
    NSString *_resUrl;
    MMResourceDownloadTaskContext *_context;
    MMResourceDownloader *_downloader;
    int _retryCnt;
    int _currentCnt;
    id <MMResourceDownloadDelegate> _downloadDelegate;
    BOOL _bExecuting;
    BOOL _bFinished;
    BOOL _bCancelled;
}

- (void).cxx_destruct;
- (void)cancelDownload;
@property(readonly, retain, nonatomic) MMResourceDownloadTaskContext *context; // @synthesize context=_context;
@property(nonatomic) int currentCnt; // @synthesize currentCnt=_currentCnt;
- (void)dealloc;
@property(nonatomic) id <MMResourceDownloadDelegate> downloadDelegate; // @synthesize downloadDelegate=_downloadDelegate;
- (void)emptyThreadTimer:(id)arg1;
- (id)initWithResUrl:(id)arg1 context:(id)arg2;
- (BOOL)isConcurrent;
- (BOOL)isExecuting;
- (BOOL)isFinished;
- (void)onDownloadFinish:(int)arg1 downloadData:(id)arg2 resUrl:(id)arg3;
@property(readonly, copy, nonatomic) NSString *resUrl; // @synthesize resUrl=_resUrl;
@property(nonatomic) int retryCnt; // @synthesize retryCnt=_retryCnt;
- (void)start;
- (void)startDownload;
- (void)startRunloop:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

