//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "EmoticonStoreDownloadViewDelegate.h"

@class EmoticonStoreDownloadView, EmoticonStoreItem, MMWebImageView, NSString, UIImageView, UILabel, UIView;

@interface MMStoreEmotionHotCell : UICollectionViewCell <EmoticonStoreDownloadViewDelegate>
{
    MMWebImageView *_emotionButton;
    UILabel *_emotionTitleLabel;
    EmoticonStoreItem *_item;
    UIView *_imageBackgroundView;
    int _type;
    int _scene;
    MMWebImageView *_tagImageView;
    UIImageView *_newImageView;
    EmoticonStoreDownloadView *_m_downloadView;
    int _cellType;
}

- (void).cxx_destruct;
@property(nonatomic) int cellType; // @synthesize cellType=_cellType;
- (void)hideFreeLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadTagImageView;
@property(retain, nonatomic) EmoticonStoreDownloadView *m_downloadView; // @synthesize m_downloadView=_m_downloadView;
- (void)onDownloadFinished;
- (void)setBoardViewRecommendCellStyle;
- (void)setCellBackgroundColor:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)setPersonalCellStyle;
- (void)setScene:(int)arg1 andType:(int)arg2;
- (void)setSelected:(BOOL)arg1;
- (void)setupButton;
- (void)setupButtonImageURL:(id)arg1;
- (void)setupDownloadView;
- (void)setupEmotionStoreItem:(id)arg1 delegate:(id)arg2 Entrance:(unsigned long)arg3 andType:(int)arg4;
- (void)setupFrameView;
- (void)setupLabel;
- (void)setupLabelWithTitle:(id)arg1;
- (void)setupViews;
- (void)showFreeLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

