//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowViewController.h"

#import "UIAlertViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class NSString, UIButton, UIImage, UIImageView, UILabel, UIView;

@interface OnlineDeviceInfoViewController : MMWindowViewController <UIAlertViewDelegate, WCActionSheetDelegate>
{
    UIImage *_deviceImg;
    UIImageView *_deviceView;
    UIButton *_logoutBtn;
    UILabel *_tipsLabel;
    UILabel *_descriptionLabel;
    UILabel *_switchDescLabel;
    UIButton *_muteButton;
    UIImageView *_muteArrowView;
    UIButton *_cancelBtn;
    UIView *_bottomLine;
    BOOL _isManualOpen;
    id <OnlineDeviceInfoViewControllerDelegate> _delegate;
    unsigned int _supportedOrientations;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dealloc;
@property(nonatomic) __weak id <OnlineDeviceInfoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getDeviceImgWithIsMuted:(BOOL)arg1;
- (id)init;
- (id)initWithIsManualOpen:(BOOL)arg1;
- (void)onCancel;
- (void)onCancelBtnClicked;
- (void)onLogout;
- (void)onMuteButtonClicked;
- (void)onMuteStateChanged:(BOOL)arg1;
- (void)onOnlineInfoUpdated;
- (void)onTopBarFrameChanged;
@property(nonatomic) unsigned int supportedOrientations; // @synthesize supportedOrientations=_supportedOrientations;
- (void)setupCancelBtn;
- (void)setupDescriptionLabel;
- (void)setupInfoView;
- (void)setupLineView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)updateIsManualOpen:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

