//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDataBase, WCDataBaseTable;

@interface OpLogDB : NSObject
{
    WCDataBase *m_db;
    WCDataBaseTable *m_table;
}

- (void).cxx_destruct;
- (void)CloseDB;
- (BOOL)ConfigWithDir:(id)arg1;
- (BOOL)DeleteOplogInDB:(unsigned long)arg1;
- (id)GetOneOplogInDBAfterOpLogID:(unsigned long)arg1;
- (unsigned long)GetOpLogCount;
- (BOOL)InsertOplogInDB:(id)arg1;
- (void)dealloc;

@end

