//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "contactVerifyLogicDelegate.h"

@class CContact, CContactVerifyLogic, CMessageWrap, MMTableView, NSString, UISwitch, UITextField;

@interface SendVerifyMsgViewController : MMUIViewController <UITextFieldDelegate, UITableViewDataSource, UITableViewDelegate, contactVerifyLogicDelegate>
{
    CContact *m_oVerifyContact;
    UITextField *m_tfVerifyMsg;
    MMTableView *m_tableView;
    UISwitch *m_swWCOutsider;
    CContactVerifyLogic *m_oContactVerifyLogic;
    CContact *m_oChatContact;
    CMessageWrap *m_oSourceMsg;
    id <SendVerifyMsgViewControllerDelegate> _m_delegate;
}

- (void).cxx_destruct;
- (void)contactVerifyOk:(id)arg1 opCode:(unsigned long)arg2;
- (void)dealloc;
- (id)init;
@property(nonatomic) __weak id <SendVerifyMsgViewControllerDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(retain, nonatomic) CContact *m_oChatContact; // @synthesize m_oChatContact;
@property(retain, nonatomic) CMessageWrap *m_oSourceMsg; // @synthesize m_oSourceMsg;
@property(retain, nonatomic) CContact *m_oVerifyContact; // @synthesize m_oVerifyContact;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onCancel;
- (void)onContactVerifyFail;
- (void)onHideKeyBoard;
- (void)onReturn;
- (void)onSendVerifyMsg;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)updateWordCount:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

