//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IClearDataMgrExt.h"
#import "MMRefreshTableFooterDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMTableView, NSString, UIButton, UIImageView, UILabel, WCTimeLineFooterView;

@interface SessionResourceViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, WCActionSheetDelegate, IClearDataMgrExt, MMRefreshTableFooterDelegate>
{
    MMTableView *_tableView;
    WCTimeLineFooterView *_tableFooterView;
    UIImageView *_footerView;
    UIButton *_selectAllButton;
    UIButton *_deleteButton;
    UILabel *_sizeLabel;
    UILabel *_emptyTipLabel;
    BOOL _hasLookDetailed;
    unsigned long _curMaxDataCount;
    vector_91fc892d _arrSelectedData;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dealloc;
- (void)deleteSelectedSessionKeepMsg:(BOOL)arg1;
- (void)didAppear;
- (unsigned long)getDataSize:(const vector_91fc892d *)arg1;
- (id)getDataSizeShowString:(const vector_91fc892d *)arg1;
- (id)getSelectButtonTitle;
- (struct CGRect)getTableViewFrame;
- (id)init;
- (void)initData;
- (void)initFooterPannelView;
- (void)initView;
- (BOOL)isDataEmpty;
- (void)loadMoreData;
- (void)onDeleteSelectedData:(id)arg1;
- (void)onLoadMore;
- (void)onLookDetail:(id)arg1;
- (void)onReloadDataItem;
- (void)onReturn;
- (void)onSelecteAll;
- (void)onSelectedDataChange;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)updateFooterPannelView;
- (void)updateTableFooterView;
- (void)updateTableView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

