//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CrossfadeAnimationDelegate.h"
#import "ILinkEventExt.h"
#import "whatsnewViewDelegateEx.h"

@class CrossfadeAnimationController, MMTableViewInfo, NSString, UILabel;

@interface SettingAboutMMViewController : MMUIViewController <whatsnewViewDelegateEx, CrossfadeAnimationDelegate, ILinkEventExt>
{
    MMTableViewInfo *m_tableViewInfo;
    UILabel *m_labelProduct;
    BOOL m_bFullVersion;
    BOOL m_bFromSetting;
    MMUIViewController *m_whatsNewViewController;
    CrossfadeAnimationController *m_transitionInstance;
}

- (void).cxx_destruct;
- (void)ShowWhatsNew;
- (void)dealloc;
- (id)getHeaderView;
- (id)init;
- (void)onAboutVersion;
- (void)onLaw;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)reloadData;
- (void)showSystemNotice;
- (void)showWhatsNewEnd;
- (void)showWhatsNewWillEnd;
- (void)updateProduct;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

