//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IMusicSearchExt.h"
#import "ITvSearchExt.h"
#import "LocationRetrieveDelegate.h"

@class LocationRetriever, NSString;

@interface ShakeMusicLogicController : MMObject <IMusicSearchExt, ITvSearchExt, LocationRetrieveDelegate>
{
    id <ShakeLogicProxyDelegate> m_delegate;
    unsigned long m_sessionId;
    LocationRetriever *m_locationRetrieve;
}

- (void).cxx_destruct;
- (void)OnEndRecord;
- (void)OnGetMusicItem:(id)arg1 andOffset:(float)arg2 andSessionId:(unsigned long)arg3;
- (void)OnGetTvItem:(id)arg1 andSessionId:(unsigned long)arg2;
- (void)OnMusicError:(int)arg1 andSessionId:(unsigned long)arg2;
- (void)OnStartRecord;
- (void)OnTvError:(int)arg1 andSessionId:(unsigned long)arg2;
- (void)dealloc;
- (id)getMsgForState:(unsigned long)arg1;
- (unsigned long)getSessionId;
- (id)initWithDelegate:(id)arg1;
- (BOOL)isShowBannerView;
- (void)onRetrieveLocationError:(int)arg1;
- (void)onRetrieveLocationOK:(id)arg1;
- (void)onRetrieveLocationTimeOut:(id)arg1;
- (void)shakeReport;
- (void)shakeReset;
- (void)shakeStop;
- (void)shakeTerminate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

