//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMovieCompressorDelegate.h"

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, MMovieCompressor, NSObject<OS_dispatch_queue>, NSString, UIImage;

@interface SightMovieWriter : NSObject <MMovieCompressorDelegate>
{
    NSString *m_moviePath;
    BOOL m_isRecording;
    NSString *m_videoPath;
    NSString *m_audioPath;
    struct CGSize m_videoSize;
    float m_bitRate;
    int m_videoOrientation;
    struct CGAffineTransform m_preferredTransform;
    UIImage *m_firstFrame;
    AVAssetWriter *m_writer;
    AVAssetWriterInput *m_videoInput;
    AVAssetWriterInputPixelBufferAdaptor *m_PixelBufferInput;
    unsigned long m_videoFrame;
    NSObject<OS_dispatch_queue> *m_movieWritingQueue;
    CDStruct_1b6d18a9 m_startTime;
    CDStruct_1b6d18a9 m_previousVideoTime;
    CDStruct_1b6d18a9 m_initializeTime;
    unsigned long long m_audioTimeStamp;
    unsigned long long m_videoTimeStamp;
    BOOL m_isLowPerformance;
    BOOL videoEncodingIsFinished;
    MMovieCompressor *m_audioCompressor;
    BOOL m_disableWritingToFile;
    BOOL _forceMPEG4;
    id <SightMovieWriterDelegate> _delegate;
    float _maxMovieDuration;
    int _videoOrientation;
}

- (void).cxx_destruct;
- (void)appendAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)appendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)cancelAmr;
- (void)cancelWriting;
- (void)compressAudio;
- (void)compressMovieWithExport:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <SightMovieWriterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finishWriting;
@property(nonatomic) BOOL forceMPEG4; // @synthesize forceMPEG4=_forceMPEG4;
- (id)getOutput;
- (id)initWithFilePath:(id)arg1 videoOrientation:(int)arg2 videoSize:(struct CGSize)arg3;
- (id)initWithFilePath:(id)arg1 videoOrientation:(int)arg2 videoSize:(struct CGSize)arg3 bitRate:(float)arg4;
- (void)initWritterOutPut;
- (BOOL)isWriting;
- (void)mMovieCompressor:(id)arg1 onMovieCompressFailed:(unsigned long)arg2;
- (void)mMovieCompressor:(id)arg1 onMovieCompressFinished:(id)arg2 thumbImg:(id)arg3 ret:(unsigned long)arg4;
- (id)makeNewPath:(id)arg1 withSubfix:(id)arg2;
@property(nonatomic) float maxMovieDuration; // @synthesize maxMovieDuration=_maxMovieDuration;
- (void)notifyOutput:(id)arg1;
@property(readonly, nonatomic) int outputType;
- (void)prepareWriting;
- (void)realWriting;
- (void)setOutput:(id)arg1;
@property(nonatomic) int videoOrientation; // @synthesize videoOrientation=_videoOrientation;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *writtingQueue; // @synthesize writtingQueue=m_movieWritingQueue;
- (void)startAmr;
- (void)startWriting;
- (void)stopAmr;
- (void)tryMergeOutputVideo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

