//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "SessionSelectControllerDelegate.h"
#import "ShareMessageConfirmLogicHelperDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCCommitViewResultDelegate.h"

@class CContact, EmotionBannerSet, NSString, ShareMessageConfirmLogicHelper, WCDataItem;

@interface StoreEmotionPageShareLogic : MMObject <ShareMessageConfirmLogicHelperDelegate, SessionSelectControllerDelegate, WCActionSheetDelegate, WCCommitViewResultDelegate>
{
    ShareMessageConfirmLogicHelper *m_shareToFriendHelper;
    NSString *m_titleForShareToTimeline;
    NSString *m_titleForShareToFriend;
    NSString *m_desc;
    NSString *m_iconUrl;
    NSString *m_linkUrl;
    int m_shareToTimelineType;
    int m_shareToFriendType;
    NSString *m_pid;
    unsigned int m_packType;
    unsigned long m_designerUin;
    NSString *m_designerName;
    EmotionBannerSet *m_bannerSet;
    CContact *m_shareContact;
    id <MMUIViewControllerDelegate> _delegate;
    WCDataItem *_timeLineDataItem;
}

+ (id)genProductIdFromTimelineUserData:(id)arg1;
- (void).cxx_destruct;
- (void)OnBackTo3rdApp:(id)arg1;
- (void)OnSelectSession:(id)arg1 SessionSelectController:(id)arg2;
- (void)OnSelectSessionCancel:(id)arg1;
- (void)OnSendMessageCancel:(id)arg1;
- (void)OnSendMessageFail:(id)arg1 WithError:(int)arg2;
- (void)OnSendMessageOK:(id)arg1;
- (void)OnStayAtWeChat:(id)arg1;
- (void)ReportShareAction:(unsigned int)arg1 BannerSet:(id)arg2 Type:(unsigned int)arg3;
- (void)ReportShareAction:(unsigned int)arg1 DesignerUin:(unsigned int)arg2;
- (void)ReportShareAction:(unsigned int)arg1 Pid:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(nonatomic) __weak id <MMUIViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)genShareFriendMessage:(id)arg1;
- (id)genTimelineUserData;
- (id)genUploadTask;
- (id)init;
- (id)initWithBannerSet:(id)arg1;
- (id)initWithPersonalDesigner:(id)arg1 Desc:(id)arg2 OldRedirectUrl:(id)arg3;
- (id)initWithStoreItem:(id)arg1;
- (void)onCancelForwardForForwardView:(id)arg1;
- (void)onDoneForwardForForwardView:(id)arg1;
- (void)rotateToCurrentOrietation;
@property(retain, nonatomic) WCDataItem *timeLineDataItem; // @synthesize timeLineDataItem=_timeLineDataItem;
- (void)shareToFriend;
- (void)shareToTimeline;
- (void)showActionSheetWithSender:(id)arg1;
- (void)showLoadingWithMsg:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

