//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (ForceTouchAnimation)
- (id)blurryImage:(id)arg1 withRadius:(float)arg2 offset:(float)arg3;
- (id)getSnapshotImage;
- (id)getSnapshotImageWithOpaque:(BOOL)arg1 scale:(float)arg2;
- (void)playForceTouchShakeAnimation;
@end

