//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface UIWebView (HackishAccessoryHiding)
+ (void)setAccessoryView:(id)arg1;
- (BOOL)becomeFirstResponder;
- (BOOL)browserViewBecomeFirstResponder;
- (BOOL)browserViewResignFirstResponder;
- (void)ensureHackishSubclassExistsOfBrowserViewClass:(Class)arg1;
- (id)hackishlyFoundBrowserView;
- (id)hackishlyFoundBrowserView:(id)arg1;
- (BOOL)hackishlyHidesInputAccessoryView;
- (id)methodReturningNil;
- (BOOL)mightPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)resignFirstResponder;
- (void)setEnabled:(BOOL)arg1;
- (void)setHackishlyHidesInputAccessoryView:(BOOL)arg1;
@end

