//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VideoVoipView.h"

#import "IRecordPermissionCheckExt.h"
#import "UIAlertViewDelegate.h"

@class MMTimer, NSString, VoipDescriptionButton;

@interface VideoVoipReceiverView : VideoVoipView <UIAlertViewDelegate, IRecordPermissionCheckExt>
{
    BOOL isNeedFormSysMsg;
    BOOL hasAcceptCall;
    BOOL hasHangUp;
    VoipDescriptionButton *m_acceptBtn;
    VoipDescriptionButton *m_hangupBtn;
    VoipDescriptionButton *m_voiceModeButton;
    MMTimer *m_actingTimer;
    unsigned long m_dotCountIncresement;
}

- (void).cxx_destruct;
- (void)OnAccept:(id)arg1 ErrNo:(int)arg2;
- (void)OnAutoHangUp:(id)arg1;
- (void)OnBeHanguped:(id)arg1;
- (void)OnBeginConnect:(id)arg1;
- (void)OnBeginTalk:(id)arg1;
- (void)OnCallInterrupt:(id)arg1;
- (void)OnError:(id)arg1 ErrNo:(int)arg2;
- (void)OnInterrupt:(id)arg1;
- (void)OnNetWorkError:(id)arg1 ErrNo:(int)arg2;
- (void)OnPreConnect:(id)arg1;
- (void)OnRecordDenied;
- (void)OnRecordPermissioned;
- (void)OnRemoteEarMode;
- (void)OnRemoteEarModeFor2G;
- (void)OnSyncError:(id)arg1 ErrNo:(int)arg2;
- (void)OnTalkBrokenError:(id)arg1 ErrNo:(int)arg2;
- (void)OnTimeOut:(id)arg1;
- (void)acceptByVoiceCall;
- (void)acceptCall;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)asyncAcceptAudio;
- (void)asyncAcceptVideo;
- (void)asyncPlaySound;
- (void)asyncStartNetDetect;
- (void)autoUpdateMainStatusString;
- (void)changeToAcceptedAnimation;
- (void)changeToRemoteEarModeBeforeAnswer;
- (void)checkAndShowAlertView;
- (void)checkLostNotifySync;
- (void)dealloc;
- (void)endCallAfterDelay:(float)arg1;
- (void)endCallByCancel;
- (void)hangup;
@property(nonatomic) BOOL hasAcceptCall; // @synthesize hasAcceptCall;
@property(nonatomic) BOOL hasHangUp; // @synthesize hasHangUp;
- (BOOL)hasVideoVoipTalkingViewClickChangeToAudioMode;
- (void)ignoreCall;
- (void)ignoreCallAction;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1 andContact:(id)arg2 isEarMode:(BOOL)arg3 andInitViewMode:(int)arg4;
- (BOOL)isCaller;
@property(nonatomic) BOOL isNeedFormSysMsg; // @synthesize isNeedFormSysMsg;
- (void)layoutAcceptButton;
- (void)layoutHangupButton;
- (void)layoutVoiceModeButton;
@property(retain, nonatomic) VoipDescriptionButton *m_acceptBtn; // @synthesize m_acceptBtn;
@property(retain, nonatomic) MMTimer *m_actingTimer; // @synthesize m_actingTimer;
@property(nonatomic) unsigned long m_dotCountIncresement; // @synthesize m_dotCountIncresement;
@property(retain, nonatomic) VoipDescriptionButton *m_hangupBtn; // @synthesize m_hangupBtn;
@property(retain, nonatomic) VoipDescriptionButton *m_voiceModeButton; // @synthesize m_voiceModeButton;
- (void)markLastVoipInfo;
- (void)onFromBackgroundToForeground;
- (void)realAcceptCall;
- (void)rejectCall;
- (void)startShowView;
- (void)updateFooterView;
- (void)updateStatusLabel;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

