//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimpleAudioFillBufferDelegate.h"

@class AudioFile, NSString, SimpleAudioPlayer;

@interface WavAudioPlayer : NSObject <SimpleAudioFillBufferDelegate>
{
    SimpleAudioPlayer *_m_audioPlayer;
    AudioFile *_m_audioFile;
}

- (void).cxx_destruct;
- (unsigned long)fillPcmBuffer:(short *)arg1 startPacket:(long long)arg2 bufferSize:(unsigned long)arg3;
- (id)init;
@property(retain, nonatomic) AudioFile *m_audioFile; // @synthesize m_audioFile=_m_audioFile;
@property(retain, nonatomic) SimpleAudioPlayer *m_audioPlayer; // @synthesize m_audioPlayer=_m_audioPlayer;
- (void)pause;
- (void)resume;
- (double)simpleRateForBuffer;
- (void)startWithPosition:(unsigned long)arg1;
- (void)stop;
- (void)updatePath:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

