//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCADVideoPlayInfo;

@interface WCADBodyWrap : NSObject
{
    NSString *_adID;
    NSString *_publishID;
    NSString *_uxInfo;
    unsigned long _startPositionType;
    unsigned long _endPositionType;
    float _readHeight;
    float _unReadTopHeight;
    float _unReadBottomHeight;
    float _tableContentY;
    WCADVideoPlayInfo *_playInfo;
    unsigned long _source;
    NSString *_snsStatExt;
    unsigned long long _startTime;
    unsigned long long _endTime;
    unsigned long long _halfStartTime;
    unsigned long long _halfEndTime;
    unsigned long long _allStartTime;
    unsigned long long _allEndTime;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adID; // @synthesize adID=_adID;
@property(nonatomic) unsigned long long allEndTime; // @synthesize allEndTime=_allEndTime;
@property(nonatomic) unsigned long long allStartTime; // @synthesize allStartTime=_allStartTime;
@property(nonatomic) unsigned long endPositionType; // @synthesize endPositionType=_endPositionType;
@property(nonatomic) unsigned long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) unsigned long long halfEndTime; // @synthesize halfEndTime=_halfEndTime;
@property(nonatomic) unsigned long long halfStartTime; // @synthesize halfStartTime=_halfStartTime;
@property(retain, nonatomic) WCADVideoPlayInfo *playInfo; // @synthesize playInfo=_playInfo;
@property(retain, nonatomic) NSString *publishID; // @synthesize publishID=_publishID;
@property(nonatomic) float readHeight; // @synthesize readHeight=_readHeight;
@property(retain, nonatomic) NSString *snsStatExt; // @synthesize snsStatExt=_snsStatExt;
@property(nonatomic) unsigned long source; // @synthesize source=_source;
@property(nonatomic) unsigned long startPositionType; // @synthesize startPositionType=_startPositionType;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) float tableContentY; // @synthesize tableContentY=_tableContentY;
@property(nonatomic) float unReadBottomHeight; // @synthesize unReadBottomHeight=_unReadBottomHeight;
@property(nonatomic) float unReadTopHeight; // @synthesize unReadTopHeight=_unReadTopHeight;
@property(retain, nonatomic) NSString *uxInfo; // @synthesize uxInfo=_uxInfo;

@end

