//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBaseControlMgr.h"

#import "JSEventExt.h"

@class NSString;

@interface WCAddressControlMgr : WCBaseControlMgr <JSEventExt>
{
}

- (void)dealloc;
- (id)init;
- (void)jsEditAddress:(id)arg1;
- (void)jsGetLatestAddresss:(id)arg1;
- (unsigned long)startAddressControlLogic:(id)arg1 jsEvent:(id)arg2;
- (unsigned long)startAddressEntranceControlLogic:(id)arg1;
- (unsigned long)startEditAddressControlLogic:(id)arg1;
- (unsigned long)startEditAddressControlLogic:(id)arg1 jsEvent:(id)arg2 AuthenticationStruct:(id)arg3;
- (unsigned long)startGetAddressControlLogic:(id)arg1;
- (unsigned long)startGetLatestAddressControlLogic:(id)arg1 jsEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

