//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCFacadeExt.h"

@class MMTableView, MMUIWindow, MMWebImageView, NSString, UILabel, UIView, WCMediaItem, WCNewYearHBDetailDataForSns;

@interface WCNewYearHBDetailViewControllerForSns : MMUIViewController <WCFacadeExt, UITableViewDelegate, UITableViewDataSource>
{
    WCMediaItem *_mediaItem;
    MMUIWindow *_fullScreenWindow;
    UIView *_bgView;
    UIView *_coverFrameView;
    MMWebImageView *_coverImgView;
    float _curProgress;
    UILabel *_moneyLabel;
    UILabel *_tipsLabel;
    MMTableView *m_tableView;
    UIView *m_oHeaderView;
    WCNewYearHBDetailDataForSns *_detailData;
    UILabel *_rmbUnitLabel;
}

- (void).cxx_destruct;
- (id)GetHeaderView:(id)arg1;
- (void)dealloc;
- (id)findBarButtonView:(id)arg1;
- (id)getEnterpriseLogo:(unsigned long)arg1;
- (id)getEnterpriseName:(unsigned long)arg1;
- (id)getUsernameListFromMyContactList:(unsigned int)arg1;
- (id)init;
- (void)initGradientBgView;
- (void)initNavBar;
- (void)initTableView;
- (void)makeCell:(id)arg1 cell:(id)arg2 row:(unsigned int)arg3;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onCancelDownloadSuccess:(id)arg1 downloadType:(int)arg2;
- (void)onClose;
- (void)setBorder:(id)arg1;
- (void)setNaviBarTransparent:(BOOL)arg1;
- (void)setupSubviews;
- (BOOL)shouldAutorotate;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)updateWithDetailData:(id)arg1;
- (BOOL)useTransparentNavibar;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

