//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCOutCallExt.h"
#import "MMTipsViewControllerDelegate.h"
#import "WCOutDialPadDelegate.h"

@class MMTimerLabel, NSString, UILabel, UIView, WCOutDialPad;

@interface WCOutCallingViewController : MMUIViewController <IWCOutCallExt, WCOutDialPadDelegate, MMTipsViewControllerDelegate>
{
    BOOL m_buttonsEnable;
    long m_lastAddKeyPadTime;
    UILabel *_logLabel;
    UIView *_normalBigView;
    UILabel *_userLabel;
    UILabel *_stateLabel;
    MMTimerLabel *_timerLabel;
    UILabel *_keyPadInputLabel;
    WCOutDialPad *_dialPad;
}

- (void).cxx_destruct;
- (void)OnPressedDialPadFunctionBtnWithType:(unsigned int)arg1;
- (void)OnPressedDialPadKeyWithText:(id)arg1 andKeyCode:(int)arg2;
- (void)OnUpdateCallStateWithText:(id)arg1 hasBeAccepted:(BOOL)arg2 isCallEnded:(BOOL)arg3 isError:(BOOL)arg4 errorlevel:(unsigned int)arg5 ErrTitle:(id)arg6 showChargeAlert:(BOOL)arg7;
- (void)configBlurBackground;
- (void)configKeyPadBigView;
- (void)configNormalBigView;
- (void)dealloc;
@property(retain, nonatomic) WCOutDialPad *dialPad; // @synthesize dialPad=_dialPad;
- (void)didReceiveMemoryWarning;
- (void)dismiss;
- (void)initView;
- (void)initViewData;
@property(retain, nonatomic) UILabel *keyPadInputLabel; // @synthesize keyPadInputLabel=_keyPadInputLabel;
@property(retain, nonatomic) UILabel *logLabel; // @synthesize logLabel=_logLabel;
@property(retain, nonatomic) UIView *normalBigView; // @synthesize normalBigView=_normalBigView;
- (void)onClickTipsBtn:(id)arg1 Index:(int)arg2;
@property(retain, nonatomic) UILabel *stateLabel; // @synthesize stateLabel=_stateLabel;
@property(retain, nonatomic) MMTimerLabel *timerLabel; // @synthesize timerLabel=_timerLabel;
@property(retain, nonatomic) UILabel *userLabel; // @synthesize userLabel=_userLabel;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

