//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayTranferGetUserNameResponse : NSObject
{
    NSString *m_nsFacingPaidID;
    NSString *m_nsUserNmae;
    NSString *m_nsTruthName;
    unsigned long m_uiTimeStamp;
    unsigned long m_uiPayScene;
    long long m_llTotalMoney;
    NSString *m_nsProductDetail;
    NSString *m_nsTransferXmlContent;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) long long m_llTotalMoney; // @synthesize m_llTotalMoney;
@property(retain, nonatomic) NSString *m_nsFacingPaidID; // @synthesize m_nsFacingPaidID;
@property(retain, nonatomic) NSString *m_nsProductDetail; // @synthesize m_nsProductDetail;
@property(retain, nonatomic) NSString *m_nsTransferXmlContent; // @synthesize m_nsTransferXmlContent;
@property(retain, nonatomic) NSString *m_nsTruthName; // @synthesize m_nsTruthName;
@property(retain, nonatomic) NSString *m_nsUserNmae; // @synthesize m_nsUserNmae;
@property(nonatomic) unsigned long m_uiPayScene; // @synthesize m_uiPayScene;
@property(nonatomic) unsigned long m_uiTimeStamp; // @synthesize m_uiTimeStamp;

@end

