//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "IWCPayControlLogicExt.h"
#import "WCPayLogicMgrExt.h"
#import "WCPaySelectReceiveOrPayViewControllerDelegate.h"

@class NSString, WCPaySelectReceiveOrPayViewController;

@interface WCPaySelectReceiveOrPayControlLogic : WCPayControlLogic <WCPaySelectReceiveOrPayViewControllerDelegate, WCPayLogicMgrExt, IWCPayControlLogicExt>
{
    WCPaySelectReceiveOrPayViewController *targetViewController;
}

- (void).cxx_destruct;
- (void)OnCancel;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)startLogic;
- (void)stopLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

