//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchBarDisplayController.h"

#import "ContactsDataLogicDelegate.h"
#import "ContactsPanelViewDelegate.h"
#import "IFTSContactMgrExt.h"
#import "MMSearchBarDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ContactsPanelView, CreateChatLogic, FTSContactMgr, MMSearchBar, MMTableView, MMUIAlertView, NSMutableArray, NSObject, NSString, UIAlertController, UIButton, WCRedEnvelopesMultiSelectContactsViewController;

@interface WCRedEnvelopesSessionSelectViewController : MMSearchBarDisplayController <IFTSContactMgrExt, UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate, MMSearchBarDelegate, ContactsDataLogicDelegate, ContactsPanelViewDelegate>
{
    int m_iSessionType;
    id <WCRedEnvelopesSessionSelectViewControllerDelegate> m_delegate;
    MMTableView *m_tableView;
    NSMutableArray *m_arrContacts;
    NSMutableArray *m_selectedContacts;
    ContactsPanelView *m_panelView;
    UIButton *m_panelBtn;
    int m_confirmType;
    int m_barTitleType;
    WCRedEnvelopesMultiSelectContactsViewController *m_oWCRedEnvelopesMultiSelectContactsViewController;
    int m_createRoomType;
    MMSearchBar *m_mmSearchBar;
    NSObject *_userData;
    MMUIAlertView *selectAlert;
    UIAlertController *selectAlertController;
    FTSContactMgr *_ftsContactMgr;
    NSString *nsCurrentSearchText;
    NSMutableArray *arrSearchResultOfContacts;
    NSMutableArray *arrSearchResultOfGroup;
    BOOL m_bShowNewSession;
    BOOL m_bFilterMyContact;
    CreateChatLogic *m_createChatLogic;
    NSString *nsNewSessionCellTitle;
}

+ (id)getGroupDispName:(id)arg1;
- (void).cxx_destruct;
- (void)FilterSearchResultOfNormalContacts:(id)arg1;
- (void)HideSelectAlert;
- (void)SearchBarBecomeActive;
- (void)addFakeViewWhenAsynSearchNotReturn;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(nonatomic) int barTitleType; // @synthesize barTitleType=m_barTitleType;
- (void)callbackDelegate;
- (void)cancelSearch;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (int)changeToAllCantactSection:(int)arg1;
@property(nonatomic) int confirmType; // @synthesize confirmType=m_confirmType;
- (void)dealloc;
- (void)delaySearch:(id)arg1 slowMode:(BOOL)arg2;
- (void)delaySearchImp:(id)arg1;
- (void)didClickImageAtIndex:(unsigned long)arg1 withKey:(id)arg2;
- (void)didSearchViewTableSelect:(id)arg1;
- (void)doSearch:(id)arg1 Pre:(BOOL)arg2;
- (id)getCellImage:(id)arg1;
- (id)getGroupDispName:(id)arg1;
- (int)getSectionType:(int)arg1;
- (void)handleSelectIndexPath:(id)arg1 tableView:(id)arg2;
- (void)handleSelectNewSession;
- (float)heightForHeaderInSection:(int)arg1 ForSearchViewTable:(id)arg2;
- (float)heightForSearchViewTable:(id)arg1;
- (id)init;
- (void)initBarItem;
- (void)initData;
- (void)initFooterPanelView;
- (void)initSearchBar;
- (void)initTableView;
- (void)initTitle;
- (void)initView;
- (BOOL)isSelected:(id)arg1;
@property(nonatomic) BOOL m_bFilterMyContact; // @synthesize m_bFilterMyContact;
@property(nonatomic) BOOL m_bShowNewSession; // @synthesize m_bShowNewSession;
@property(retain, nonatomic) CreateChatLogic *m_createChatLogic; // @synthesize m_createChatLogic;
@property(nonatomic) int m_createRoomType; // @synthesize m_createRoomType;
@property(nonatomic) __weak id <WCRedEnvelopesSessionSelectViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void)makeCell:(id)arg1 contact:(id)arg2;
- (void)makeNewSessionCell:(id)arg1;
- (void)mmSearchBarTextDidChange:(id)arg1;
@property(retain, nonatomic) NSString *nsNewSessionCellTitle; // @synthesize nsNewSessionCellTitle;
- (int)numberOfRowsInSection:(int)arg1 ForSearchViewTable:(id)arg2;
- (int)numberOfSectionsForSearchViewTable:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onCancel:(id)arg1;
- (void)onConfirm;
- (void)onContactsDataChange;
- (void)onCreateChatContactReturn:(id)arg1;
- (void)onDone:(id)arg1;
- (void)onFTSContactSearchResultChanged:(BOOL)arg1;
- (BOOL)onFilterContactCandidate:(id)arg1;
- (void)onSelect:(id)arg1;
- (void)performCallback;
- (void)removeFakeViewWhenAsynSearchIsReturn;
- (id)sectionIndexTitlesForTableView:(id)arg1;
@property(retain, nonatomic) NSObject *userData; // @synthesize userData=_userData;
- (void)switchSelect:(id)arg1 atIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)titleForHeaderInSection:(int)arg1 ForSearchViewTable:(id)arg2;
- (void)updatePanelBtn;
- (void)updatePanelView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)viewForHeaderInSection:(int)arg1 ForSearchViewTable:(id)arg2;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

