//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDataProviderDelegate.h"

@class MyWCDB, NSMutableArray, NSMutableDictionary, NSString, WCAdvertiseDataHelper, WCAdvertiseLogicMgr, WCTimelineDataProvider;

@interface WCTimelineMgr : MMObject <WCDataProviderDelegate>
{
    id <WCTimelineDelegate> m_delegate;
    NSMutableArray *m_cache;
    NSMutableArray *m_timelineDataList;
    NSMutableArray *m_advertiseDataList;
    MyWCDB *m_database;
    WCAdvertiseDataHelper *m_adDataHelper;
    WCTimelineDataProvider *m_dataProvider;
    WCAdvertiseLogicMgr *m_adLogicMgr;
    BOOL isNoMoreData;
    unsigned long m_showFlag;
    NSString *nsLatestID;
    BOOL m_needWriteBackDataItemUpdateTime;
    BOOL m_needLoadDataItemUpdateTime;
    NSMutableDictionary *m_dataUpdateTime;
    NSMutableDictionary *m_dicUpdateDataList;
}

- (void).cxx_destruct;
- (void)addDataItem:(id)arg1 notify:(BOOL)arg2;
- (void)beginSession;
- (int)countOfDataItem:(id)arg1;
- (void)dealloc;
- (void)deleteAdvertiseDataItem:(id)arg1;
- (void)deleteDataItem:(id)arg1 notify:(BOOL)arg2;
- (void)endSession;
- (id)findDataItemInCacheByItemID:(id)arg1;
- (id)getDataItem:(id)arg1 OfIndex:(int)arg2;
- (unsigned long)getFirstPageCount;
- (unsigned long)getMaxTimeFromDataList:(id)arg1;
- (unsigned long)getMinChangedTimeBetween:(id)arg1 andMinID:(id)arg2;
- (unsigned long)getMinTimeFromDataList:(id)arg1;
- (unsigned long)getNextPageCount;
- (BOOL)hasAdvertiseInCache;
- (BOOL)hasExistAdInLocal:(id)arg1;
- (id)init;
@property(nonatomic) BOOL isNoMoreData; // @synthesize isNoMoreData;
@property(retain, nonatomic) WCAdvertiseDataHelper *m_adDataHelper; // @synthesize m_adDataHelper;
@property(retain, nonatomic) WCAdvertiseLogicMgr *m_adLogicMgr; // @synthesize m_adLogicMgr;
@property(retain, nonatomic) NSMutableArray *m_cache; // @synthesize m_cache;
@property(retain, nonatomic) WCTimelineDataProvider *m_dataProvider; // @synthesize m_dataProvider;
@property(retain, nonatomic) MyWCDB *m_database; // @synthesize m_database;
@property(nonatomic) __weak id <WCTimelineDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) unsigned long m_showFlag; // @synthesize m_showFlag;
- (void)modifyCache:(id)arg1;
- (void)modifyDataItem:(id)arg1 notify:(BOOL)arg2;
- (void)onDataUpdated:(id)arg1 andData:(id)arg2 andAdData:(id)arg3 withChangedTime:(unsigned long)arg4;
- (void)onDataUpdated:(id)arg1 maxItemID:(unsigned long long)arg2 minItemID:(unsigned long long)arg3 withChangedTime:(unsigned long)arg4;
- (void)onDataUpdated:(id)arg1 withChangedTime:(unsigned long)arg2;
- (void)onNoMoreDataWithRet:(int)arg1;
- (void)onReturnIsAllData:(id)arg1 andAdData:(id)arg2;
- (void)onReturnServerConfig:(id)arg1;
- (void)onReturnShowFlag:(unsigned long)arg1;
- (unsigned long)onServiceCleanCache;
- (void)onServiceCleanDataProviderMd5Cache;
- (void)onServiceEnterBackground;
- (void)onServiceMemoryWarning;
- (void)onServiceTerminate;
- (id)pathForDataItemUpdateTime;
- (void)removeItemNotInCacheFrom:(id)arg1;
- (id)safeAddAdvertiseData:(id)arg1;
- (void)setChangedTimeForDatas:(id)arg1 withChangedTime:(unsigned long)arg2;
- (void)tryDeleteDataItemUpdateTime;
- (void)tryLoadDataItemUpdateTime;
- (void)trySaveDataItemUpdateTime;
- (BOOL)updateData:(id)arg1 WithReferID:(id)arg2;
- (BOOL)updateDataHead:(id)arg1;
- (BOOL)updateDataTail:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

