//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IFavAudioRecorderExt.h"
#import "IRecordPermissionCheckExt.h"
#import "MMService.h"

@class FavAudioRecorder, MMTimer, NSString;

@interface WebviewRecorderManager : MMService <MMService, IFavAudioRecorderExt, IRecordPermissionCheckExt>
{
    FavAudioRecorder *_recorder;
    int _recordStatus;
    NSString *_lastFilePath;
    unsigned int _startRecordTime;
    unsigned int _endRecordTime;
    MMTimer *_recordTimer;
    int _stopReason;
    int _recordTimeoutValue;
}

- (void).cxx_destruct;
- (void)OnFavBeginRecording:(int)arg1;
- (void)OnFavFinishRecord:(id)arg1 VoiceFmt:(unsigned long)arg2;
- (void)dealloc;
- (id)init;
- (BOOL)internalStopRecord;
@property(retain, nonatomic) NSString *lastFilePath; // @synthesize lastFilePath=_lastFilePath;
- (void)notifyFinishRecordOnMainThread:(id)arg1;
- (void)notifyRecordTimeTooShortOnMainThread;
- (void)notifyStartRecordOnMainThread:(id)arg1;
- (void)onTimeCount;
- (BOOL)startRecord;
- (BOOL)stopRecord;
- (void)stopTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

