//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFavAudioPlayerExt.h"

@class NSString, WNNoteVoicePlayView, WNNoteVoiceRecordView;

@interface WNNoteVoiceMgr : NSObject <IFavAudioPlayerExt>
{
    WNNoteVoiceRecordView *_voiceRecordView;
    WNNoteVoicePlayView *_voicePlayView;
    NSString *_curAudioPlayLocalEditorId;
    BOOL _playing;
    BOOL _recording;
    id <WNNoteVoicePlayDelegate> _playDelegate;
}

- (void).cxx_destruct;
- (void)OnAudioPlaying:(id)arg1 Offset:(unsigned long)arg2;
- (void)OnBeginPlay:(id)arg1;
- (void)OnEndPlay:(id)arg1 isForceStop:(BOOL)arg2;
- (void)OnPlayError:(id)arg1;
- (void)cancelRecord;
- (id)createPlayViewWithLocalId:(id)arg1 LocalPath:(id)arg2 Fmt:(unsigned long)arg3 Len:(int)arg4;
- (id)createRecordViewWithObj:(id)arg1 Delegate:(id)arg2;
- (id)curPlayId;
- (void)dealloc;
- (id)init;
@property(nonatomic) __weak id <WNNoteVoicePlayDelegate> playDelegate; // @synthesize playDelegate=_playDelegate;
@property(readonly, nonatomic) BOOL playing; // @synthesize playing=_playing;
@property(readonly, nonatomic) BOOL recording; // @synthesize recording=_recording;
- (void)stopPlay;
- (void)stopRecord;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

