//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WXCGroupMember : NSObject
{
    NSString *_mUserName;
    NSString *_mInviteUserName;
    int _mStatus;
    int _mReason;
    long _mInviteTime;
    int _mHoldStatus;
}

- (void).cxx_destruct;
- (id)description;
@property(nonatomic) int mHoldStatus; // @synthesize mHoldStatus=_mHoldStatus;
@property(nonatomic) long mInviteTime; // @synthesize mInviteTime=_mInviteTime;
@property(copy, nonatomic) NSString *mInviteUserName; // @synthesize mInviteUserName=_mInviteUserName;
@property(nonatomic) int mReason; // @synthesize mReason=_mReason;
@property(nonatomic) int mStatus; // @synthesize mStatus=_mStatus;
@property(copy, nonatomic) NSString *mUserName; // @synthesize mUserName=_mUserName;

@end

