//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"

@class ABtestCase, NSMutableDictionary, NSString;

@interface ABtestMgr : MMService <MMService, IMsgExt>
{
    NSMutableDictionary *dicTestSetting;
    NSMutableDictionary *dicTestPoint;
    ABtestCase *oldTestCase;
    NSMutableDictionary *dicTestPointPeriod;
    unsigned int autoincrement;
}

- (void).cxx_destruct;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)dealloc;
- (id)getABtestFilePath;
- (id)getABtestPoint:(unsigned int)arg1 obj:(id)arg2;
- (id)getABtestSettingFilePath;
- (id)getEffectiveAbTestPoint:(unsigned int)arg1;
- (id)getKeyFromPointID:(unsigned int)arg1 obj:(id)arg2;
- (id)getValue:(unsigned int)arg1;
- (BOOL)hasABtestPoint:(unsigned int)arg1;
- (id)init;
- (void)initABtentCases:(struct XmlReaderNode_t *)arg1;
- (void)initABtestPoints:(id)arg1;
- (BOOL)isABtesting:(unsigned int)arg1 obj:(id)arg2;
- (BOOL)isIgnorePoint:(unsigned int)arg1;
- (void)loadSetting;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)onServiceTerminate;
- (void)removeSetting;
- (void)report:(unsigned int)arg1 actionResult:(id)arg2 actionScene:(unsigned int)arg3;
- (void)reportActionResult:(id)arg1 actionScene:(unsigned int)arg2;
- (void)reportRemainTestPoint;
- (void)saveSetting;
- (void)setActionResult:(id)arg1 actionScene:(unsigned int)arg2 point:(unsigned int)arg3 obj:(id)arg4;
- (void)setActionResult:(id)arg1 point:(unsigned int)arg2 obj:(id)arg3;
- (void)setCheckID:(unsigned int)arg1 point:(unsigned int)arg2 obj:(id)arg3;
- (void)setEnd:(unsigned int)arg1 obj:(id)arg2;
- (void)setEnd:(unsigned int)arg1 obj:(id)arg2 actionResult:(unsigned int)arg3;
- (void)setEnd:(unsigned int)arg1 obj:(id)arg2 actionResultString:(id)arg3;
- (void)setIgnoreForEver:(unsigned int)arg1;
- (void)setStart:(unsigned int)arg1 obj:(id)arg2 checkID:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

