//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class CLocalInfo, CSetting, CSettingExt, CUpdateInfo, NSData, NSRecursiveLock, NSString, SyncBufferInfo;

@interface AccountStorageMgr : MMService <MMService>
{
    NSRecursiveLock *m_oLock;
    SyncBufferInfo *m_oSyncBufferInfo;
    NSData *m_dtKFSyncBuffer;
    BOOL m_testMemoryInvalid;
    BOOL m_testPhysicalInvalid;
    BOOL m_testSettingInvalid;
    CLocalInfo *m_oLocalInfo;
    CSetting *m_oSetting;
    CSettingExt *m_oSettingExt;
    CUpdateInfo *m_oUpdateInfo;
    NSString *m_nsDocPath;
}

- (void).cxx_destruct;
- (void)ClearAllLocalInfo;
- (void)ClearLocalInfo;
- (void)DirectSaveSetting;
- (id)GetKFSyncBuffer;
- (id)GetKFSyncBufferFilePath;
- (id)GetSyncBuffer;
- (id)GetSyncBufferFilePath;
- (id)GetUpdateInfo;
- (void)LoadLocalInfo;
- (void)LoadSetting;
- (void)LoadSettingExt;
- (void)LoadUpdateInfo;
- (void)MainThreadSaveSetting;
- (BOOL)MergeAndSaveKFSyncBuffer:(id)arg1;
- (BOOL)MergeAndSaveSyncBuffer:(id)arg1;
- (void)ResetMemorySyncBuffer;
- (void)SaveLocalInfo:(BOOL)arg1;
- (void)SaveSettingExt;
- (BOOL)SaveSyncBuffer:(id)arg1;
- (void)SaveUpdateInfo;
- (BOOL)ValidForMemorySyncBuffer;
- (BOOL)ValidForPhysicalSyncBuffer;
- (BOOL)ValidForSettingInfo;
- (void)clearSyncBuffer;
- (void)closeResource;
- (void)dealloc;
- (id)init;
- (void)initWithDocPath:(id)arg1;
@property(copy, nonatomic) NSString *m_nsDocPath; // @synthesize m_nsDocPath;
@property(copy, nonatomic) CLocalInfo *m_oLocalInfo; // @synthesize m_oLocalInfo;
@property(copy, nonatomic) CSetting *m_oSetting; // @synthesize m_oSetting;
@property(copy, nonatomic) CSettingExt *m_oSettingExt; // @synthesize m_oSettingExt;
@property(copy, nonatomic) CUpdateInfo *m_oUpdateInfo; // @synthesize m_oUpdateInfo;
- (void)onServiceClearData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

