//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDBCoding.h"

@class NSString, PublicWifiCache, PublicWifiPageInfo;

@interface APBase : MMObject <WCDBCoding>
{
    NSString *ssid;
    NSString *mac;
    unsigned long opCode;
    PublicWifiCache *cache;
    unsigned long scene;
    NSString *qrCode;
    NSString *mpUrl;
    NSString *mid;
    NSString *checkUrl;
    NSString *sessionKey;
    NSString *password;
    unsigned long retcode;
    NSString *errMsg;
    int actionCode;
    NSString *bannerText;
    NSString *showUrl;
    unsigned long protocolType;
    NSString *retMsg;
    int _state;
    PublicWifiPageInfo *_pageInfo;
    double expiredTime;
    long long m___rowID;
}

+ (id)dummyObject;
- (void).cxx_destruct;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(nonatomic) int actionCode; // @synthesize actionCode;
@property(copy, nonatomic) NSString *bannerText; // @synthesize bannerText;
@property(nonatomic) __weak PublicWifiCache *cache; // @synthesize cache;
- (BOOL)canStartWithCurrSSID:(id)arg1;
- (void)cancel;
@property(copy, nonatomic) NSString *checkUrl; // @synthesize checkUrl;
- (const WCDBCondition_750820ee *)db_actionCode;
- (const WCDBCondition_8be2a476 *)db_bannerText;
- (const WCDBCondition_8be2a476 *)db_checkUrl;
- (const WCDBCondition_83998780 *)db_expiredTime;
- (const WCDBCondition_8be2a476 *)db_mac;
- (const WCDBCondition_8be2a476 *)db_mid;
- (const WCDBCondition_8be2a476 *)db_mpUrl;
- (const WCDBCondition_e9b1f587 *)db_opCode;
- (const WCDBCondition_e9b1f587 *)db_protocolType;
- (const WCDBCondition_8be2a476 *)db_qrCode;
- (const WCDBCondition_8be2a476 *)db_retMsg;
- (const WCDBCondition_e9b1f587 *)db_retcode;
- (const WCDBCondition_8be2a476 *)db_showUrl;
- (const WCDBCondition_8be2a476 *)db_ssid;
- (void)dealloc;
@property(readonly, copy) NSString *description;
@property(nonatomic) double expiredTime; // @synthesize expiredTime;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
- (void)handleHomeBarClicked:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSString *mac; // @synthesize mac;
@property(copy, nonatomic) NSString *mid; // @synthesize mid;
@property(copy, nonatomic) NSString *mpUrl; // @synthesize mpUrl;
@property(nonatomic) unsigned long opCode; // @synthesize opCode;
@property(retain, nonatomic) PublicWifiPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(copy, nonatomic) NSString *password; // @synthesize password;
@property(nonatomic) unsigned long protocolType; // @synthesize protocolType;
@property(copy, nonatomic) NSString *qrCode; // @synthesize qrCode;
@property(copy, nonatomic) NSString *retMsg; // @synthesize retMsg;
@property(nonatomic) unsigned long retcode; // @synthesize retcode;
@property(nonatomic) unsigned long scene; // @synthesize scene;
@property(copy, nonatomic) NSString *sessionKey; // @synthesize sessionKey;
@property(copy, nonatomic) NSString *showUrl; // @synthesize showUrl;
@property(retain, nonatomic) NSString *ssid; // @synthesize ssid;
@property(nonatomic) int state; // @synthesize state=_state;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

