//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseAudioPlayer.h"

@class NSString;

@interface AQAudioPlayer : BaseAudioPlayer
{
    BOOL mIsBindMuteSwitch;
    BOOL mIsNeedRestartMusic;
    NSString *mCachedTag;
}

- (void).cxx_destruct;
- (void)autostop;
@property(copy, nonatomic) NSString *mCachedTag; // @synthesize mCachedTag;
@property(nonatomic) BOOL needRestartMusic; // @synthesize needRestartMusic=mIsNeedRestartMusic;
- (void)openAudioFile:(id)arg1;
- (void)play;
- (void)prepareBuffers;
- (BOOL)preparePlayWithAudioFile:(id)arg1 cachedForTag:(id)arg2;
- (void)replay;
- (void)setBindMuteSwitch:(BOOL)arg1;
- (void)setDataFormat;
- (void)setDelegate:(id)arg1;
- (void)setMagicCookieForPlayBack;
- (void)stop;

@end

