//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBaseContactInfoAssist.h"

#import "ICertInfoMgrExt.h"
#import "IEnterpriseBrandContactMgrExt.h"
#import "IEnterpriseContactMgrExt.h"
#import "IKFContactMgrExt.h"
#import "IWCDeviceBrandMgrExt.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CertInfo, MMBrandHeadImageView, MMTableView, NSArray, NSMutableArray, NSString, UIButton, UIView, WCADPageWrap;

@interface BrandUserContactInfoAssist : CBaseContactInfoAssist <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate, IWCDeviceBrandMgrExt, IKFContactMgrExt, IEnterpriseContactMgrExt, IEnterpriseBrandContactMgrExt, ICertInfoMgrExt>
{
    UIButton *_viewMsgBtn;
    UIButton *_followBtn;
    BOOL _isSettingsChanged;
    BOOL _isMuteChanged;
    BOOL _isTopSessionSwitchOn;
    BOOL _isClickedTopSessionSwitch;
    BOOL _isEnterpriseSessionTopChanged;
    BOOL _needGetWorker;
    NSArray *_bindWorkerList;
    MMBrandHeadImageView *m_brandHeadView;
    NSMutableArray *m_arrData;
    UIView *m_titleView;
    MMTableView *m_tableView;
    CertInfo *m_certInfo;
    WCADPageWrap *_profilePageWrap;
    unsigned long _lastCertificationFlag;
    NSString *_searchKeyword;
    unsigned long _searchFromIndex;
    NSString *_searchExtraParamsString;
}

- (void).cxx_destruct;
- (id)GetTableView;
- (void)OnUpdateCertInfo;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)adjustNickNameAndUserNameLabelVerticalCenter;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (int)calBusinessScopeCellHeight;
- (int)calPrivilegesCellHeight;
- (int)calRegisterBodyCellHeight;
- (int)calSignatureCellHeight;
- (int)calTrademarkBodyHeight;
- (int)calVerifySourceCellHeight;
- (void)cancelFocus;
- (void)checkUpdateCertInfo;
- (void)contactVerifyOk:(id)arg1 opCode:(unsigned long)arg2;
- (void)dealloc;
- (id)getAlertMessageForVerifyLogic:(id)arg1;
- (id)getAlertTitleForVerifyLogic:(id)arg1;
- (id)getBrandInfoItemAndRemoveIt:(id)arg1 fromArray:(id)arg2;
- (id)getMatchDescription:(id)arg1;
- (id)getMatchTitle:(id)arg1;
- (id)getPrivilegeIcon:(id)arg1;
- (int)getPrivilegeItemHeight:(id)arg1;
- (float)getRegisterBodyRightWidth;
- (float)getRightLabelWidth;
- (float)getTextFieldTopMarginVerifyLogic:(id)arg1;
- (id)getTitleKey:(id)arg1;
- (id)getUrlItemDescription:(id)arg1;
- (id)getUrlItemUrl:(id)arg1;
- (id)getVerifySourceAttributedString;
- (float)getVerifySourceRightWidth;
- (void)handleAddedContact;
- (id)hardcodeKFWorker;
- (BOOL)hasDeviceUserData;
- (void)initFooterView;
- (void)initHDHeadImage;
- (void)initHeadImage;
- (void)initHeaderView;
- (void)initNickNameLabel;
- (void)initTableView;
- (void)initTitleView;
- (id)initWithContact:(id)arg1 delegate:(id)arg2;
- (BOOL)isContactExpired;
- (BOOL)isDeviceBound;
- (BOOL)isFromNotifyMessage;
- (BOOL)isInCustomAlertMode;
- (BOOL)isTempBrandSession;
@property(retain, nonatomic) NSMutableArray *m_arrData; // @synthesize m_arrData;
- (void)makeAllowPositionCell:(id)arg1;
- (void)makeBindWorkerCell:(id)arg1;
- (void)makeBlockMessageNotifyCell:(id)arg1;
- (void)makeBusinessScopeCell:(id)arg1;
- (void)makeCell:(id)arg1 row:(unsigned int)arg2 section:(unsigned long)arg3;
- (void)makeDisableEnterpriseSubBrand:(id)arg1;
- (void)makeEnterEnterpriseCell:(id)arg1;
- (void)makeEnterpriseBlockMessageCell:(id)arg1;
- (void)makeEnterpriseBrandStikyOnTopCell:(id)arg1;
- (void)makeEnterpriseChatEntryCell:(id)arg1;
- (void)makeEnterpriseNewMessageNotificationCell:(id)arg1;
- (void)makeHideFromProfileCell:(id)arg1;
- (void)makeMerchantRatings:(id)arg1;
- (void)makeMerchantSecurityCell:(id)arg1;
- (void)makeNearFieldCell:(id)arg1;
- (void)makeNewMessageNotificationCell:(id)arg1;
- (void)makePrivilegesCell:(id)arg1;
- (void)makeRegisterBodyCell:(id)arg1;
- (void)makeServicePhoneCell:(id)arg1 withPhone:(id)arg2;
- (void)makeShowDisabledEnterpriseSubBrand:(id)arg1;
- (void)makeShowMessageCell:(id)arg1;
- (void)makeSignatureCell:(id)arg1;
- (void)makeTemplateMsgRecvCell:(id)arg1;
- (void)makeTopSessionCell:(id)arg1;
- (void)makeTrandemarkBodyCell:(id)arg1;
- (void)makeUrlCell:(id)arg1 withData:(id)arg2;
- (void)makeVerifySourceCell:(id)arg1;
- (void)markRecentUsedContact;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onAddToContacts;
- (void)onAllowPositionChanged:(id)arg1;
- (void)onBindDevice;
- (void)onBlockSwitchChanged:(id)arg1;
- (void)onCallServicePhone:(id)arg1;
- (void)onClearContent;
- (void)onClickNavRightButton;
- (void)onContactUpdated;
- (void)onEnableEnterpriseSubBrandBtnSwitched:(id)arg1;
- (void)onEnterEnterprise;
- (void)onEnterEnterpriseChat;
- (void)onEnterWebView:(id)arg1;
- (void)onEnterpriseBlockSwitchChanged:(id)arg1;
- (void)onEnterpriseBrandContactSyncToSvrCompleted:(id)arg1 extParams:(id)arg2;
- (void)onEnterpriseNotificationSwitchChanged:(id)arg1;
- (void)onEnterpriseStickyOnTopSwitchChanged:(id)arg1;
- (void)onGetKFContactsBindList:(id)arg1 errCode:(int)arg2;
- (void)onGetKFContactsDefaultList:(id)arg1 errCode:(int)arg2;
- (void)onNotificationSwitchChanged:(id)arg1;
- (void)onShowCancelFocusTips:(id)arg1;
- (void)onShowDisabledEnterpriseSubBrand;
- (void)onShowMessage;
- (void)onShowSwitchChanged:(id)arg1;
- (void)onSwitchEnableEnterpriseSubBrand;
- (void)onTemplateMsgRecv;
- (void)onTopSessionSwitchChanged:(id)arg1;
- (void)onUpdateKFContactsList:(id)arg1 errCode:(int)arg2;
- (void)onUpdateMyContactUserFlag:(id)arg1 bitMask:(unsigned long)arg2 errCode:(int)arg3;
- (void)onUpdateMyEnterpriseContact:(id)arg1 errCode:(int)arg2;
- (void)onWCDeviceBindEnd:(id)arg1 Error:(id)arg2;
- (void)onWCDeviceUnbindEnd:(id)arg1 Error:(id)arg2;
- (void)opLogToSvr;
- (void)opLogToSvrForTopSession;
- (void)profileDestory;
- (void)recordProfilePageWrap;
- (void)reloadRowData;
- (void)reloadTableView;
@property(retain, nonatomic) NSString *searchExtraParamsString; // @synthesize searchExtraParamsString=_searchExtraParamsString;
@property(nonatomic) unsigned long searchFromIndex; // @synthesize searchFromIndex=_searchFromIndex;
@property(retain, nonatomic) NSString *searchKeyword; // @synthesize searchKeyword=_searchKeyword;
- (BOOL)shouldEnterpriseStickyOnTop;
- (BOOL)shouldMuteEnterpriseNotification;
- (BOOL)shouldReceiveEnterpriseMessage;
- (BOOL)shouldReceiveMessage;
- (void)switchEnableEnterpriseSubBrand;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (unsigned long)transToReportScene:(unsigned long)arg1;
- (void)updateFooterView;
- (void)updateNavigationBarRightButton;
- (void)updateNickNameLabel;
- (void)updateTitleView;
- (float)widthForBusinessScopeTitleLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

