//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "CNetworkStatusExt.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class MMTimer, NSDate, NSString;

@interface CdnComMgr : MMService <MMService, MMKernelExt, PBMessageObserverDelegate, CNetworkStatusExt>
{
    struct CDNTransportComponent *m_pCdnCom;
    struct CdnUploadCallback *m_pUploadCallback;
    struct CdnDownloadCallback *m_pDownloadCallback;
    unsigned long m_uiGetCdnDnsInfoEventID;
    unsigned long m_uiGetCdnCount;
    NSDate *m_tGetCdn;
    MMTimer *m_tmCheckCdnInfo;
    BOOL m_bInitCdnCom;
    BOOL m_bHasGetCdnDns;
}

+ (id)GetCdnRootPath;
+ (id)GetDownloadClientID:(id)arg1 HD:(BOOL)arg2;
+ (id)GetDownloadThumbClientID:(id)arg1;
+ (struct WXConfig)GetWxConfig;
- (void).cxx_destruct;
- (void)CallDownloadExtendsion:(id)arg1;
- (void)CallDownloadProgressExtendsion:(id)arg1;
- (void)CallUploadExtendsion:(id)arg1;
- (void)CallUploadProgressExtendsion:(id)arg1;
- (BOOL)CheckAppAttachExist:(id)arg1 IsLargeFile:(BOOL)arg2;
- (void)CheckCdnInfo;
- (void)GetCdnDnsInfo;
- (id)GetUploadImageBuffer:(id)arg1;
- (void)InternalGetCdnDnsInfo;
- (BOOL)IsAppMsgUseCdn;
- (BOOL)IsCdnAvaible;
- (BOOL)IsImageUseCdn;
- (BOOL)IsMessageCanUseCdnDownload:(id)arg1;
- (BOOL)IsMessageCanUseCdnUpload:(id)arg1;
- (BOOL)IsUseCdn;
- (BOOL)IsVideoUseCdn;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)OnDownloadEnd:(id)arg1;
- (void)OnDownloadProgress:(id)arg1;
- (void)OnUploadEnd:(id)arg1;
- (void)OnUploadProgress:(id)arg1;
- (void)ReachabilityChange:(unsigned long)arg1;
- (void)SetCdnHostIPFromNewDNS;
- (BOOL)StartDownloadAppAttach:(id)arg1 IsLargeFile:(BOOL)arg2 SvrSign:(id)arg3;
- (BOOL)StartDownloadComMedia:(id)arg1;
- (BOOL)StartDownloadImage:(id)arg1 HD:(BOOL)arg2 AutoDownload:(BOOL)arg3;
- (BOOL)StartDownloadNormalFile:(id)arg1;
- (BOOL)StartDownloadRecordMedia:(id)arg1;
- (BOOL)StartDownloadThumb:(id)arg1;
- (BOOL)StartDownloadVideo:(id)arg1 AutoDownload:(BOOL)arg2;
- (BOOL)StartDownloadYearLuckyMoneyImage:(id)arg1;
- (BOOL)StartUploadAppAttach:(id)arg1 IsLargeFile:(BOOL)arg2 FileMd5:(id)arg3 SvrSign:(id)arg4;
- (BOOL)StartUploadComMedia:(id)arg1;
- (BOOL)StartUploadDeviceFile:(id)arg1;
- (BOOL)StartUploadDeviceImage:(id)arg1;
- (BOOL)StartUploadDeviceRankCover:(id)arg1;
- (BOOL)StartUploadFavMedia:(id)arg1;
- (BOOL)StartUploadImage:(id)arg1;
- (BOOL)StartUploadNormalFile:(id)arg1;
- (BOOL)StartUploadRecordMedia:(id)arg1;
- (BOOL)StartUploadShortVideo:(id)arg1;
- (BOOL)StartUploadTimelineMedia:(id)arg1;
- (BOOL)StartUploadTimelineMediaOfSight:(id)arg1;
- (BOOL)StartUploadVideo:(id)arg1;
- (BOOL)StartUploadYearLuckyMoneyImage:(id)arg1;
- (void)StopDownloadAppAttach:(id)arg1;
- (BOOL)StopDownloadAppAttach:(id)arg1 CdnDownloadTaskInfo:(id)arg2;
- (void)StopDownloadComMedia:(id)arg1;
- (BOOL)StopDownloadComMedia:(id)arg1 CdnDownloadTaskInfo:(id)arg2;
- (void)StopDownloadFavMedia:(id)arg1;
- (void)StopDownloadImage:(id)arg1 HD:(BOOL)arg2;
- (BOOL)StopDownloadImage:(id)arg1 HD:(BOOL)arg2 CdnDownloadTaskInfo:(id)arg3;
- (void)StopDownloadNormalFile:(id)arg1;
- (void)StopDownloadRecordMedia:(id)arg1;
- (void)StopDownloadThumb:(id)arg1;
- (void)StopDownloadVideo:(id)arg1;
- (BOOL)StopDownloadVideo:(id)arg1 CdnDownloadTaskInfo:(id)arg2;
- (void)StopDownloadYearLuckyMoneyImage:(id)arg1;
- (void)StopUploadAppAttach:(id)arg1;
- (void)StopUploadComMedia:(id)arg1;
- (void)StopUploadFavMedia:(id)arg1;
- (void)StopUploadImage:(id)arg1;
- (void)StopUploadNormalFile:(id)arg1;
- (void)StopUploadRecordMedia:(id)arg1;
- (void)StopUploadShortVideo:(id)arg1;
- (void)StopUploadTimelineMedia:(id)arg1;
- (void)StopUploadTimelineMediaOfSight:(id)arg1;
- (void)StopUploadVideo:(id)arg1;
- (void)StopUploadYearLuckyMoneyImage:(id)arg1;
- (BOOL)StrartDownloadFavMedia:(id)arg1;
- (void)UnInit;
- (id)calcFileMd5WithFilePath:(id)arg1;
- (void)dealloc;
- (id)genarateResAesKey;
- (id)init;
@property(retain, nonatomic) NSDate *m_tGetCdn; // @synthesize m_tGetCdn;
- (void)onAuthOK;
- (void)onKickQuit;
- (void)onPreQuit;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

