//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CEmojiCataLogWrap : NSObject
{
    NSString *m_nsDisplay;
    NSString *m_nsCataLog;
    unsigned long m_uiLocalID;
    unsigned long m_uiSvrID;
    unsigned long m_uiVersion;
    unsigned long m_uiStatus;
}

- (void).cxx_destruct;
- (void)ChangeForDisplay;
- (id)init;
@property(retain, nonatomic) NSString *m_nsCataLog; // @synthesize m_nsCataLog;
@property(retain, nonatomic) NSString *m_nsDisplay; // @synthesize m_nsDisplay;
@property(nonatomic) unsigned long m_uiLocalID; // @synthesize m_uiLocalID;
@property(nonatomic) unsigned long m_uiStatus; // @synthesize m_uiStatus;
@property(nonatomic) unsigned long m_uiSvrID; // @synthesize m_uiSvrID;
@property(nonatomic) unsigned long m_uiVersion; // @synthesize m_uiVersion;

@end

