//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface ChatBackgroundSettings : NSObject
{
    NSMutableArray *items;
    NSMutableDictionary *backgroundPreferences;
    int currentCID;
    int lastSyncListDate;
}

- (void).cxx_destruct;
- (void)addItem:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *backgroundPreferences; // @synthesize backgroundPreferences;
- (unsigned int)countOfItems;
@property(nonatomic) int currentCID; // @synthesize currentCID;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)getBackgroundPreferenceForUsername:(id)arg1;
- (id)getChatBackgroundItemByCID:(int)arg1;
- (id)getDefaultBackgroundItem;
- (id)initWithCoder:(id)arg1;
- (id)initWithDefault;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items;
- (id)keyPaths;
@property(nonatomic) int lastSyncListDate; // @synthesize lastSyncListDate;
- (void)removeItem:(id)arg1;
- (void)setBackgroundPreference:(id)arg1 forUsername:(id)arg2;

@end

