//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PluginContactInfoAssist.h"

#import "UIAlertViewDelegate.h"

@class NSString, UISwitch;

@interface CMediaNoteContactInfoAssist : PluginContactInfoAssist <UIAlertViewDelegate>
{
    UISwitch *m_syncMailSwitch;
}

- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)getPluginIntro;
- (void)onNewMsg;
- (void)onSwitchValueChange:(id)arg1;
- (void)onSwitchViewOn;
- (void)reloadInstalledTableViewData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

