//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TagViewController.h"

#import "ContactTagEditLogicDelegate.h"
#import "IContactLabelMgrExt.h"
#import "UIAlertViewDelegate.h"

@class CContact, ContactTagEditLogic, NSString;

@interface ContactTagViewController : TagViewController <IContactLabelMgrExt, UIAlertViewDelegate, ContactTagEditLogicDelegate>
{
    CContact *m_contact;
    ContactTagEditLogic *m_TagEditLogic;
    BOOL _bIsNeedReloadView;
    BOOL isAlreadyDisMissSelf;
}

+ (id)genContactTagButton:(id)arg1 Height:(float)arg2;
+ (id)genContactTagProfileButton:(id)arg1 Height:(float)arg2;
- (void).cxx_destruct;
- (void)InternalDisMissSelfAnimated:(BOOL)arg1;
- (void)OnMyCancel;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)buildAllTagsData:(id)arg1;
- (void)buildContactTagsData:(id)arg1;
- (void)dealloc;
- (void)editCancel;
- (void)editDone:(id)arg1;
- (id)getAllTagNameList;
- (id)getContactTagNameList;
- (void)initData;
- (void)initView;
- (id)initWithContact:(id)arg1;
@property(retain, nonatomic) CContact *m_contact; // @synthesize m_contact;
- (void)onAllContactLabelUpdated:(id)arg1 withRetCode:(int)arg2 andEventId:(unsigned long)arg3;
- (void)onJobForTagEditRet:(int)arg1;
- (void)onTouchView:(id)arg1;
- (void)reloadAllTags;
- (void)reloadCurrentTags;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

