//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSString;

@interface DBBottleContact : NSObject <WCDBCoding>
{
    NSString *userName;
    NSString *nickName;
    unsigned long sex;
    NSString *imageStatus;
    NSString *hdImageStatus;
    NSString *province;
    NSString *city;
    NSString *sign;
    unsigned long imageKey;
    unsigned long imageKeyLast;
    unsigned long extKey;
    unsigned long extKeyLast;
    unsigned long BottleContactINTRES1;
    unsigned long BottleContactINTRES2;
    unsigned long BottleContactINTRES3;
    NSString *ext;
    NSString *BottleContactTEXTRES2;
    NSString *BottleContactTEXTRES3;
    long long m___rowID;
}

+ (id)dummyObject;
- (void).cxx_destruct;
@property(nonatomic) unsigned long BottleContactINTRES1; // @synthesize BottleContactINTRES1;
@property(nonatomic) unsigned long BottleContactINTRES2; // @synthesize BottleContactINTRES2;
@property(nonatomic) unsigned long BottleContactINTRES3; // @synthesize BottleContactINTRES3;
@property(retain, nonatomic) NSString *BottleContactTEXTRES2; // @synthesize BottleContactTEXTRES2;
@property(retain, nonatomic) NSString *BottleContactTEXTRES3; // @synthesize BottleContactTEXTRES3;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSString *city; // @synthesize city;
- (const WCDBCondition_e9b1f587 *)db_BottleContactINTRES1;
- (const WCDBCondition_e9b1f587 *)db_BottleContactINTRES2;
- (const WCDBCondition_e9b1f587 *)db_BottleContactINTRES3;
- (const WCDBCondition_8be2a476 *)db_BottleContactTEXTRES2;
- (const WCDBCondition_8be2a476 *)db_BottleContactTEXTRES3;
- (const WCDBCondition_8be2a476 *)db_city;
- (const WCDBCondition_8be2a476 *)db_ext;
- (const WCDBCondition_e9b1f587 *)db_extKey;
- (const WCDBCondition_e9b1f587 *)db_extKeyLast;
- (const WCDBCondition_8be2a476 *)db_hdImageStatus;
- (const WCDBCondition_e9b1f587 *)db_imageKey;
- (const WCDBCondition_e9b1f587 *)db_imageKeyLast;
- (const WCDBCondition_8be2a476 *)db_imageStatus;
- (const WCDBCondition_8be2a476 *)db_nickName;
- (const WCDBCondition_8be2a476 *)db_province;
- (const WCDBCondition_e9b1f587 *)db_sex;
- (const WCDBCondition_8be2a476 *)db_sign;
- (const WCDBCondition_8be2a476 *)db_userName;
@property(retain, nonatomic) NSString *ext; // @synthesize ext;
@property(nonatomic) unsigned long extKey; // @synthesize extKey;
@property(nonatomic) unsigned long extKeyLast; // @synthesize extKeyLast;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
@property(retain, nonatomic) NSString *hdImageStatus; // @synthesize hdImageStatus;
@property(nonatomic) unsigned long imageKey; // @synthesize imageKey;
@property(nonatomic) unsigned long imageKeyLast; // @synthesize imageKeyLast;
@property(retain, nonatomic) NSString *imageStatus; // @synthesize imageStatus;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName;
@property(retain, nonatomic) NSString *province; // @synthesize province;
@property(nonatomic) unsigned long sex; // @synthesize sex;
@property(retain, nonatomic) NSString *sign; // @synthesize sign;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

