//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSString;

@interface DBEmoticonDownload : NSObject <WCDBCoding>
{
    NSString *userName;
    NSString *msgServerId;
    unsigned long offset;
    unsigned long status;
    unsigned long createTime;
    unsigned long type;
    NSString *message;
    unsigned long imageStatus;
    NSString *catalog;
    unsigned long catalogId;
    NSString *draft;
    unsigned long messageFlag;
    unsigned long messageFrom;
    unsigned long ConIntRes3;
    NSString *messageSource;
    NSString *ConStrRes2;
    NSString *ConStrRes3;
    long long m___rowID;
}

+ (id)dummyObject;
- (void).cxx_destruct;
@property(nonatomic) unsigned long ConIntRes3; // @synthesize ConIntRes3;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *ConStrRes3; // @synthesize ConStrRes3;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSString *catalog; // @synthesize catalog;
@property(nonatomic) unsigned long catalogId; // @synthesize catalogId;
@property(nonatomic) unsigned long createTime; // @synthesize createTime;
- (const WCDBCondition_e9b1f587 *)db_ConIntRes3;
- (const WCDBCondition_8be2a476 *)db_ConStrRes2;
- (const WCDBCondition_8be2a476 *)db_ConStrRes3;
- (const WCDBCondition_8be2a476 *)db_catalog;
- (const WCDBCondition_e9b1f587 *)db_catalogId;
- (const WCDBCondition_e9b1f587 *)db_createTime;
- (const WCDBCondition_8be2a476 *)db_draft;
- (const WCDBCondition_e9b1f587 *)db_imageStatus;
- (const WCDBCondition_8be2a476 *)db_message;
- (const WCDBCondition_e9b1f587 *)db_messageFlag;
- (const WCDBCondition_e9b1f587 *)db_messageFrom;
- (const WCDBCondition_8be2a476 *)db_messageSource;
- (const WCDBCondition_8be2a476 *)db_msgServerId;
- (const WCDBCondition_e9b1f587 *)db_offset;
- (const WCDBCondition_e9b1f587 *)db_status;
- (const WCDBCondition_e9b1f587 *)db_type;
- (const WCDBCondition_8be2a476 *)db_userName;
@property(retain, nonatomic) NSString *draft; // @synthesize draft;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
@property(nonatomic) unsigned long imageStatus; // @synthesize imageStatus;
@property(retain, nonatomic) NSString *message; // @synthesize message;
@property(nonatomic) unsigned long messageFlag; // @synthesize messageFlag;
@property(nonatomic) unsigned long messageFrom; // @synthesize messageFrom;
@property(retain, nonatomic) NSString *messageSource; // @synthesize messageSource;
@property(retain, nonatomic) NSString *msgServerId; // @synthesize msgServerId;
@property(nonatomic) unsigned long offset; // @synthesize offset;
@property(nonatomic) unsigned long status; // @synthesize status;
@property(nonatomic) unsigned long type; // @synthesize type;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

