//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSArray, NSString, PersonalDesigner, SKProduct, iAPTransation;

@interface EmoticonStoreItem : MMObject <PBCoding>
{
    NSString *productID;
    NSString *iconUrl;
    NSString *packName;
    NSString *packDesc;
    NSString *packAuthInfo;
    NSString *packPrice;
    unsigned int packType;
    unsigned int packFlag;
    NSString *packThumb;
    NSString *coverUrl;
    unsigned int boughtTime;
    NSString *packCopyright;
    NSArray *packThumbList;
    NSArray *packThumbPreviewList;
    NSString *timeLimit;
    unsigned long version;
    NSString *introduce;
    NSString *tagUrl;
    NSString *shareDesc;
    NSString *oldRedirectUrl;
    SKProduct *product;
    BOOL isInvalidProductFromApple;
    iAPTransation *transation;
    NSString *packFileID;
    NSString *packFileKey;
    unsigned int packFileSize;
    NSString *cdnDownloadClientID;
    NSString *cdnDownloadPath;
    unsigned int designerUin;
    NSString *designerName;
    NSString *designerHeaderUrl;
    BOOL _m_isAutomaticDownload;
    PersonalDesigner *personalDesigner;
}

+ (BOOL)IsPrivilegeEmoticonByPid:(id)arg1;
+ (id)StoreItemFromEmotionDetail:(id)arg1;
+ (id)StoreItemFromEmotionSummary:(id)arg1;
+ (id)getItemCachePath:(id)arg1;
+ (id)getItemCacheRootDir;
+ (id)getMd5Pid:(id)arg1;
+ (void)initialize;
+ (id)loadItemFromCache:(id)arg1;
+ (void)megerStoreItem:(id)arg1 FromEmotionSummary:(id)arg2;
+ (void)megerWithOutProduct:(id)arg1 item:(id)arg2;
+ (void)megerWithOutProductForceUpdateTagAndIntroduce:(id)arg1 item:(id)arg2;
- (void).cxx_destruct;
- (id)GetBoughtTimeString;
- (id)GetCoverUrl;
- (id)GetDesc;
- (id)GetIconUrl;
- (id)GetName;
- (id)GetPrice;
- (id)GetServerPrice;
- (id)GetSmallIconUrlList;
- (BOOL)IsFree;
- (BOOL)IsFreeLimited;
- (BOOL)IsStaticPicture;
@property(nonatomic) unsigned int boughtTime; // @synthesize boughtTime;
- (BOOL)canBuy;
- (BOOL)canDownload;
@property(copy, nonatomic) NSString *cdnDownloadClientID; // @synthesize cdnDownloadClientID;
@property(copy, nonatomic) NSString *cdnDownloadPath; // @synthesize cdnDownloadPath;
@property(copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl;
@property(readonly, copy) NSString *description;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (BOOL)hasDetail;
- (BOOL)hasPaid;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl;
@property(retain, nonatomic) NSString *introduce; // @synthesize introduce;
- (BOOL)isCanReport;
- (BOOL)isCanReward;
- (BOOL)isCanShare;
- (BOOL)isEmptyItem;
- (BOOL)isExpired;
@property(nonatomic) BOOL isInvalidProductFromApple; // @synthesize isInvalidProductFromApple;
- (BOOL)isSameAs:(id)arg1;
- (BOOL)isValid;
@property(nonatomic) BOOL m_isAutomaticDownload; // @synthesize m_isAutomaticDownload=_m_isAutomaticDownload;
@property(retain, nonatomic) NSString *oldRedirectUrl; // @synthesize oldRedirectUrl;
@property(copy, nonatomic) NSString *packAuthInfo; // @synthesize packAuthInfo;
@property(copy, nonatomic) NSString *packCopyright; // @synthesize packCopyright;
@property(copy, nonatomic) NSString *packDesc; // @synthesize packDesc;
@property(copy, nonatomic) NSString *packFileID; // @synthesize packFileID;
@property(copy, nonatomic) NSString *packFileKey; // @synthesize packFileKey;
@property(nonatomic) unsigned int packFileSize; // @synthesize packFileSize;
@property(nonatomic) unsigned int packFlag; // @synthesize packFlag;
@property(copy, nonatomic) NSString *packName; // @synthesize packName;
@property(copy, nonatomic) NSString *packPrice; // @synthesize packPrice;
@property(copy, nonatomic) NSString *packThumb; // @synthesize packThumb;
@property(retain, nonatomic) NSArray *packThumbList; // @synthesize packThumbList;
@property(retain, nonatomic) NSArray *packThumbPreviewList; // @synthesize packThumbPreviewList;
@property(nonatomic) unsigned int packType; // @synthesize packType;
@property(retain, nonatomic) PersonalDesigner *personalDesigner; // @synthesize personalDesigner;
- (id)priceStringForProduct:(id)arg1;
@property(retain, nonatomic) SKProduct *product; // @synthesize product;
@property(copy, nonatomic) NSString *productID; // @synthesize productID;
- (void)saveItemToCache;
@property(retain, nonatomic) NSString *shareDesc; // @synthesize shareDesc;
@property(retain, nonatomic) NSString *tagUrl; // @synthesize tagUrl;
@property(retain, nonatomic) NSString *timeLimit; // @synthesize timeLimit;
@property(retain, nonatomic) iAPTransation *transation; // @synthesize transation;
@property(nonatomic) unsigned long version; // @synthesize version;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

