//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableArray;

@interface EmoticonCustomManageDataLogic : MMObject
{
    NSMutableArray *m_wrapArray;
    int m_mode;
    id <EmoticonCustomManageDataLogicDelegate> m_delegate;
}

+ (id)sortEmoticon:(id)arg1;
- (void).cxx_destruct;
- (id)arrayForMarkDelete;
- (id)arrayForRow:(unsigned int)arg1;
- (void)changeToDeleteMode;
- (void)changeToNormalMode;
- (void)changeToRecoveringMode;
- (unsigned int)columnCount;
- (void)dealloc;
- (id)init;
@property(nonatomic) __weak id <EmoticonCustomManageDataLogicDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) int m_mode; // @synthesize m_mode;
@property(retain, nonatomic) NSMutableArray *m_wrapArray; // @synthesize m_wrapArray;
- (id)reloadDataWithType:(int)arg1;
- (unsigned int)rowCount;
- (void)setDelegate:(id)arg1;
- (unsigned int)totalEmoticonCountIncludeRecoverFailed;

@end

