//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EmoticonDownloadProxy.h"

#import "EmoticonDownloadProxyDelegate.h"

@class NSString;

@interface EmoticonHybridDownloadProxy : EmoticonDownloadProxy <EmoticonDownloadProxyDelegate>
{
    NSString *m_md5;
    NSString *m_cdnUrlString;
    NSString *m_encryptUrlString;
    NSString *m_aesKey;
    id <EmoticonDownloadProxyDelegate> m_delegate;
    EmoticonDownloadProxy *m_downloadProxy;
    BOOL m_needTryCgi;
    BOOL m_tryCgiWhenCdnDownloadFailed;
    NSString *_m_serverId;
}

+ (BOOL)tryCgiWhenCdnDownloadFailedDefaultConfig;
- (void).cxx_destruct;
- (void)clearDelegate;
- (id)createCdnDownloadConnection;
- (id)createDownloadCgiProxy;
- (id)createMd5DownloadProxy;
- (id)initWithMd5:(id)arg1 delegate:(id)arg2;
- (id)initWithMd5:(id)arg1 withCdnUrl:(id)arg2 AndEncryptUrl:(id)arg3 withAesKey:(id)arg4 delegate:(id)arg5;
- (id)initWithMd5:(id)arg1 withCdnUrl:(id)arg2 delegate:(id)arg3;
- (BOOL)isActive;
@property(retain, nonatomic) NSString *m_serverId; // @synthesize m_serverId=_m_serverId;
@property(nonatomic) BOOL m_tryCgiWhenCdnDownloadFailed; // @synthesize m_tryCgiWhenCdnDownloadFailed;
- (void)onEmoticonDownloadMd5Failed:(id)arg1;
- (void)onEmoticonDownloadMd5Failed:(id)arg1 withUserInfo:(id)arg2;
- (void)onEmoticonDownloadMd5Ok:(id)arg1 AndFilePath:(id)arg2;
- (void)onEmoticonDownloadMd5Ok:(id)arg1 AndFilePath:(id)arg2 withUserInfo:(id)arg3;
- (void)startRequest;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

