//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IEnterpriseGroupMgrExt.h"
#import "IEnterpriseSessionMgrExt.h"
#import "IMMNewSessionMgrExt.h"
#import "MMWebViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CContact, MMScrollView, MMTableView, MMTitleView, NSMutableArray, NSString, UIView;

@interface EnterpriseSessionListViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, IEnterpriseSessionMgrExt, IEnterpriseGroupMgrExt, IMMNewSessionMgrExt, MMWebViewDelegate>
{
    unsigned long _scene;
    unsigned long _fromScene;
    MMTableView *_tableView;
    MMScrollView *_emptyView;
    MMTitleView *_titleView;
    UIView *_footerView;
    UIView *_footerViewBackground;
    NSMutableArray *_arySpecialSession;
    float preContentOffsetY;
    CContact *brandContact;
}

- (void).cxx_destruct;
- (id)brandCellDataWithMainUsrName:(id)arg1;
@property(retain, nonatomic) CContact *brandContact; // @synthesize brandContact;
- (void)createChatroom:(id)arg1;
- (void)createSingleChat:(id)arg1;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)enterChat:(id)arg1;
- (void)hideSpecialSession;
- (void)initData;
- (void)initEmptyView;
- (void)initFooterView;
- (id)initWithBrand:(id)arg1 fromScene:(unsigned long)arg2;
- (BOOL)isSpecialIndex:(id)arg1;
- (id)makeNormalCell:(id)arg1;
- (id)makeSpecialCell:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onCreateEnterpriseGroup:(id)arg1 errorCode:(int)arg2 extDic:(id)arg3;
- (void)onEnterpriseSessionChanged;
- (void)onQuitEnterpriseGroup:(id)arg1 errorCode:(int)arg2;
- (void)onSessionTotalUnreadCountChange:(unsigned long)arg1;
- (void)onWebViewWillClose:(id)arg1;
- (void)openChatBrandInfo:(id)arg1;
- (void)openCreateChat:(id)arg1;
- (void)openEnterpriseBrandSessionListView;
- (void)openFavSessionListView:(id)arg1;
- (void)report;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)setScene:(unsigned long)arg1;
- (void)showRightTopMenuBtn:(id)arg1;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)updateEmptyView;
- (void)updateLeftBarItem;
- (void)updateMemberToLocal:(id)arg1;
- (void)updateTitleView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillBePoped:(BOOL)arg1;
- (void)viewWillBePushed:(BOOL)arg1;
- (void)willAppear;
- (void)willDisappear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

