//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface EnterpriseRoomData : MMObject <PBCoding>
{
    NSMutableArray *m_aryMemberList;
    unsigned long m_uiMaxMemberCount;
    NSString *m_nsOwner;
}

+ (void)initialize;
- (void).cxx_destruct;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSMutableArray *m_aryMemberList; // @synthesize m_aryMemberList;
@property(retain, nonatomic) NSString *m_nsOwner; // @synthesize m_nsOwner;
@property(nonatomic) unsigned long m_uiMaxMemberCount; // @synthesize m_uiMaxMemberCount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

