//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UIView;

@interface EnterpriseSessionControllerMenuView : UIButton
{
    UIImageView *m_viewBg;
    UIView *m_viewContent;
}

- (void).cxx_destruct;
- (void)addItemWithTitle:(id)arg1 imageName:(id)arg2 sel:(SEL)arg3 target:(id)arg4;
- (void)addLine;
- (void)animateHideAction;
- (void)animateShowInView:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)dealloc;
- (id)init;
- (void)layoutSubviews;
- (void)onHideAction;
- (void)updateSubviewWidth;

@end

