//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class AttributeLabel, FTSMsgItem, MMHeadImageView, MMUILabel, NSArray, NSString;

@interface FTSMsgCell : MMTableViewCell
{
    FTSMsgItem *_msgItem;
    unsigned int _mergeCount;
    NSString *_searchText;
    NSArray *_arrKeyword;
    MMHeadImageView *_headImageView;
    AttributeLabel *_displayNameLabel;
    AttributeLabel *_detailLabel;
    MMUILabel *_timeLabel;
    MMUILabel *_prefixDetailLabel;
    BOOL _hiddenMode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *arrKeyword; // @synthesize arrKeyword=_arrKeyword;
@property(nonatomic) BOOL hiddenMode; // @synthesize hiddenMode=_hiddenMode;
- (void)initView;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 hiddenMode:(BOOL)arg3;
- (BOOL)isTrailSurrogates:(unsigned short)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void)updateMsgItem:(id)arg1 searchText:(id)arg2 keywords:(id)arg3 mergeCount:(unsigned int)arg4;
- (void)updateStatus:(BOOL)arg1;

@end

