//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GameCenterMsgDbModel, WCDataBase, WCDataBaseTable;

@interface GameCenterMsgDb : NSObject
{
    GameCenterMsgDbModel *dummyObj;
    WCDataBase *_db;
    WCDataBaseTable *_table;
}

- (void).cxx_destruct;
- (struct WCDBConditionBase)buildWhereCondition:(int)arg1 lastLocalId:(int)arg2 onlyUnRead:(BOOL)arg3 maxCount:(int)arg4;
- (void)closeDbBeforeInit;
- (BOOL)createTable;
@property(retain, nonatomic) WCDataBase *db; // @synthesize db=_db;
- (BOOL)deleteAllMsg;
- (BOOL)deleteMsgBeforeTimeStamp:(unsigned long)arg1;
- (BOOL)deleteMsgByLocalId:(int)arg1;
- (id)getAllMsg;
- (id)getDbPath;
- (id)getMsgByLocalId:(int)arg1;
- (id)getMsgListByPage:(int)arg1 lastLocalId:(int)arg2 maxCount:(int)arg3;
- (id)getMsgListByPageForJsApi:(int)arg1 lastLocalId:(int)arg2 onlyUnRead:(BOOL)arg3 maxCount:(int)arg4;
- (BOOL)initDb;
- (BOOL)isMsgExistBySvrMsgId:(id)arg1;
- (unsigned long)saveMsg:(id)arg1;
- (BOOL)setMsgCenterAllRead;
@property(retain, nonatomic) WCDataBaseTable *table; // @synthesize table=_table;

@end

