//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class GameCenterGameBriefInfo, MMWebImageView, NSArray, UIButton, UIImageView, UILabel;

@interface GameCenterGameInfoCell : MMTableViewCell
{
    MMWebImageView *_iconView;
    UILabel *_nameLabel;
    UILabel *_descLabel;
    UILabel *_remarkLabel;
    UIImageView *_trendIconView;
    UIButton *_downloadButton;
    UILabel *_buttonCommentLabel;
    unsigned int _type;
    NSArray *_trendIconNameMap;
    id <GameCenterGameInfoCellDelegate> _delegate;
    GameCenterGameBriefInfo *_gameInfo;
    unsigned int _actionStyle;
    int _index;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int actionStyle; // @synthesize actionStyle=_actionStyle;
- (void)dealloc;
@property(nonatomic) __weak id <GameCenterGameInfoCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GameCenterGameBriefInfo *gameInfo; // @synthesize gameInfo=_gameInfo;
@property(nonatomic) int index; // @synthesize index=_index;
- (void)initSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 type:(unsigned int)arg3;
- (void)layoutContent;
- (void)layoutSubviews;
- (void)onDownloadButtonClicked:(id)arg1;
- (void)reloadData;
- (void)setButtonCommentText:(id)arg1;
- (void)setButtonTitle:(id)arg1;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, retain, nonatomic) NSArray *trendIconNameMap; // @synthesize trendIconNameMap=_trendIconNameMap;

@end

