//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IGameCenterExt.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FMSearchBar, GameSearchRecommendList, NSMutableArray, NSString, UISearchDisplayController, UITableView;

@interface GameCenterSearchLogicController : MMObject <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate, IGameCenterExt>
{
    BOOL _isHeaderView;
    NSMutableArray *_resultGroupList;
    UISearchDisplayController *_searchDisplayController;
    UITableView *_recommendTableView;
    unsigned long _searchScene;
    GameSearchRecommendList *_smartBoxData;
    GameSearchRecommendList *_rcmData;
    int _resultType;
    int _sourceScene;
    BOOL _isNoResult;
    FMSearchBar *_searchBar;
    id <GameCenterSearchLogicControllerDelegate> _delegate;
    NSString *_searchKeyword;
    int _returnKeyType;
    NSString *_searchPlaceholder;
}

- (void).cxx_destruct;
- (void)adjustDimmingView:(id)arg1;
- (void)cancelSearch;
- (id)cellForSearchResult:(id)arg1 IndexPath:(id)arg2;
- (id)cellForSmartBox:(id)arg1 IndexPath:(id)arg2;
- (id)cellForSmartBoxResult:(id)arg1 IndexPath:(id)arg2;
- (void)dealloc;
@property(nonatomic) __weak id <GameCenterSearchLogicControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finishSearch;
- (int)handleSearchGameResultItem:(id)arg1 searchWord:(id)arg2 sourceScene:(int)arg3;
- (void)handleSearchWebResultItem:(id)arg1;
- (void)handleShowMore:(id)arg1;
- (void)hideDimmingView:(id)arg1;
- (id)initWithContentsController:(id)arg1 isHeaderView:(BOOL)arg2 sourceScene:(int)arg3;
@property(nonatomic) BOOL isNoResult; // @synthesize isNoResult=_isNoResult;
- (void)keyboardWillShow;
- (void)loadSubviewsForSearchCell:(id)arg1 gameResultItem:(id)arg2 separatorX:(float)arg3;
- (void)loadSubviewsForSearchCell:(id)arg1 resultTips:(id)arg2;
- (void)loadSubviewsForSearchCell:(id)arg1 separatorColor:(id)arg2;
- (void)loadSubviewsForSearchCell:(id)arg1 showMore:(id)arg2;
- (void)loadSubviewsForSearchCell:(id)arg1 similarResultItem:(id)arg2 separatorX:(float)arg3;
- (void)loadSubviewsForSearchCell:(id)arg1 webResultItem:(id)arg2 separatorX:(float)arg3;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onClassifyBtnClicked:(id)arg1;
- (void)onGameSearchFinishedWithResultGroups:(id)arg1 searchWithText:(id)arg2 error:(int)arg3;
- (void)onGameSearchSmartBox:(id)arg1 recommendList:(id)arg2 error:(int)arg3;
- (void)onOpenSearchGameResultItem:(id)arg1 searchWord:(id)arg2 sourceScene:(int)arg3;
- (void)onOpenSearchWebResultItem:(id)arg1;
- (void)popupSearchBar;
- (void)relayoutSearchBar:(id)arg1;
- (void)relayoutSubviews;
- (void)removeNoResultLabelWhenSearching;
- (void)resetRecommendGamesAndShowRecommendTableView;
@property(nonatomic) int returnKeyType; // @synthesize returnKeyType=_returnKeyType;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) FMSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarBecomeFirstResponder;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarDidEndSearch;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (BOOL)searchBarShouldBeginEditing:(id)arg1;
- (BOOL)searchBarShouldEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchDisplayController:(id)arg1 didShowSearchResultsTableView:(id)arg2;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
@property(retain, nonatomic) NSString *searchKeyword; // @synthesize searchKeyword=_searchKeyword;
@property(retain, nonatomic) NSString *searchPlaceholder; // @synthesize searchPlaceholder=_searchPlaceholder;
- (id)sessionHeaderViewForSearchResult:(id)arg1;
- (id)sessionHeaderViewForSmartBox:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

