//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GameCenterMsgAppInfo, GameCenterMsgBubbleInfo, GameCenterMsgCenterContent, GameCenterMsgControlInfo, GameCenterMsgUserInfo, GameCenterNotifyContent, NSString;

@interface GameCenterBaseMsg : NSObject
{
    BOOL _wifiFlag;
    BOOL _showInMsgCenter;
    unsigned long _localId;
    NSString *_svrMsgId;
    NSString *_noticeId;
    int _type;
    GameCenterMsgControlInfo *_controlInfo;
    NSString *_formatContent;
    NSString *_url;
    GameCenterMsgUserInfo *_userInfo;
    GameCenterMsgAppInfo *_appInfo;
    int _badgeType;
    NSString *_entranceIconUrl;
    NSString *_entranceText;
    GameCenterMsgBubbleInfo *_bubbleInfo;
    NSString *_originMsg;
    GameCenterNotifyContent *_notifyContent;
    GameCenterMsgCenterContent *_msgCenterContent;
}

+ (struct XmlReaderNode_t *)getRootNode:(id)arg1;
+ (id)msgWithType:(unsigned long)arg1 xmlNode:(struct XmlReaderNode_t *)arg2;
+ (id)parseFromDbItem:(id)arg1;
+ (id)parseFromMsgWrap:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) GameCenterMsgAppInfo *appInfo; // @synthesize appInfo=_appInfo;
@property(nonatomic) int badgeType; // @synthesize badgeType=_badgeType;
@property(retain, nonatomic) GameCenterMsgBubbleInfo *bubbleInfo; // @synthesize bubbleInfo=_bubbleInfo;
@property(retain, nonatomic) GameCenterMsgControlInfo *controlInfo; // @synthesize controlInfo=_controlInfo;
@property(retain, nonatomic) NSString *entranceIconUrl; // @synthesize entranceIconUrl=_entranceIconUrl;
@property(retain, nonatomic) NSString *entranceText; // @synthesize entranceText=_entranceText;
@property(retain, nonatomic) NSString *formatContent; // @synthesize formatContent=_formatContent;
- (id)getMsgCenterContent;
- (id)getNotifyContent;
- (id)initWithXmlNode:(struct XmlReaderNode_t *)arg1;
- (BOOL)isExpired;
@property(nonatomic) unsigned long localId; // @synthesize localId=_localId;
@property(retain, nonatomic) GameCenterMsgCenterContent *msgCenterContent; // @synthesize msgCenterContent=_msgCenterContent;
@property(retain, nonatomic) NSString *noticeId; // @synthesize noticeId=_noticeId;
@property(retain, nonatomic) GameCenterNotifyContent *notifyContent; // @synthesize notifyContent=_notifyContent;
@property(retain, nonatomic) NSString *originMsg; // @synthesize originMsg=_originMsg;
@property(nonatomic) BOOL showInMsgCenter; // @synthesize showInMsgCenter=_showInMsgCenter;
@property(retain, nonatomic) NSString *svrMsgId; // @synthesize svrMsgId=_svrMsgId;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) GameCenterMsgUserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) BOOL wifiFlag; // @synthesize wifiFlag=_wifiFlag;

@end

