//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface GoogleContact : NSObject <PBCoding>
{
    BOOL isInMyContactList;
    BOOL isOnlyInOtherContact;
    NSString *googleId;
    NSString *nickName;
    NSString *gmail;
    unsigned long sex;
    NSString *wxUsrname;
    NSString *wxNickname;
    NSString *headImgUrl;
    NSString *headHDImgUrl;
    NSString *googleImageUrl;
    NSMutableArray *emailList;
    NSString *m_nsAntispamTicket;
}

+ (void)initialize;
- (void).cxx_destruct;
- (int)compareGoogleContactsAscending:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSMutableArray *emailList; // @synthesize emailList;
- (id)getDisplayContactDataFromGContactAndDB;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *gmail; // @synthesize gmail;
@property(retain, nonatomic) NSString *googleId; // @synthesize googleId;
@property(retain, nonatomic) NSString *googleImageUrl; // @synthesize googleImageUrl;
@property(retain, nonatomic) NSString *headHDImgUrl; // @synthesize headHDImgUrl;
@property(retain, nonatomic) NSString *headImgUrl; // @synthesize headImgUrl;
- (id)init;
@property(nonatomic) BOOL isInMyContactList; // @synthesize isInMyContactList;
@property(nonatomic) BOOL isOnlyInOtherContact; // @synthesize isOnlyInOtherContact;
@property(retain, nonatomic) NSString *m_nsAntispamTicket; // @synthesize m_nsAntispamTicket;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName;
@property(nonatomic) unsigned long sex; // @synthesize sex;
@property(retain, nonatomic) NSString *wxNickname; // @synthesize wxNickname;
@property(retain, nonatomic) NSString *wxUsrname; // @synthesize wxUsrname;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

