//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIScrollView.h"

#import "MMImageScrollViewHelperDelegate.h"
#import "UIScrollViewDelegate.h"

@class MMImageScrollViewHelper, NSArray, NSString, UIActivityIndicatorView, UIImageView;

@interface ImageScrollView : MMUIScrollView <UIScrollViewDelegate, MMImageScrollViewHelperDelegate>
{
    UIImageView *imageView;
    UIActivityIndicatorView *mActivityIndicator;
    MMImageScrollViewHelper *m_scrollViewHelper;
    BOOL m_bIsLongPressHandled;
    BOOL isLoaded;
    id <ImageScrollViewDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)LongPressBegin;
- (void)LongPressEvents;
- (void)dealloc;
- (void)displayImage:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)displayImage:(id)arg1 withFrame:(struct CGRect)arg2 FullScreen:(BOOL)arg3;
- (void)displayImage:(id)arg1 withFrame:(struct CGRect)arg2 FullScreen:(BOOL)arg3 CornerRadius:(float)arg4;
- (id)getImage;
- (id)getImageView;
- (id)getScrollView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) BOOL isLoaded; // @synthesize isLoaded;
@property __weak id <ImageScrollViewDelegate> m_delegate; // @synthesize m_delegate;
- (void)onDoubleTap:(id)arg1;
- (void)pressedEvents;
- (void)reloadView:(id)arg1 FullScreen:(BOOL)arg2;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateImage:(id)arg1;
- (id)viewForZooming;
- (id)viewForZoomingInScrollView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) struct CGRect frame;
@property(copy, nonatomic) NSArray *gestureRecognizers;
@property(readonly) unsigned int hash;
@property(nonatomic) float maximumZoomScale;
@property(nonatomic) float minimumZoomScale;
@property(readonly) Class superclass;
@property(nonatomic) float zoomScale;

@end

