//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIButton.h"

@class NSString, UIActivityIndicatorView, UIImage, UILabel;

@interface MMDeviceControlButton : MMUIButton
{
    BOOL _roundedBorder;
    UIImage *_originImage;
    UILabel *_controlTitleLabel;
    UIActivityIndicatorView *_loadingIndicator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *controlTitle;
@property(retain, nonatomic) UILabel *controlTitleLabel; // @synthesize controlTitleLabel=_controlTitleLabel;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) UIImage *originImage; // @synthesize originImage=_originImage;
@property(nonatomic) BOOL roundedBorder; // @synthesize roundedBorder=_roundedBorder;
- (void)setImage:(id)arg1 forState:(unsigned int)arg2;
- (void)startLoadingAnimation;
- (void)stopLoadingAnimation;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

