//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMExtensionFileUtil : NSObject
{
}

+ (BOOL)addMessageFailPostSessionDataToFile:(id)arg1 WithSessionID:(id)arg2 withTaskID:(unsigned int)arg3;
+ (void)clearAllExtFavImgTaskFiles;
+ (void)clearAllExtFavUrlTaskFiles;
+ (void)clearAllExtFavVideoTaskFiles;
+ (BOOL)clearPostCacheWithSessionID:(id)arg1;
+ (id)getAllExtFavImgTaskFiles;
+ (id)getAllExtFavUrlTaskFiles;
+ (id)getAllExtFavVideoTaskFiles;
+ (id)getAllExtWCUploadFailTaskFiles;
+ (id)getAllMessageFailSessionFile;
+ (id)getExtWCUploadTaskWithSessionID:(id)arg1 andTaskID:(unsigned int)arg2;
+ (id)getMessagePostMetaDataFilePathWithClientID:(id)arg1;
+ (id)getMessagePostTaskIdDataFailePathWithSessionID:(id)arg1 andTaskID:(id)arg2;
+ (id)getWCUploadTaskWithTaskFilePath:(id)arg1;
+ (BOOL)removeMessagePostMetaDataFilePathWithClientID:(id)arg1;
+ (BOOL)removeMessagePostTaskIdDataWithSessionID:(id)arg1 withTaskID:(unsigned int)arg2;
+ (BOOL)removeTimelineUploadTaskFileWithSessionID:(id)arg1 withTaskID:(unsigned int)arg2;

@end

