//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMGridViewLayoutStrategyBase.h"

#import "MMGridViewLayoutStrategy.h"

@class NSString;

@interface MMGridViewLayoutVerticalStrategy : MMGridViewLayoutStrategyBase <MMGridViewLayoutStrategy>
{
    int _numberOfItemsPerRow;
}

+ (BOOL)requiresEnablingPaging;
- (id)init;
- (int)itemPositionFromLocation:(struct CGPoint)arg1;
@property(readonly, nonatomic) int numberOfItemsPerRow; // @synthesize numberOfItemsPerRow=_numberOfItemsPerRow;
- (struct CGPoint)originForItemAtPosition:(int)arg1;
- (struct _NSRange)rangeOfPositionsInBoundsFromOffset:(struct CGPoint)arg1;
- (void)rebaseWithItemCount:(int)arg1 insideOfBounds:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

