//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMLandscapeInputToolView, NSString, UIImage;

@protocol MMLandscapeInputToolViewDelegate <NSObject>

@optional
- (void)SendTextMessageToolView:(NSString *)arg1;
- (void)TextDidChanged:(NSString *)arg1 selectedRange:(struct _NSRange)arg2;
- (void)ToolViewPositionDidChanged:(BOOL)arg1 animated:(BOOL)arg2;
- (void)afterLandscapeToolViewHeightUpdate:(MMLandscapeInputToolView *)arg1;
- (void)beforeLandscapeToolViewHeightUpdate:(MMLandscapeInputToolView *)arg1;
- (void)pasteImage:(UIImage *)arg1;
- (void)updateToolViewAnimationCurve:(int)arg1;
- (void)updateToolViewAnimationDuration:(float)arg1;
@end

