//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IRemoteControlMusicPlayerExt.h"
#import "MMAudioDataWriteStreamDelegate.h"
#import "MMMusicPlayerNotifyExt.h"
#import "MMService.h"
#import "NSURLConnectionDelegate.h"
#import "WCAudioSessionExt.h"

@class MMAudioDataPipe, MMAudioStreamPlayer, MMMusicInfo, MMTimer, NSObject, NSRecursiveLock, NSString, NSURLConnection;

@interface MMMusicPlayer : MMService <MMMusicPlayerNotifyExt, WCAudioSessionExt, IRemoteControlMusicPlayerExt, MMService, NSURLConnectionDelegate, MMAudioDataWriteStreamDelegate>
{
    MMAudioStreamPlayer *m_audioPlayer;
    MMAudioDataPipe *m_dataPipe;
    BOOL m_isLocalPlay;
    BOOL m_isQQMusicWifiPlay;
    BOOL m_isCyclePlay;
    BOOL m_isNeedRestartByOthers;
    MMMusicInfo *m_musicInfo;
    MMTimer *m_levelTimer;
    NSRecursiveLock *m_oLock;
    unsigned int _curStreamSeekOffset;
    BOOL _bIsSeekToNewOffset;
    NSObject *m_clientInfo;
    NSString *m_title;
    NSString *m_photoUrl;
    NSURLConnection *m_dlConn;
    NSString *m_url;
}

- (void).cxx_destruct;
- (void)TimerCheckMeter;
- (void)addMusicItem:(id)arg1;
- (id)bcdStringFromUrl_QQMusic:(id)arg1;
- (id)bcdStringFromUrl_WechatMusicUrl:(id)arg1;
- (id)cachePathForMusicFromUrl:(id)arg1;
- (id)cacheRootPath;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
- (void)destroyStreamer;
- (id)downloadTempPathForMusicFromUrl:(id)arg1;
- (void)forceStopMusic;
- (id)getUrlPathExt:(id)arg1;
- (id)hashForUrl:(id)arg1;
- (void)ignoreCurrentMusicItem;
- (id)init;
- (BOOL)isIdle;
- (BOOL)isNeedRestartByOthers;
- (BOOL)isPaused;
- (BOOL)isPlaying;
- (BOOL)isWaiting;
@property(retain, nonatomic) NSObject *m_clientInfo; // @synthesize m_clientInfo;
@property(retain, nonatomic) NSURLConnection *m_dlConn; // @synthesize m_dlConn;
@property(retain, nonatomic) MMMusicInfo *m_musicInfo; // @synthesize m_musicInfo;
@property(retain, nonatomic) NSString *m_photoUrl; // @synthesize m_photoUrl;
@property(retain, nonatomic) NSString *m_title; // @synthesize m_title;
@property(retain, nonatomic) NSString *m_url; // @synthesize m_url;
- (void)notifyMusicPlayerPauseMusic;
- (void)notifyMusicPlayerRestartMusic;
- (void)onHandleWriteEventfromStream:(id)arg1 eventType:(unsigned long)arg2;
- (void)onHandleWriteSeekToNewStreamOffset:(int)arg1 andSeekTime:(double)arg2;
- (void)onPlayNextMusic;
- (void)onPlayPreviousMusic;
- (void)onServiceInit;
- (void)onSetNeedRestartMusicByOthers:(BOOL)arg1;
- (void)onWCAudioSessionCategoryChange:(unsigned int)arg1;
- (void)onWCAudioSessionNewDeviceAvailable;
- (void)onWCAudioSessionOldDeviceUnavailable;
- (void)onWCAudioSessionOverride;
- (void)pause;
- (void)playWithUrl:(id)arg1 MusicID:(id)arg2;
- (void)playbackStateChanged:(id)arg1;
- (void)reportDownloadFailed;
- (void)reportDownloadStart;
- (void)seekToTime:(double)arg1;
- (void)setNeedRestartByOthers:(BOOL)arg1;
- (void)start;
- (void)startDownloadMusicFromUrl:(id)arg1;
- (int)status;
- (void)stop;
- (void)stopcycle;
- (void)tryStopClientId:(id)arg1;
- (unsigned int)tryToGetDownloadPercent;
- (double)tryToGetDuaration;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

