//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactSelectViewDelegate.h"
#import "GroupSelectContactsViewControllerDelegate.h"
#import "MMSearchBarDelegate.h"
#import "NewContactsSearchPanelViewDelegate.h"
#import "SelectTagContactsViewControllerDelegate.h"
#import "TipsViewDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "WCActionSheetDelegate.h"

@class ContactSelectView, NSDictionary, NSIndexPath, NSMutableDictionary, NSString, NewContactsSearchPanelView, TipsView, UIBarButtonItem, UIButton, UIView;

@interface MultiSelectContactsViewController : MMUIViewController <SelectTagContactsViewControllerDelegate, ContactSelectViewDelegate, UISearchDisplayDelegate, MMSearchBarDelegate, WCActionSheetDelegate, NewContactsSearchPanelViewDelegate, GroupSelectContactsViewControllerDelegate, TipsViewDelegate>
{
    id <MultiSelectContactsViewControllerDelegate> m_delegate;
    NSDictionary *m_dicExistContact;
    NSDictionary *m_dicIgnoreContact;
    BOOL m_bShowHistoryGroup;
    BOOL m_bShowRadarCreateRoom;
    BOOL m_bShowBrandContact;
    NSMutableDictionary *m_dicMultiSelect;
    NSIndexPath *m_indexPathToBeDeleted;
    NewContactsSearchPanelView *m_panelView;
    UIButton *m_panelBtn;
    UIBarButtonItem *m_panelBtnItem;
    unsigned long m_uiGroupScene;
    unsigned int m_memberCountLimit;
    NSString *m_showTip;
    TipsView *m_tipView;
    BOOL m_tempForbidLayout;
    ContactSelectView *m_selectView;
    int m_commonSearchScene;
    UIView *_tableFooterView;
    NSString *nsCurrentSearchText;
    BOOL _m_bKeepCurViewAfterSelect;
}

- (void).cxx_destruct;
- (void)UpdateForChatGroup:(id)arg1;
- (void)cancelSearch;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (void)dealloc;
- (void)didClickImageAtIndex:(unsigned long)arg1 withKey:(id)arg2;
- (void)didDeleteLastWithKey:(id)arg1;
- (void)didSearchViewTableSelect:(id)arg1;
- (void)doSearch:(id)arg1 Pre:(BOOL)arg2;
- (void)doTagSearch:(id)arg1 arrContacts:(id)arg2;
- (unsigned int)getTotalSelectCount;
- (float)heightForSearchViewTable:(id)arg1;
- (id)init;
- (void)initTitleArea;
- (void)initView;
- (BOOL)isExisted:(id)arg1;
- (BOOL)isIgnore:(id)arg1;
@property(nonatomic) BOOL m_bKeepCurViewAfterSelect; // @synthesize m_bKeepCurViewAfterSelect=_m_bKeepCurViewAfterSelect;
@property(nonatomic) BOOL m_bShowBrandContact; // @synthesize m_bShowBrandContact;
@property(nonatomic) BOOL m_bShowHistoryGroup; // @synthesize m_bShowHistoryGroup;
@property(nonatomic) BOOL m_bShowRadarCreateRoom; // @synthesize m_bShowRadarCreateRoom;
@property(nonatomic) int m_commonSearchScene; // @synthesize m_commonSearchScene;
@property(nonatomic) __weak id <MultiSelectContactsViewControllerDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSDictionary *m_dicExistContact; // @synthesize m_dicExistContact;
@property(retain, nonatomic) NSDictionary *m_dicIgnoreContact; // @synthesize m_dicIgnoreContact;
@property(retain, nonatomic) NSMutableDictionary *m_dicMultiSelect; // @synthesize m_dicMultiSelect;
@property(nonatomic) unsigned int m_memberCountLimit; // @synthesize m_memberCountLimit;
@property(retain, nonatomic) UIButton *m_panelBtn; // @synthesize m_panelBtn;
@property(retain, nonatomic) UIBarButtonItem *m_panelBtnItem; // @synthesize m_panelBtnItem;
@property(retain, nonatomic) NSString *m_showTip; // @synthesize m_showTip;
@property(nonatomic) unsigned long m_uiGroupScene; // @synthesize m_uiGroupScene;
- (id)makeFiterContactToTagSearchView:(id)arg1;
- (void)onCancel:(id)arg1;
- (void)onContactSelectSearch:(id)arg1;
- (void)onDone:(id)arg1;
- (BOOL)onFilterContactCandidate:(id)arg1;
- (void)onGroupMultiSelectContactReturn:(id)arg1;
- (void)onGroupSelectContactReturn:(id)arg1;
- (void)onSelectContact:(id)arg1;
- (void)onSelectDoneWithContacts:(id)arg1;
- (void)onSelectHistoryGroup;
- (void)onSelectRadarCreateRoom;
- (BOOL)onShouldSelectContact:(id)arg1;
- (void)onTipsViewClick:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)searchTextFieldDidBeginEditing;
- (void)tryShowSelectTip:(unsigned int)arg1 currentSelectCount:(unsigned int)arg2;
- (void)updatePanelBtn;
- (void)updatePanelView:(id)arg1;
- (void)updateSelectedHeadImgView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

