//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIImagePickerController.h"

#import "PickedImagePaneDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSDictionary, NSString, PickedImagePane;

@interface MultiImagePickerController : MMUIImagePickerController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, PickedImagePaneDelegate>
{
    id <MultiImagePickerControllerDelegate> _mpdelegate;
    PickedImagePane *_imagePane;
    unsigned long _maxSelectNum;
    NSDictionary *_imageInfo;
    BOOL _isStatusbarHidden;
}

- (void).cxx_destruct;
- (void)MultiImagePickerPreviewViewFinishSelectingImages:(id)arg1;
@property(nonatomic) unsigned long _maxSelectNum; // @synthesize _maxSelectNum;
@property(nonatomic) __weak id <MultiImagePickerControllerDelegate> _mpdelegate; // @synthesize _mpdelegate;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (id)init;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)pickedImagePaneDidFinishPickingImages:(id)arg1;
- (void)removeImages;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

