//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface NavigateItem : MMObject
{
    CDStruct_2c43369c _coordinate;
    NSString *_name;
}

- (void).cxx_destruct;
@property(nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate=_coordinate;
- (void)dealloc;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;

@end

