//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class CContact, MMCPLabel, MMMaskHeadImageView, NSString, UIButton, UIColor, UIImageView;

@interface NewChatRoomMemberItemView : MMUIView
{
    UIButton *m_viewMemberBtn;
    UIButton *m_addMemberBtn;
    UIButton *m_deleteMemberBtn;
    UIButton *m_actionBtn;
    MMMaskHeadImageView *m_headImageView;
    MMCPLabel *m_labelDisplayName;
    UIImageView *m_trackIcon;
    UIImageView *m_talkIcon;
    UIImageView *m_ownerIcon;
    UIButton *m_smallDeleteBtn;
    CContact *m_contact;
    CContact *m_groupContact;
    id <NewChatRoomMemberItemViewDelegate> m_delegate;
    SEL m_updateItemViewForDeleteSel;
    BOOL m_bDeleteStatus;
    unsigned long m_uiIndex;
    UIColor *m_textColor;
    float m_fLeftMargin;
    float m_fRightMargin;
    BOOL m_noDisplayName;
    NSString *m_cpKeyForNickname;
    NSString *m_cpKeyForChatRoomDisplayName;
    BOOL m_isNickNameUnsafe;
    BOOL m_isChatRoomDisplayNameUnsafe;
}

- (void).cxx_destruct;
- (void)OnClickDeleteBtn;
- (void)OnClickHeadImage;
- (void)OnClickViewBtn;
- (void)handleLongPressEx:(id)arg1;
- (void)hiddenAllSubViews;
- (id)initViewInChatRoomProfile;
- (BOOL)isDisplayNameUnsafe;
@property(retain, nonatomic) CContact *m_contact; // @synthesize m_contact;
@property(nonatomic) __weak id <NewChatRoomMemberItemViewDelegate> m_delegate; // @synthesize m_delegate;
@property(readonly) float m_fLeftMargin; // @synthesize m_fLeftMargin;
@property(readonly) float m_fRightMargin; // @synthesize m_fRightMargin;
@property(retain, nonatomic) CContact *m_groupContact; // @synthesize m_groupContact;
@property(nonatomic) unsigned long m_uiIndex; // @synthesize m_uiIndex;
- (void)setNoDisplayName:(BOOL)arg1;
- (void)setTextColor:(id)arg1 shadowColor:(id)arg2;
- (void)showTalkFlag;
- (void)showTrackFlag;
- (void)updateAddItemViewForDelete;
- (void)updateAdminIcon;
- (void)updateAtIndexEx:(unsigned int)arg1 withColumn:(unsigned int)arg2;
- (void)updateCPState;
- (void)updateContact;
- (void)updateContactItemSubview;
- (void)updateContactItemViewForDelete;
- (void)updateDeleteItemViewForDelete;
- (void)updateItemViewForDelete:(BOOL)arg1;
- (void)updateWithAddMemberBtnAtIndexEx:(unsigned int)arg1 withColumn:(unsigned int)arg2;
- (void)updateWithContactEx:(id)arg1 atIndex:(unsigned int)arg2 withColumn:(unsigned int)arg3;
- (void)updateWithDeleteMemberBtnAtIndexEx:(unsigned int)arg1 withColumn:(unsigned int)arg2;
- (void)updateWithViewMemberBtnAtIndexEx:(unsigned int)arg1;
- (void)updateWithViewMemberBtnAtIndexEx:(unsigned int)arg1 withColumn:(unsigned int)arg2;

@end

