//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSData, NSString;

@interface OpLog : NSObject <WCDBCoding>
{
    unsigned long oplogID;
    unsigned long oplogCmdID;
    NSData *oplogBuffer;
    long long m___rowID;
}

+ (id)dummyObject;
- (void).cxx_destruct;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
- (const WCDBCondition_5617ae99 *)db_oplogBuffer;
- (const WCDBCondition_e9b1f587 *)db_oplogCmdID;
- (const WCDBCondition_e9b1f587 *)db_oplogID;
@property(readonly, copy) NSString *description;
- (const map_18e36f99 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_18e36f99 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_55ceb464 *)getValueNameIndexMap;
- (id)getValueTable;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long)getWCDBIndexArrayCount;
- (const basic_string_7d00a7a9 *)getWCDBPrimaryColumnName;
@property(retain, nonatomic) NSData *oplogBuffer; // @synthesize oplogBuffer;
@property(nonatomic) unsigned long oplogCmdID; // @synthesize oplogCmdID;
@property(nonatomic) unsigned long oplogID; // @synthesize oplogID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

