//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@class NSMutableArray;

@interface OrderedDictionary : NSMutableDictionary
{
    NSMutableDictionary *dictionary;
    NSMutableArray *array;
}

- (void).cxx_destruct;
- (id)allValues;
- (id)allValuesForKeyEnumerator:(id)arg1;
- (id)allValuesInOrder;
- (id)allValuesInReverseOrder;
- (id)copy;
- (unsigned int)count;
- (void)dealloc;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned int)arg2;
- (id)init;
- (id)initWithCapacity:(unsigned int)arg1;
- (void)insertObject:(id)arg1 forKey:(id)arg2 atIndex:(unsigned int)arg3;
- (id)keyAtIndex:(unsigned int)arg1;
- (id)keyEnumerator;
- (id)lastKey;
- (id)objectForKey:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (id)reverseKeyEnumerator;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setObjectAsLastObject:(id)arg1 forKey:(id)arg2;
- (void)setupWithCapacity:(unsigned int)arg1;

@end

