//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString, PBCContact, PBCMessageWrap;

@interface PBSessionInfo : NSObject <PBCoding>
{
    BOOL showUnreadCountAsRedDot;
    PBCContact *contact;
    PBCMessageWrap *message;
    unsigned int atMeCount;
    unsigned int greenLabelType;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) unsigned int atMeCount; // @synthesize atMeCount;
@property(retain, nonatomic) PBCContact *contact; // @synthesize contact;
- (const map_18e36f99 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(nonatomic) unsigned int greenLabelType; // @synthesize greenLabelType;
@property(retain, nonatomic) PBCMessageWrap *message; // @synthesize message;
- (void)setFromSessionInfo:(id)arg1;
@property(nonatomic) BOOL showUnreadCountAsRedDot; // @synthesize showUnreadCountAsRedDot;
- (id)toSessionInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

