//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IPreEnterWechatLogicExt.h"
#import "SessionSelectControllerDelegate.h"
#import "ShareMessageConfirmLogicHelperDelegate.h"
#import "UIAlertViewDelegate.h"

@class AppCommunicateData, CContact, CMessageWrap, MMUINavigationController, NSString, ShareMessageConfirmLogicHelper, UIAlertView, UINavigationController;

@interface SendAppMsgHandler : MMObject <SessionSelectControllerDelegate, ShareMessageConfirmLogicHelperDelegate, UIAlertViewDelegate, IPreEnterWechatLogicExt>
{
    NSString *m_nsAppid;
    NSString *m_nsBundleId;
    AppCommunicateData *m_appData;
    CMessageWrap *m_messageWrap;
    UINavigationController *m_sessionSelectViewController;
    ShareMessageConfirmLogicHelper *m_helper;
    CContact *m_oContact;
    UIAlertView *m_alertView;
    BOOL m_bIsHiddenTarBar;
    int m_Scene;
    NSString *m_nsRedirectUrl;
    id <SendAppMsgHandleDelegate> m_delegate;
    MMUINavigationController *_m_navigationController;
}

- (void).cxx_destruct;
- (void)OnBackTo3rdApp:(id)arg1;
- (void)OnSelectSession:(id)arg1 SessionSelectController:(id)arg2;
- (void)OnSelectSessionCancel:(id)arg1;
- (void)OnSendMessageCancel:(id)arg1;
- (void)OnSendMessageFail:(id)arg1 WithError:(int)arg2;
- (void)OnSendMessageOK:(id)arg1;
- (void)OnStayAtWeChat:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)asyncNotifySendAppMsgOk;
- (void)cancelAllHandle;
- (void)cancelAllHandleAndReturn3rdApp;
- (void)cancelSendAppMsg;
- (void)clearAllHandle;
- (void)clearAllHandleAndReturn3rdApp:(BOOL)arg1;
- (void)createConfirmView;
- (void)createConfirmViewWithShakeMusic;
- (void)createSelectSessionView;
- (void)createSelectSessionViewWithShakeMusic;
- (void)dealloc;
- (void)doAppAuth;
- (void)getCustomConfirmView;
- (void)getCustomConfirmViewWithShakeMusic;
- (id)init;
@property(nonatomic) int m_Scene; // @synthesize m_Scene;
@property(nonatomic) __weak id <SendAppMsgHandleDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) MMUINavigationController *m_navigationController; // @synthesize m_navigationController=_m_navigationController;
- (void)onPreEnterWechatDone;
- (void)removeAuthViewController;
- (void)removeConfirmView;
- (void)removeSelectSessionView;
- (void)removeSelectSessionViewWithAnimated:(BOOL)arg1;
- (void)selectSessionView;
- (void)sendAppMsg:(id)arg1;
- (void)sendAppMsg:(id)arg1 bundleId:(id)arg2 withData:(id)arg3;
- (void)shareAuthViewControllerDidCancel:(id)arg1;
- (void)shareAuthViewControllerDidFail:(id)arg1;
- (void)shareAuthViewControllerDidSuccess:(id)arg1 redirectUrl:(id)arg2;
- (void)showAlertView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

