//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MMovieCompressorDelegate.h"
#import "SightCaptureLogic.h"
#import "SightMovieWriterDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SightCameraCapture;

@interface SightCaptureLogicF4 : MMObject <SightMovieWriterDelegate, SightCaptureLogic, MMovieCompressorDelegate>
{
    id <SightCaptureDelegate> m_delegate;
    BOOL m_shouldStart;
    BOOL m_shouldNotifyPreviewReady;
    unsigned int m_currID;
    int m_zoomState;
    BOOL m_lightBoostOn;
    SightCameraCapture *m_movieCapture;
    NSMutableDictionary *m_recorderDict;
    NSMutableArray *m_compressorAry;
    NSObject<OS_dispatch_queue> *m_logicQueue;
}

- (void).cxx_destruct;
- (void)cancelAllRecorder;
- (void)cancelRecord:(unsigned long)arg1;
- (void)capturePreviewImage:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)closeLightBoost;
- (void)dealloc;
- (void)focusAtPoint:(struct CGPoint)arg1;
- (id)genPreviewView:(struct CGRect)arg1;
- (id)getPreset;
- (id)init;
- (BOOL)isCameraOn;
- (BOOL)isLightBoostOn;
- (BOOL)isRecording:(unsigned long)arg1;
- (BOOL)isSupportZoom;
- (void)mMovieCompressor:(id)arg1 onMovieCompressFinished:(id)arg2 thumbImg:(id)arg3 ret:(unsigned long)arg4;
@property(readonly, nonatomic) SightCameraCapture *movieCapture; // @synthesize movieCapture=m_movieCapture;
- (void)movieWriter:(id)arg1 onMovieWriteFailed:(unsigned long)arg2;
- (void)movieWriter:(id)arg1 onMovieWriteFinished:(id)arg2 ret:(unsigned long)arg3;
- (void)onMovieWriterInvalidate:(id)arg1;
- (void)openLightBoost;
- (BOOL)pauseCamera;
- (void)pauseCameraImmediately;
- (unsigned long)prepareHighQualityRecord:(struct CGSize)arg1 maxVideoDuration:(float)arg2;
- (unsigned long)prepareRecord:(struct CGSize)arg1 bitRate:(int)arg2 maxVideoDuration:(float)arg3;
- (unsigned long)prepareRecordF4:(struct CGSize)arg1 bitRate:(int)arg2 needCompress:(BOOL)arg3 maxVideoDuration:(float)arg4;
- (void)realStartRecord;
- (void)setDelegate:(id)arg1;
- (void)setZoomState:(int)arg1;
- (void)startCameraWithAudio:(BOOL)arg1;
- (void)startDeviceAudio;
- (unsigned long)startHighQualityRecord:(struct CGSize)arg1 maxVideoDuration:(float)arg2;
- (void)startQRCodeWatcher;
- (unsigned long)startRecord:(struct CGSize)arg1 bitRate:(int)arg2 maxVideoDuration:(float)arg3;
- (unsigned long)startRecordF4:(struct CGSize)arg1 bitRate:(int)arg2 needCompress:(BOOL)arg3 maxVideoDuration:(float)arg4;
- (void)stopQRCodeWatcher;
- (void)stopRecord:(unsigned long)arg1;
- (void)unregistPreviewView:(id)arg1;
- (int)zoomState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

