//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMQRStrokeViewDelegate.h"
#import "SightPreviewView.h"

@class MMQRStrokeView, NSObject<SightQRCodeScannerDelegate>, NSString, StrokeView;

@interface SightPreviewViewF2 : MMUIView <SightPreviewView, MMQRStrokeViewDelegate>
{
    float m_zoomLevel;
    BOOL m_isReady;
    struct CGSize sizeInPixels;
    float inputWidth;
    float inputHeight;
    float m_currZoomLevel;
    int m_focusInAnim;
    StrokeView *m_focusStroke;
    MMQRStrokeView *m_qrcodeStroke;
    BOOL m_supportQRFrame;
    BOOL _renderFirstFrame;
    BOOL _lightBoostOn;
    int _videoStabilizationMode;
    NSString *_qrData;
    NSObject<SightQRCodeScannerDelegate> *_qrDelegate;
}

- (void).cxx_destruct;
- (void)forceFocusAnimAtPoint:(struct CGPoint)arg1;
- (id)getShineAnim:(float)arg1 count:(unsigned long)arg2;
- (void)hideFocusFrame;
- (id)initWithFrame:(struct CGRect)arg1 previewLayer:(id)arg2;
- (BOOL)isReady;
- (void)layoutSubviews;
@property(nonatomic) BOOL lightBoostOn; // @synthesize lightBoostOn=_lightBoostOn;
- (void)makeQRCodeFrame;
- (void)onFocusState:(BOOL)arg1 atPoint:(struct CGPoint)arg2;
- (void)onQRCodeFind;
- (void)onQRCodeFrame:(float *)arg1 withData:(id)arg2;
- (void)onQRCodeGone;
- (void)onQRCodeTrig;
@property(retain, nonatomic) NSString *qrData; // @synthesize qrData=_qrData;
@property(nonatomic) __weak NSObject<SightQRCodeScannerDelegate> *qrDelegate; // @synthesize qrDelegate=_qrDelegate;
- (void)removeFocusStroke;
@property(readonly, nonatomic) BOOL renderFirstFrame; // @synthesize renderFirstFrame=_renderFirstFrame;
- (void)setOutputWidth:(float)arg1 andHeight:(float)arg2;
- (void)setQRFrameEnable:(BOOL)arg1;
- (void)setQRScannerDelegate:(id)arg1;
- (void)setReady;
@property(nonatomic) int videoStabilizationMode; // @synthesize videoStabilizationMode=_videoStabilizationMode;
@property(nonatomic) float zoomLevel; // @synthesize zoomLevel=m_zoomLevel;
- (void)setZoomLevel:(float)arg1 immediatly:(BOOL)arg2;
- (void)startFocusAnimAtPoint:(struct CGPoint)arg1;
- (BOOL)supportQRFrame;
- (struct CGPoint)transformPointInView:(struct CGPoint)arg1;
- (struct CGPoint)transformPointToView:(struct CGPoint)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

