//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface StoreEmotionUtil : NSObject
{
}

+ (id)GetDefaultPathOfEmotionSearchDir;
+ (id)GetDownloadPathOfEmotionSearchDir;
+ (id)GetDownloadPathOfEmotionSearchTempDir;
+ (id)GetDownloadingPathOfEmoticonInTempDirForMd5:(id)arg1;
+ (id)GetPathOfEmoticonInTempDirForMd5:(id)arg1;
+ (id)GetPathOfRewardTipsStatisticsDataFile;
+ (id)GetPathOfTempEmoticonDir;
+ (unsigned int)GetSearchTemplateVesionFromConfigFileInDir:(id)arg1;
+ (id)getEmotionCommonCacheDir;
+ (id)getEmotionDesignerIdDecodeFilePath;
+ (id)getEmotionPersonalDesignerDir;
+ (id)getEmotionPersonalDesignerFilePathForUin:(unsigned long)arg1;
+ (id)getEmotionRewardInfoCacheDir;
+ (id)getEmotionRewardInfoCacheForPid:(id)arg1;
+ (id)getUserEmotionCommonDataDir;

@end

