//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSString;

@interface StoreEmotionBaseCgi : MMObject <PBMessageObserverDelegate>
{
    unsigned long m_eventID;
    id <StoreEmotionBaseCgiDelegate> _baseDelegate;
    NSString *_nsCgiName;
    unsigned long _uiCgi;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
@property(nonatomic) __weak id <StoreEmotionBaseCgiDelegate> baseDelegate; // @synthesize baseDelegate=_baseDelegate;
- (void)handleErrorReturn;
- (void)handleMessageReturnWithResponse:(id)arg1;
- (id)init;
@property(readonly, nonatomic) BOOL isRequesting;
@property(retain, nonatomic) NSString *nsCgiName; // @synthesize nsCgiName=_nsCgiName;
- (void)onReturnError;
@property(nonatomic) unsigned long uiCgi; // @synthesize uiCgi=_uiCgi;
- (BOOL)startRequestWithRequest:(id)arg1;

@end

