//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMsgContentLogicController.h"

@interface TemplateMsgLogicController : BaseMsgContentLogicController
{
}

- (BOOL)CanShowSight;
- (void)ClearUnRead:(id)arg1 FromID:(unsigned long)arg2 ToID:(unsigned long)arg3;
- (void)CustomToolViewEX:(id)arg1;
- (void)DelMsg:(id)arg1 MsgList:(id)arg2 DelAll:(BOOL)arg3;
- (id)GetDownMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(unsigned long)arg3 LeftCount:(unsigned int *)arg4 LeftUnreadCount:(unsigned int *)arg5;
- (id)GetMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(unsigned long)arg3 LeftCount:(unsigned int *)arg4 LeftUnreadCount:(unsigned int *)arg5;
- (id)GetUsrTitle;
- (void)OpenChatView:(id)arg1;
- (void)OpenContactInfo:(id)arg1;
- (BOOL)ShouldShowSearchCompleteRightBarButton;
- (unsigned long)getMsgCountToLoad;
- (void)initViewController;
- (BOOL)isShowHeadImage:(id)arg1;
- (BOOL)shouldShowAppBottomButton;

@end

