//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (Extend)
+ (void)copyFontSetToLocalInfo;
+ (id)dynamicBoldSystemFontOfSize:(float)arg1;
+ (id)dynamicBoldSystemFontOfSize:(float)arg1 forModule:(int)arg2;
+ (float)dynamicFontSize:(float)arg1;
+ (float)dynamicFontSize:(float)arg1 forModule:(int)arg2;
+ (float)dynamicLength:(float)arg1;
+ (float)dynamicLength:(float)arg1 forModule:(int)arg2;
+ (id)dynamicSettingFont:(float)arg1;
+ (id)dynamicSystemFontOfSize:(float)arg1;
+ (id)dynamicSystemFontOfSize:(float)arg1 forModule:(int)arg2;
+ (id)fontBaskervilleSemiBoldOfSize:(float)arg1;
+ (id)fontCochinBoldOfSize:(float)arg1;
+ (id)fontGeorgiaBoldOfSize:(float)arg1;
+ (id)fontHiraKakuProNW3OfSize:(float)arg1;
+ (id)fontJianTiOfSize:(float)arg1;
+ (id)fontMonacoOfSize:(float)arg1;
+ (id)fontSongTiOfSize:(float)arg1;
+ (float)getNormalFontSize;
+ (float)getNormalFontSize:(int)arg1;
+ (float)getNormalFontSizeByLevel:(unsigned long)arg1;
+ (float)getNormalFontSizeByLevelForTimeline:(unsigned long)arg1;
+ (unsigned long)getWebviewFontScale;
+ (void)loadOldFontSet:(unsigned long)arg1;
+ (void)setAppFontSize:(unsigned long)arg1;
+ (void)setAppFontSize:(unsigned long)arg1 andBackTab:(int)arg2;
+ (void)setIpadClassic:(BOOL)arg1;
+ (id)settingFont:(float)arg1;
+ (id)systemBoldBigFont;
+ (id)systemFont;
+ (id)systemLittleFont;
+ (id)systemSmallFont;
+ (BOOL)useDynamicSize;
+ (BOOL)useDynamicSize:(int)arg1;
@end

