//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IAutoVerifySMSExt.h"
#import "PBMessageObserverDelegate.h"
#import "UIAlertViewDelegate.h"
#import "VerifyCodeByVoiceViewControllerDelegate.h"

@class NSString, UITextField;

@interface VerifyPhoneViewController : MMUIViewController <UIAlertViewDelegate, PBMessageObserverDelegate, VerifyCodeByVoiceViewControllerDelegate, IAutoVerifySMSExt>
{
    UITextField *m_verifyCode;
    id <VerifyPhoneDelegate> m_delegate;
    int m_getVerifyCodeCount;
    unsigned long m_uiFromScene;
    NSString *m_nsPhoneNumber;
    BOOL m_bShouldNotRequestValifyCode;
    NSString *m_nsTicket;
    NSString *m_nsAuthTicket;
    NSString *m_nsLanguageCode;
    unsigned long m_uiReadyOpcode;
    unsigned long m_uiCheckOpcode;
    unsigned long m_uiVerifyCGI;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)OnHandleOpenAutoVerifySMS:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)bindFaild;
- (void)bindPhoneOKReturn;
- (id)checkShowVoiceBtn:(struct CGRect)arg1;
- (void)dealloc;
- (void)forwardError;
- (id)getCloseLink;
- (void)handleVerifiedOk:(id)arg1;
- (id)init;
- (void)jumpToUnProtectPage;
@property(nonatomic) BOOL m_bShouldNotRequestValifyCode; // @synthesize m_bShouldNotRequestValifyCode;
@property(nonatomic) __weak id <VerifyPhoneDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSString *m_nsAuthTicket; // @synthesize m_nsAuthTicket;
@property(retain, nonatomic) NSString *m_nsLanguageCode; // @synthesize m_nsLanguageCode;
@property(retain, nonatomic) NSString *m_nsPhoneNumber; // @synthesize m_nsPhoneNumber;
@property(retain, nonatomic) NSString *m_nsTicket; // @synthesize m_nsTicket;
@property(nonatomic) unsigned long m_uiCheckOpcode; // @synthesize m_uiCheckOpcode;
@property(nonatomic) unsigned long m_uiFromScene; // @synthesize m_uiFromScene;
@property(nonatomic) unsigned long m_uiReadyOpcode; // @synthesize m_uiReadyOpcode;
@property(nonatomic) unsigned long m_uiVerifyCGI; // @synthesize m_uiVerifyCGI;
- (void)networkFaild;
- (void)onCallVoiceVerify:(id)arg1;
- (void)onCloseLink;
- (void)onGetVerifyCode:(id)arg1;
- (void)onGetVerifyCodeByVoice:(id)arg1;
- (void)onVerify:(id)arg1;
- (void)opFreqLimited;
- (void)regByPhoneVerifySucceed:(id)arg1;
- (void)removeRegisterInfo;
- (void)saveRegisterInfo;
- (void)sendVerifyCodeFail;
- (void)showSyncAddressBookAlert;
- (void)syncAddressBook;
- (void)trySyncAddressBook;
- (void)verify:(id)arg1;
- (void)verifyFaild;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

