//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

@class MMLoadingView, MMProgressView, UIButton, UIImageView, UILabel, UIView;

@interface VideoMessageNodeView : BaseMessageNodeView
{
    UIImageView *m_oImageView;
    UIView *m_oStatusView;
    UIImageView *m_oStatusBkgView;
    UILabel *m_oTimeLabel;
    UILabel *m_oFileSizeLabel;
    UIView *m_oProgressBkgView;
    MMProgressView *m_oProgressView;
    UIButton *m_oDownloadButton;
    MMLoadingView *m_oLoadingView;
    UIImageView *m_oImageDownloadFailView;
    BOOL m_bhasDownloadComplete;
}

+ (BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (float)BkgImageHeight;
- (void)StartDownloadVideo:(id)arg1;
- (void)StartUploadVideo:(id)arg1;
- (void)StopDownloadVideo:(id)arg1;
- (void)StopUploadVideo:(id)arg1;
- (id)getCoverImage;
- (id)getMessageImageView;
- (id)getMoreMainInfomationAccessibilityDescription;
- (struct CGPoint)getSendOKViewOrgin;
- (BOOL)isTouchInView:(id)arg1;
- (void)layoutSubviewsInternal;
- (void)onClearResource;
- (void)onClick;
- (void)onDisappear;
- (void)onFavoriteAdd:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (void)onMenuItemWillHide;
- (void)onMoreOperate:(id)arg1;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)resend:(id)arg1;
- (void)showOpearation;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (id)thumbImage;
- (void)updateBkgImage:(BOOL)arg1;
- (void)updateContentViewHeight;
- (void)updateStatus:(id)arg1;

@end

