//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCAccountBaseControlLogic.h"

#import "IAddressBookMgrExt.h"
#import "IRsaCertMgrExt.h"
#import "WCAccountGraphicVerifyViewControllerDelegate.h"
#import "WCAccountRegisterViewControllerDelegate.h"

@class NSMutableSet, NSString;

@interface WCAccountRegisterControlLogic : WCAccountBaseControlLogic <IAddressBookMgrExt, WCAccountRegisterViewControllerDelegate, WCAccountGraphicVerifyViewControllerDelegate, IRsaCertMgrExt>
{
    NSMutableSet *m_suggestAlias;
    BOOL m_bCanSyncAddressBook;
    unsigned long m_idc_redirect_count;
    unsigned long m_getSuggestAlias_EventID;
    unsigned long long m_ui64BeginTime;
}

- (void).cxx_destruct;
- (void)DidEnterBackground:(id)arg1;
- (void)DidEnterForeground:(id)arg1;
- (void)OnConfirmAddressBookStatus:(unsigned long)arg1;
- (void)RSAProtobufMessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)dealloc;
- (void)enableAddressBook;
- (id)genNewRegRequest;
- (id)getArchive;
- (id)getBindName;
- (void)getSuggestAlias;
- (void)handleNewRegResponse:(id)arg1;
- (void)handleRespForSuggestAlias:(id)arg1;
- (id)initWithData:(id)arg1;
- (void)jumpToMainFrame;
- (void)onEnableAddressBookTip;
- (void)onGetSuggestAlias:(id)arg1 alias:(id)arg2;
- (void)onGraphicVerifyBack;
- (void)onGraphicVerifyChangeImage;
- (void)onGraphicVerifyWithVerifyCode:(id)arg1;
- (void)onRegNickNameBack;
- (void)onRegNickNameReg:(id)arg1 alias:(id)arg2 headImage:(id)arg3;
- (void)pause;
- (BOOL)recoverFromArchive:(id)arg1;
- (BOOL)regAccount;
- (void)resume;
- (void)showDeniedTip;
- (void)showEnableTip;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

