//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary, NSString, WCADBodyWrap, WCADChainStrengthenInfo, WCADCommentWrap, WCADPageWrap, WCADPoiInfo, WCADVideoWrap, WCMultiLanguageItem;

@interface WCAdvertiseInfo : NSObject <NSCoding>
{
    int adType;
    NSString *adDescription;
    NSString *adActionLink;
    NSString *adActionCardTpId;
    NSString *adActionCardExt;
    NSString *adActionCardTitle;
    int adActionType;
    NSString *adViewId;
    int adPosition;
    int noExposureExpireTime;
    int exposureNoActionExpireTime;
    BOOL webviewRightBarShow;
    NSString *adUserNickName;
    BOOL bExposured;
    int myAdCommentCount;
    unsigned long myAdCommentStartTime;
    NSString *adActionLinkWithTraceId;
    int source;
    NSString *expId;
    BOOL adActionLinkHidden;
    BOOL attachShareLinkHidden;
    BOOL bWithoutAdExp;
    BOOL bIgnoreNewMsgTip;
    BOOL bIgnoreNewLikeMsg;
    BOOL bIgnoreNewCommentMsg;
    BOOL headClickRightBarShow;
    NSString *adActionLinkName;
    WCMultiLanguageItem *expandOutsideTitle;
    WCMultiLanguageItem *expandInsideTitle;
    NSString *uxInfo;
    NSString *attachShareLinkUrl;
    NSString *attachShareLinkWording;
    NSMutableDictionary *adArgsDic;
    unsigned long headClickType;
    NSString *headClickParam;
    WCADPoiInfo *adPoiInfo;
    WCADChainStrengthenInfo *adChainStrengthenInfo;
    int longVideoAcessType;
    NSString *adActionAppStoreTitle;
    NSString *adActionAppStoreLink;
    int adActionAppStoreType;
    WCADBodyWrap *_bodyWrap;
    WCADCommentWrap *_commentWrap;
    WCADPageWrap *_detailPageWrap;
    WCADPageWrap *_h5PageWrap;
    WCADPageWrap *_albumPageWrap;
    WCADVideoWrap *_videoWrap;
    WCADVideoWrap *_streamVideoWrap;
    WCADPageWrap *_poiH5PageWrap;
    unsigned long long commentStartTime;
    unsigned long long commentEndTime;
    unsigned long long unInterestStartTime;
    unsigned long long unInterestEndTime;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adActionAppStoreLink; // @synthesize adActionAppStoreLink;
@property(retain, nonatomic) NSString *adActionAppStoreTitle; // @synthesize adActionAppStoreTitle;
@property(nonatomic) int adActionAppStoreType; // @synthesize adActionAppStoreType;
@property(retain, nonatomic) NSString *adActionCardExt; // @synthesize adActionCardExt;
@property(retain, nonatomic) NSString *adActionCardTitle; // @synthesize adActionCardTitle;
@property(retain, nonatomic) NSString *adActionCardTpId; // @synthesize adActionCardTpId;
@property(retain, nonatomic) NSString *adActionLink; // @synthesize adActionLink;
@property(nonatomic) BOOL adActionLinkHidden; // @synthesize adActionLinkHidden;
@property(retain, nonatomic) NSString *adActionLinkName; // @synthesize adActionLinkName;
@property(retain, nonatomic) NSString *adActionLinkWithTraceId; // @synthesize adActionLinkWithTraceId;
@property(nonatomic) int adActionType; // @synthesize adActionType;
@property(retain, nonatomic) NSMutableDictionary *adArgsDic; // @synthesize adArgsDic;
@property(retain, nonatomic) WCADChainStrengthenInfo *adChainStrengthenInfo; // @synthesize adChainStrengthenInfo;
@property(retain, nonatomic) NSString *adDescription; // @synthesize adDescription;
@property(retain, nonatomic) WCADPoiInfo *adPoiInfo; // @synthesize adPoiInfo;
@property(nonatomic) int adPosition; // @synthesize adPosition;
@property(nonatomic) int adType; // @synthesize adType;
@property(retain, nonatomic) NSString *adUserNickName; // @synthesize adUserNickName;
@property(retain, nonatomic) NSString *adViewId; // @synthesize adViewId;
@property(retain, nonatomic) WCADPageWrap *albumPageWrap; // @synthesize albumPageWrap=_albumPageWrap;
@property(nonatomic) BOOL attachShareLinkHidden; // @synthesize attachShareLinkHidden;
@property(retain, nonatomic) NSString *attachShareLinkUrl; // @synthesize attachShareLinkUrl;
@property(retain, nonatomic) NSString *attachShareLinkWording; // @synthesize attachShareLinkWording;
@property(nonatomic) BOOL bExposured; // @synthesize bExposured;
@property(nonatomic) BOOL bIgnoreNewCommentMsg; // @synthesize bIgnoreNewCommentMsg;
@property(nonatomic) BOOL bIgnoreNewLikeMsg; // @synthesize bIgnoreNewLikeMsg;
@property(nonatomic) BOOL bIgnoreNewMsgTip; // @synthesize bIgnoreNewMsgTip;
@property(nonatomic) BOOL bWithoutAdExp; // @synthesize bWithoutAdExp;
@property(retain, nonatomic) WCADBodyWrap *bodyWrap; // @synthesize bodyWrap=_bodyWrap;
@property(nonatomic) unsigned long long commentEndTime; // @synthesize commentEndTime;
@property(nonatomic) unsigned long long commentStartTime; // @synthesize commentStartTime;
@property(retain, nonatomic) WCADCommentWrap *commentWrap; // @synthesize commentWrap=_commentWrap;
@property(retain, nonatomic) WCADPageWrap *detailPageWrap; // @synthesize detailPageWrap=_detailPageWrap;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *expId; // @synthesize expId;
@property(retain, nonatomic) WCMultiLanguageItem *expandInsideTitle; // @synthesize expandInsideTitle;
@property(retain, nonatomic) WCMultiLanguageItem *expandOutsideTitle; // @synthesize expandOutsideTitle;
@property(nonatomic) int exposureNoActionExpireTime; // @synthesize exposureNoActionExpireTime;
- (id)genAdStatExt:(BOOL)arg1;
- (id)getAdActionLink;
- (id)getAdActionTitle;
- (unsigned long)getAdClickLinkActionType;
@property(retain, nonatomic) WCADPageWrap *h5PageWrap; // @synthesize h5PageWrap=_h5PageWrap;
- (BOOL)hasMyAdComments;
@property(retain, nonatomic) NSString *headClickParam; // @synthesize headClickParam;
@property(nonatomic) BOOL headClickRightBarShow; // @synthesize headClickRightBarShow;
@property(nonatomic) unsigned long headClickType; // @synthesize headClickType;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (BOOL)isAppstoreInternalJump;
- (BOOL)isVaildForShow;
- (BOOL)isValidForJumpAppstore;
@property(nonatomic) int longVideoAcessType; // @synthesize longVideoAcessType;
@property(nonatomic) int myAdCommentCount; // @synthesize myAdCommentCount;
@property(nonatomic) unsigned long myAdCommentStartTime; // @synthesize myAdCommentStartTime;
@property(nonatomic) int noExposureExpireTime; // @synthesize noExposureExpireTime;
@property(retain, nonatomic) WCADPageWrap *poiH5PageWrap; // @synthesize poiH5PageWrap=_poiH5PageWrap;
@property(nonatomic) int source; // @synthesize source;
@property(retain, nonatomic) WCADVideoWrap *streamVideoWrap; // @synthesize streamVideoWrap=_streamVideoWrap;
@property(nonatomic) unsigned long long unInterestEndTime; // @synthesize unInterestEndTime;
@property(nonatomic) unsigned long long unInterestStartTime; // @synthesize unInterestStartTime;
@property(retain, nonatomic) NSString *uxInfo; // @synthesize uxInfo;
@property(retain, nonatomic) WCADVideoWrap *videoWrap; // @synthesize videoWrap=_videoWrap;
@property(nonatomic) BOOL webviewRightBarShow; // @synthesize webviewRightBarShow;

@end

