//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCCardPkgExt.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCCardUsedStoreViewDelegate.h"

@class MMTableView, NSArray, NSString;

@interface WCCardUsedStoresViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, UIAlertViewDelegate, IWCCardPkgExt, WCCardUsedStoreViewDelegate>
{
    id <WCCardDataSource> _cardDataSource;
    NSArray *_tableDatas;
    MMTableView *_tableView;
}

- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dealloc;
- (void)hardCodeData;
- (void)initData;
- (void)initView;
- (id)initWithCardDataSource:(id)arg1;
- (void)makeStoreCell:(id)arg1 storeInfo:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onGetUsedStoreList:(id)arg1 ErrCode:(int)arg2;
- (void)onNavigation:(id)arg1;
- (void)onRetrieveLocation:(int)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

