//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCShareCardPkgExt.h"
#import "MMWebImageViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCCardMsgViewDelegate.h"
#import "WCNewShareCardConsumedViewDelegate.h"
#import "tableViewDelegate.h"

@class MMTableView, MMUIButton, MMUILabel, NSMutableArray, NSMutableDictionary, NSString, UIActivityIndicatorView, UIScrollView, UIView, WCNewShareCardConsumedView;

@interface WCCardMsgCenterViewController : MMUIViewController <IWCShareCardPkgExt, WCNewShareCardConsumedViewDelegate, UITableViewDataSource, UITableViewDelegate, tableViewDelegate, WCActionSheetDelegate, MMWebImageViewDelegate, WCCardMsgViewDelegate>
{
    NSMutableArray *_msgList;
    NSMutableDictionary *_cellHeightDic;
    UIScrollView *_emptyView;
    UIView *_navHeaderView;
    MMTableView *_tableView;
    MMUIButton *_footerView;
    UIActivityIndicatorView *_activityView;
    MMUILabel *_loadLabel;
    unsigned long _curMinUpdateTime;
    NSString *_lastShareCardConsumedMsgCardID;
    WCNewShareCardConsumedView *_newConsumendView;
    BOOL _bForNewMsg;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(nonatomic) BOOL bForNewMsg; // @synthesize bForNewMsg=_bForNewMsg;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)genNormalCell:(id)arg1 IndexPath:(id)arg2;
- (void)hideEmptyView;
- (id)init;
- (void)initData;
- (void)initEmptyView;
- (void)initNavigationBar;
- (void)initTableView;
- (BOOL)isAddedMsg:(id)arg1;
@property(retain, nonatomic) NSMutableArray *msgList; // @synthesize msgList=_msgList;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onAcceptCard:(id)arg1;
- (void)onAction:(id)arg1;
- (void)onClearAllMsg;
- (void)onFooterClicked;
- (void)onJumpUrl:(id)arg1;
- (void)onLoadImageOK:(id)arg1;
- (void)onLoadMore;
- (void)onMsgNotifyShareCardConsumed:(id)arg1 sharedCardId:(id)arg2 consumedBoxId:(id)arg3 subscribeAppUserName:(id)arg4 subscribeWording:(id)arg5 retMsg:(id)arg6;
- (void)onOperate;
- (void)onShareCardAfterConsumed:(BOOL)arg1;
- (void)reloadTableView;
- (void)safeAddMsgList:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sortMsgList;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)updateTableFooterHasMore:(BOOL)arg1;
- (BOOL)useTransparentNavibar;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

