//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDataBaseItem;

@interface WCDBTableColumnInfo : NSObject
{
    BOOL m_isRowId;
    WCDataBaseItem *m_item;
    unsigned int m_objectIndex;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL m_isRowId; // @synthesize m_isRowId;
@property(retain, nonatomic) WCDataBaseItem *m_item; // @synthesize m_item;
@property(nonatomic) unsigned int m_objectIndex; // @synthesize m_objectIndex;

@end

