//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCDBTableQueryInfo : NSObject
{
    vector_24c76cbd m_vecProperty;
    basic_string_7d00a7a9 m_tableName;
    BOOL m_hasFileProperty;
    Class m_tableClass;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) BOOL m_hasFileProperty; // @synthesize m_hasFileProperty;
@property(nonatomic) Class m_tableClass; // @synthesize m_tableClass;
- (const vector_24c76cbd *)selectProperty;
- (void)setSelectProperty:(const vector_24c76cbd *)arg1;
- (void)setTableInfo:(id)arg1;
- (const basic_string_7d00a7a9 *)tableName;

@end

