//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData, NSString;

@interface WCLocationInfo : NSObject <NSCoding>
{
    NSString *city;
    CDStruct_2c43369c location;
    NSString *poiName;
    NSString *poiAddress;
    float poiScale;
    NSString *poiInfoUrl;
    NSString *poiClassifyId;
    int poiClassifyType;
    int poiClickableStatus;
    NSData *poiBuff;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *city; // @synthesize city;
- (void)encodeWithCoder:(id)arg1;
- (id)getDisplayCity;
- (id)getDisplayPOIAddress;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (BOOL)isLocationValid;
- (BOOL)isPoiInfo;
- (BOOL)isPoiInfoClickable;
- (BOOL)isValidForShow;
@property(nonatomic) CDStruct_c3b9c2ee location; // @synthesize location;
@property(retain, nonatomic) NSString *poiAddress; // @synthesize poiAddress;
@property(retain, nonatomic) NSData *poiBuff; // @synthesize poiBuff;
@property(retain, nonatomic) NSString *poiClassifyId; // @synthesize poiClassifyId;
@property(nonatomic) int poiClassifyType; // @synthesize poiClassifyType;
@property(nonatomic) int poiClickableStatus; // @synthesize poiClickableStatus;
@property(retain, nonatomic) NSString *poiInfoUrl; // @synthesize poiInfoUrl;
@property(retain, nonatomic) NSString *poiName; // @synthesize poiName;
@property(nonatomic) float poiScale; // @synthesize poiScale;

@end

