//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCMallActivityInfo : NSObject
{
    unsigned long m_uiActivityExpiredTime;
    NSString *m_nsActivityIconLink;
    NSString *m_nsActivityId;
    NSString *m_nsActivityLink;
    NSString *m_nsActivityMessageContent;
    NSString *m_nsActivityTips;
    unsigned long m_uiActivityJumpFunctionId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *m_nsActivityIconLink; // @synthesize m_nsActivityIconLink;
@property(retain, nonatomic) NSString *m_nsActivityId; // @synthesize m_nsActivityId;
@property(retain, nonatomic) NSString *m_nsActivityLink; // @synthesize m_nsActivityLink;
@property(retain, nonatomic) NSString *m_nsActivityMessageContent; // @synthesize m_nsActivityMessageContent;
@property(retain, nonatomic) NSString *m_nsActivityTips; // @synthesize m_nsActivityTips;
@property(nonatomic) unsigned long m_uiActivityExpiredTime; // @synthesize m_uiActivityExpiredTime;
@property(nonatomic) unsigned long m_uiActivityJumpFunctionId; // @synthesize m_uiActivityJumpFunctionId;

@end

