//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IWCCardPkgExt.h"
#import "IWCShareCardPkgExt.h"

@class NSMutableArray, NSMutableDictionary, NSString, WCNewShareCardLayoutCache;

@interface WCNewShareCardListLogicController : MMObject <IWCCardPkgExt, IWCShareCardPkgExt>
{
    BOOL _bIsLocalCityLayoutDataEnd;
    BOOL _bIsOtherCityLayourDataEnd;
    BOOL _bIsLayoutCacheExist;
    BOOL _bIsProcessingLayoutRequest;
    BOOL _bHadGetMyCardListLayout;
    id <WCNewShareCardListLogicDelegate> _delegate;
    NSMutableDictionary *_dictAllShareCardTpIdData;
    NSMutableDictionary *_dictAllGroupShareCardData;
    WCNewShareCardLayoutCache *_shareCardLayoutCache;
    NSString *_curCityName;
    NSMutableArray *_arrMyCardListLayout;
    NSMutableArray *_arrSections;
    NSString *_curSelectCardId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *arrMyCardListLayout; // @synthesize arrMyCardListLayout=_arrMyCardListLayout;
@property(retain, nonatomic) NSMutableArray *arrSections; // @synthesize arrSections=_arrSections;
@property(nonatomic) BOOL bHadGetMyCardListLayout; // @synthesize bHadGetMyCardListLayout=_bHadGetMyCardListLayout;
@property(nonatomic) BOOL bIsLayoutCacheExist; // @synthesize bIsLayoutCacheExist=_bIsLayoutCacheExist;
@property(nonatomic) BOOL bIsLocalCityLayoutDataEnd; // @synthesize bIsLocalCityLayoutDataEnd=_bIsLocalCityLayoutDataEnd;
@property(nonatomic) BOOL bIsOtherCityLayourDataEnd; // @synthesize bIsOtherCityLayourDataEnd=_bIsOtherCityLayourDataEnd;
@property(nonatomic) BOOL bIsProcessingLayoutRequest; // @synthesize bIsProcessingLayoutRequest=_bIsProcessingLayoutRequest;
- (void)calcTableViewSectionData;
- (void)clearDataWhenWillDealloc;
@property(retain, nonatomic) NSString *curCityName; // @synthesize curCityName=_curCityName;
@property(retain, nonatomic) NSString *curSelectCardId; // @synthesize curSelectCardId=_curSelectCardId;
- (void)dealloc;
- (BOOL)delCurrentShareCardListDataWithSvrData:(id)arg1;
- (BOOL)delUselessCardTpId:(id)arg1;
- (BOOL)delUselessCardTpIdInLocalCityList:(id)arg1;
- (BOOL)delUselessCardTpIdInOtherCityList:(id)arg1;
@property(nonatomic) __weak id <WCNewShareCardListLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (id)detectAnimationCardIndexPathInLocalCityList;
@property(retain, nonatomic) NSMutableDictionary *dictAllGroupShareCardData; // @synthesize dictAllGroupShareCardData=_dictAllGroupShareCardData;
@property(retain, nonatomic) NSMutableDictionary *dictAllShareCardTpIdData; // @synthesize dictAllShareCardTpIdData=_dictAllShareCardTpIdData;
- (unsigned int)getAllAvaiableCardTpIdCount;
- (unsigned int)getAllAvaiableShareCardCount;
- (id)getCurCityName;
- (unsigned int)getLocalCityShareCardCount;
- (id)getLocalCityShareCardDataListInRow:(unsigned int)arg1;
- (id)getMyCardPkgLayout;
- (unsigned int)getOtherCityShareCardCount;
- (id)getOtherCityShareCardDataListInRow:(unsigned int)arg1;
- (id)getSectionTypeOfIndex:(unsigned int)arg1;
- (void)getShareCardDataFromDBWithCacheLocalCityList:(id)arg1 withCacheOtherCityList:(id)arg2 withCacheCityName:(id)arg3;
- (BOOL)getShareCardDataFromDBWithCardTpId:(id)arg1 withAouncementStr:(id)arg2;
- (id)getShareCardFromDBWithCardId:(id)arg1;
- (void)getShareCardHomePageLayout;
- (unsigned int)getTableViewSectionCount;
- (void)handleHomePageLocalCityLayout:(id)arg1 isFirstPage:(BOOL)arg2 isLocalCityEnd:(BOOL)arg3;
- (void)handleHomePageOtherCityLayout:(id)arg1 isLocalCityEnd:(BOOL)arg2;
- (void)handleUserDeleteShareCardList:(id)arg1;
- (void)handleViewControllerWillReload;
- (BOOL)hasCardDataToShow;
- (BOOL)hasMoreLayoutData;
- (BOOL)hasMoreLocalCityLayoutData;
- (BOOL)hasMoreOtherCityLoyoutData;
- (BOOL)hasUnreadMessage;
- (id)init;
- (void)initData;
- (BOOL)isProcessingLayoutRequest;
- (BOOL)loadMoreHomePageLayoutData;
- (BOOL)loadShareCardLayoutCacheIfExist;
- (void)onGetCardLayout;
- (void)onGetShareCardsHomePageLayout:(id)arg1 andOtherCityList:(id)arg2 withCityName:(id)arg3 isLocalCityEnd:(BOOL)arg4 isOtherCityEnd:(BOOL)arg5 isFirstPageData:(BOOL)arg6;
- (void)onGetShareCardsLayoutError;
- (void)onRetrieveLocation:(int)arg1;
- (void)onUpdateShareCard:(id)arg1 Error:(int)arg2;
- (void)onUpdateShareCardList:(id)arg1;
- (void)onWCCardMessageUnreadCountChanged:(id)arg1;
- (void)refreshHomePageLayoutData;
- (void)reloadViewController:(BOOL)arg1;
- (BOOL)replaceShareCard:(id)arg1 inList:(id)arg2;
- (void)saveShareCardLayoutCache;
- (void)setCurrentSelectCardId:(id)arg1;
- (void)setShareCardCommonPropertyTo:(id)arg1 from:(id)arg2;
@property(retain, nonatomic) WCNewShareCardLayoutCache *shareCardLayoutCache; // @synthesize shareCardLayoutCache=_shareCardLayoutCache;
- (void)startLoadMyCardLayout;
- (void)syncShareCardData;
- (BOOL)updateCurrentShareCardListDataWithSvrData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

