//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "AVAssetResourceLoaderDelegate.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, AVURLAsset, NSString;

@interface WCNetworkMediaCore : MMObject <AVAssetResourceLoaderDelegate>
{
    WCNetworkMediaCore *weakSelf;
    BOOL hasPlayed;
    BOOL m_isNeedRestartMusic;
    NSString *url;
    AVPlayerLayer *layer;
    id <WCNetworkMediaCoreDelegate> delegate;
    AVURLAsset *m_asset;
    AVPlayerItem *m_item;
    AVPlayer *m_player;
    int m_state;
    struct CGSize m_videoSize;
    double m_duration;
    double m_cacheDuration;
}

- (void).cxx_destruct;
- (double)cacheDuration;
- (double)currentPosition;
- (void)dealloc;
@property(nonatomic) __weak id <WCNetworkMediaCoreDelegate> delegate; // @synthesize delegate;
- (double)duration;
- (void)initPlayer;
- (id)initWithURL:(id)arg1;
- (void)internalPlay;
@property(retain, nonatomic) AVPlayerLayer *layer; // @synthesize layer;
@property(retain, nonatomic) AVURLAsset *m_asset; // @synthesize m_asset;
@property(nonatomic) double m_cacheDuration; // @synthesize m_cacheDuration;
@property double m_duration; // @synthesize m_duration;
@property(nonatomic) BOOL m_isNeedRestartMusic; // @synthesize m_isNeedRestartMusic;
@property(retain, nonatomic) AVPlayerItem *m_item; // @synthesize m_item;
@property(retain, nonatomic) AVPlayer *m_player; // @synthesize m_player;
@property struct CGSize m_videoSize; // @synthesize m_videoSize;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onCacheRangeChange:(id)arg1;
- (void)onPlaybackEnd:(id)arg1;
- (void)onPlaybackFailedToEnd:(id)arg1;
- (void)onPlaybackStalled:(id)arg1;
- (void)onPlayerItemStatusChange:(int)arg1;
- (void)onPlayerStatusChange:(int)arg1;
- (void)pause;
- (void)play;
- (void)seekTo:(double)arg1;
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(readonly, nonatomic) int state; // @synthesize state=m_state;
- (void)updateState:(int)arg1;
- (struct CGSize)videoSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

