//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "CSettingExt.h"
#import "MMPatternLockLogicDelegate.h"
#import "MMPatternLockMgrExt.h"

@class MMBadgeView, MMTableViewCellInfo, NSDictionary, NSString;

@interface WCPayPwdViewController : WCPayBaseViewController <MMPatternLockLogicDelegate, CSettingExt, MMPatternLockMgrExt>
{
    id <WCPayPwdViewControllerDelegate> m_delegate;
    BOOL _isDeductShowNew;
    unsigned int _patternLockStatus;
    int _curScene;
    MMTableViewCellInfo *_switchCellInfo;
    unsigned long _patternLockLogicTag;
    MMTableViewCellInfo *_touchIDSwitchCellInfo;
    MMBadgeView *_touchIDSwithBadgeView;
    NSDictionary *_payManageData;
    MMTableViewCellInfo *_payManageCellInfo;
}

- (void).cxx_destruct;
- (void)OnBack;
@property(nonatomic) int curScene; // @synthesize curScene=_curScene;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)getEnteranceViewContoller;
- (void)gotoPayManage:(id)arg1;
- (id)init;
- (void)initCellView;
- (void)initPayManageDataFromCacheOrNetwork;
@property(nonatomic) BOOL isDeductShowNew; // @synthesize isDeductShowNew=_isDeductShowNew;
@property(nonatomic) __weak id <WCPayPwdViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void)onModifyPatternLock;
- (void)onModifyPwd;
- (void)onPatternLockLogicOperateCancel;
- (void)onPatternLockLogicOperateSuccess;
- (void)onPatternLockSvrCheckStatusBack:(unsigned int)arg1;
- (void)onResetPwd;
- (void)onSettingChanged:(int)arg1;
- (void)onSwitchChange:(id)arg1;
- (void)onTouchIDSwitchChanged:(id)arg1;
@property(nonatomic) unsigned long patternLockLogicTag; // @synthesize patternLockLogicTag=_patternLockLogicTag;
@property(nonatomic) unsigned int patternLockStatus; // @synthesize patternLockStatus=_patternLockStatus;
@property(retain, nonatomic) MMTableViewCellInfo *payManageCellInfo; // @synthesize payManageCellInfo=_payManageCellInfo;
@property(retain, nonatomic) NSDictionary *payManageData; // @synthesize payManageData=_payManageData;
- (void)reloadTable;
@property(retain, nonatomic) MMTableViewCellInfo *switchCellInfo; // @synthesize switchCellInfo=_switchCellInfo;
@property(retain, nonatomic) MMTableViewCellInfo *touchIDSwitchCellInfo; // @synthesize touchIDSwitchCellInfo=_touchIDSwitchCellInfo;
- (void)setTouchIDSwitchValue:(BOOL)arg1;
@property(retain, nonatomic) MMBadgeView *touchIDSwithBadgeView; // @synthesize touchIDSwithBadgeView=_touchIDSwithBadgeView;
- (void)showNewForCellIfNeed:(id)arg1;
- (void)showNewForDeductCellIfNeeded;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidBePushed:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

