//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureSession, AVCaptureVideoPreviewLayer, NSString, ScanLicenceBackgroundView, UIView, WCPayCardNumberScanForeView;

@interface WCPayCardNumberScanViewController : MMUIViewController <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    int cutImgVScreenHeight;
    int cutImgVScreenWidth;
    struct MyImage *origImg;
    struct MyImage *grayImg;
    UIView *_topBarView;
    UIView *_bottomBarView;
    UIView *_leftBarView;
    UIView *_rightBarView;
    ScanLicenceBackgroundView *m_backgroundView;
    WCPayCardNumberScanForeView *m_foreView;
    BOOL shouldStopCapture;
    BOOL _didHandledRotate;
    BOOL _didSetupUI;
    NSString *_username;
    id <WCPayCardNumberScanDelegate> _delegate;
    AVCaptureSession *_captureSession;
    AVCaptureVideoPreviewLayer *_prevLayer;
}

- (void).cxx_destruct;
- (BOOL)addOutput:(id)arg1;
- (void)backAction:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
- (void)continuousAutoFocus:(struct CGPoint)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <WCPayCardNumberScanDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finalizeCapture;
- (float)getRotateRadius:(int)arg1;
- (void)handleVisible:(BOOL)arg1 forView:(id)arg2;
- (void)personTipsAction:(id)arg1;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *prevLayer; // @synthesize prevLayer=_prevLayer;
- (void)printVersion;
- (void)setBarViewToInvisible:(id)arg1;
- (void)setGreenBarView;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void)setupEngine;
- (void)setupUI;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)startCapture;
- (void)stopCapture;
- (void)stopEngine;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)useHighResolution;
- (struct CGRect)viewBounds;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewDidTransitionToNewSize;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

