//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCUIUtil : NSObject
{
}

+ (id)getDefaultProductImage:(int)arg1;
+ (id)getErrTipForDataItem:(id)arg1;
+ (id)getLocalizedArrayGroupName:(id)arg1;
+ (id)getLocalizedGroupName:(id)arg1;
+ (float)getTimelineImageCompressRate;
+ (id)getTimelineSortLabelName;
+ (id)getWCGroupPrivacyContent;
+ (BOOL)showCellSource:(id)arg1;
+ (BOOL)showCellSummary;
+ (void)updateTimelineSortLabelName:(id)arg1 arrSortLabelName:(id)arg2;

@end

