//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCWatchSettingCommonViewController.h"

#import "MMWebImageViewDelegate.h"

@class MMWebImageView, NSArray, NSString, NSTimer, UILabel, UIView;

@interface WCWatchMomentsViewController : WCWatchSettingCommonViewController <MMWebImageViewDelegate>
{
    BOOL _photoInfoShowed;
    NSArray *_photoItemList;
    UIView *_albumContainer;
    UIView *_albumPhotoViewContainer;
    MMWebImageView *_albumPhotoView;
    UIView *_albumPhotoInfoView;
    UILabel *_albumPhotoInfoLabel;
    int _photoIndex;
    UILabel *_timeLabel;
    UIView *_recentRowView;
    NSTimer *_timeLabelTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *albumContainer; // @synthesize albumContainer=_albumContainer;
@property(retain, nonatomic) UILabel *albumPhotoInfoLabel; // @synthesize albumPhotoInfoLabel=_albumPhotoInfoLabel;
@property(retain, nonatomic) UIView *albumPhotoInfoView; // @synthesize albumPhotoInfoView=_albumPhotoInfoView;
@property(retain, nonatomic) MMWebImageView *albumPhotoView; // @synthesize albumPhotoView=_albumPhotoView;
@property(retain, nonatomic) UIView *albumPhotoViewContainer; // @synthesize albumPhotoViewContainer=_albumPhotoViewContainer;
- (void)dealloc;
- (void)handleCoverAnimationFinishedAndStartAgain;
- (void)hidePhotoInfo;
- (void)initUI;
- (void)onLoadImageOK:(id)arg1;
@property(nonatomic) int photoIndex; // @synthesize photoIndex=_photoIndex;
@property(nonatomic) BOOL photoInfoShowed; // @synthesize photoInfoShowed=_photoInfoShowed;
@property(retain, nonatomic) NSArray *photoItemList; // @synthesize photoItemList=_photoItemList;
@property(retain, nonatomic) UIView *recentRowView; // @synthesize recentRowView=_recentRowView;
- (void)refreshTimeLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) NSTimer *timeLabelTimer; // @synthesize timeLabelTimer=_timeLabelTimer;
- (void)showPhotoInfo;
- (void)startCurrentCoverAnimation;
- (void)startLoadingNextCoverImage;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

